# Label configuration for PR Labeler
# https://github.com/actions/labeler

backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**"

frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "doc/**"
          - "*.md"
          - "**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Dockerfile"
          - "docker-compose*.yml"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.spec.ts"
          - "**/*.test.ts"
          - "**/test/**"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "*.json"
          - "*.yml"
          - "*.yaml"
          - ".env*"
