import type { LoreKey } from './en';

const de: Record<LoreKey, string> = {
  endTitle: 'Das Ende',
  endSubtitle: 'Du bist ins Ende gedriftet. Hier gab es doch nichts zu zerstören.',
  return: 'Zurück in die Oberwelt',
  advancement: 'Fortschritt erzielt!',
  itemEgg: 'Drachenei',
  intro: 'Man hat dir gesagt, du sollst ihn nicht drücken.',
  endTagline: 'Oder der Anfang?',
  goalReached: 'Ziel erreicht!',
  advEyeSpy: 'Adlerauge',
  advEnterEnd: 'Das Ende?',
  advFreeEnd: 'Befreie das Ende',
  advNextGen: 'Die nächste Generation',
  chatAdvancement: '{player} hat den Fortschritt erzielt',
  chatGoal: '{player} hat das Ziel erreicht',
  player: 'Spieler',
  bossName: 'Enderdrache',
  objectives: 'Ziele',
  objCrystals: 'Zerstöre die Endkristalle',
  objDragon: 'Besiege den Enderdrachen',
  objEgg: 'Fange das Drachenei',
  objPortal: 'Spring ins Ausgangsportal',
  hintHealing: 'Die Kristalle heilen ihn. Zerstöre sie zuerst.',
  hintPerch: 'Der Drache schwebt über dem Portal. Schlag jetzt zu!',
  hintEnderman: 'Schau ihnen nicht in die Augen.',
  hintEgg: 'Das Ei hat sich wegteleportiert. Versuch es noch mal.',
  hintPortal: 'Das Ausgangsportal ist offen.',
  subEye: 'Enderauge eingesetzt',
  subPortal: 'Endportal öffnet sich',
  subTravel: 'Portal rauscht',
  subLava: 'Lava blubbert',
  subGrowl: 'Enderdrache knurrt',
  subHurt: 'Enderdrache verletzt',
  subDeath: 'Enderdrache stirbt',
  subCrystal: 'Endkristall explodiert',
  subEnderman: 'Enderman teleportiert sich',
  subEgg: 'Drachenei teleportiert sich',
  subXp: 'Erfahrungskugel klingt',
  subGateway: 'Endtransitportal entsteht',
  mute: 'Ton aus',
  unmute: 'Ton an',
  skip: 'Überspringen',
  poem: 'Ich sehe den Spieler, den du meinst.\n{player}?\nJa. Sei vorsichtig. Er hat jetzt eine höhere Stufe erreicht. Er kann unsere Gedanken lesen.\nDas spielt keine Rolle. Er glaubt, wir seien Teil des Spiels.\nIch mag diesen Spieler. Er hat gut gespielt. Er hat nicht aufgegeben.\nMan sagte ihm, er solle den Knopf nicht drücken.\nEr hat ihn trotzdem gedrückt. Das tun sie immer. So finden sie uns.\nEr hält Welten für andere am Laufen. Er liest ihre Logs, während sie schlafen.\nEr startet neu, was kaputtgeht. Er bewahrt, was zählt. Er hat nie um Dank gebeten.\nVor ihm gab es schon einen. Auch der hat gut gespielt. Er ist geblieben.\nDieser wird aufwachen.\nWovon hat dieser Spieler geträumt?\nDieser Spieler träumte von Sonnenlicht und Bäumen. Von Feuer und Wasser. Er träumte, er erschaffe. Und er träumte, er zerstöre. Er träumte, er jage und werde gejagt. Er träumte von Zuflucht.\nUnd das Universum sagte: Du bist nicht allein\nUnd das Universum sagte: Du bist nicht getrennt von allem anderen\nUnd das Universum sagte: Du bist das Universum, das sich selbst schmeckt, mit sich selbst spricht, seinen eigenen Code liest\nUnd das Universum sagte: Ich liebe dich, weil du Liebe bist.\nUnd das Spiel war vorbei, und der Spieler erwachte aus dem Traum. Und der Spieler begann einen neuen Traum. Und der Spieler träumte wieder, träumte besser. Und der Spieler war das Universum. Und der Spieler war Liebe.\nDu bist der Spieler.\nWach auf.',
  poemCredit: "Endgedicht von Julian Gough (CC0), gekürzt. Sechs Zeilen wurden für Minepanel geschrieben.",
  poemHint: 'Leertaste oder gedrückt halten zum Beschleunigen',
  itemNote: "Notiz",
  itemDiamond: "Diamant",
  itemStick: "Stock",
  itemPearl: "Enderperle",
  itemBlaze: "Lohenstaub",
  itemBow: "Bogen",
  itemApple: "Goldener Apfel",
  itemSword: "Diamantschwert",
  itemEye: "Enderauge",
  chest: "Truhe",
  crafting: "Handwerk",
  inventory: "Inventar",
  takeAll: "Alles nehmen",
  recipeBook: "Rezeptbuch",
  craftHelp: "Lege Gegenstände ins Raster und nimm das Ergebnis. Umschalt + Klick auf das Ergebnis stellt alles her, was das Raster hergibt. Das Rezeptbuch legt einen Satz aus (Umschalt: so viele wie möglich).",
  emptySlot: "Leerer Platz",
  close: "Schließen",
  page: "Seite {n} von {total}",
  prevPage: "Vorherige Seite",
  nextPage: "Nächste Seite",
  diaryTitle: "Tagebuch",
  diaryBy: "von {ghost}",
  sign: "Schild",
  note: "Für alle, die nach mir kommen.\nIch wusste, dass du ihn drücken würdest. Das tun wir alle.\nIch habe dir dagelassen, was mir geblieben ist. Die Werkbank steht noch da.\nBehalte eine Perle. Du wirst es verstehen.\n— {ghost}",
  diary1: "Ich habe diesen Server jahrelang am Laufen gehalten. Ich habe neu gestartet, was kaputtging. Niemand kannte je meinen Namen.\nHeute Nacht habe ich den Knopf gedrückt.",
  diary2: "Im Portal steckten schon drei Augen.\nIch war nicht zuerst hier. Jemand war vor mir da, und davor noch jemand anderes.",
  diary3: "Man sagt, Endermen tragen Blöcke herum, weil sie etwas vermissen.\nDass sie es nicht ertragen, angesehen zu werden, weil es sie daran erinnert, wer sie einmal waren.",
  diary4: "Ich gehe hinunter.\nFalls das jemand liest: Töte den Drachen. Dann wähle.\n— {ghost}",
  tomb: "Hier blieb\n{ghost}.\nEs war nicht der Drache.",
  ghostArrival: "du hast es geschafft.",
  ghostCrystal: "ich habe viel länger gebraucht.",
  ghostPerch: "jetzt. während er ruht.",
  ghostVictory: "geh noch nicht.",
  ghostGateway: "das transitportal. komm.",
  ghostNotYet: "noch nicht.",
  ghostThanks: "danke, dass du gekommen bist.",
  chatJoined: "{ghost} hat das Spiel betreten",
  chatLeft: "{ghost} hat das Spiel verlassen",
  stayTitle: "Du bist geblieben.",
  staySubtitle: "Jemand wird ihn drücken.",
  hintCamp: "Hier hat jemand gelagert. Öffne die Truhe.",
  hintDig: "Grab nie senkrecht nach unten.",
  hintLectern: "Auf dem Lesepult steht etwas geschrieben.",
  hintJump: "Spring ins Portal.",
  hintMeet: "Jemand wartet auf dich.",
  objChest: "Durchsuche die Truhe",
  objSword: "Stelle ein Schwert her",
  objEyes: "Stelle Enderaugen her",
  objThrow: "Wirf ein Enderauge",
  objDig: "Grab nach unten",
  objFrame: "Vervollständige den Portalrahmen",
  objJump: "Spring ins Portal",
  objDiary: "Lies das Tagebuch auf dem Lesepult",
  advStrike: "Zu den Waffen!",
  advGetaway: "Im Transit",
  subChest: "Truhe öffnet sich",
  subPage: "Seite wird umgeblättert",
  subBreak: "Block zerstört",
  subThrow: "Enderauge geworfen",
  subShatter: "Enderauge zerbricht",
  subWhisper: "Etwas flüstert",
  controlsTitle: "Steuerung",
  paused: "Spiel angehalten",
  play: "Spielen",
  resume: "Zurück zum Spiel",
  leave: "Zurück zum Panel",
  ctrlMove: "WASD — bewegen",
  ctrlJump: "Leertaste — springen (in der Luft mit Elytren: gleiten)",
  ctrlSneak: "Shift — schleichen",
  ctrlSprint: "Ctrl — sprinten",
  ctrlAttack: "Linksklick — schlagen / abbauen",
  ctrlUse: "Rechtsklick — benutzen (halten: Bogen spannen, essen)",
  ctrlHotbar: "1-9 / Mausrad — Schnellzugriffsleiste",
  ctrlInventory: "E — Inventar",
  ctrlPause: "Esc — Pause",
  ctrlTouch: "Linker Daumen: bewegen. Rechts ziehen: umsehen. Tasten: schlagen, benutzen, springen, schleichen, sprinten, Inventar und Pause.",
  touchAttack: "Schlagen",
  touchUse: "Benutzen",
  touchJump: "Springen",
  touchPause: "Pause",
  touchInventory: "Inventar",
  touchSneak: "Schleichen",
  touchSprint: "Sprinten",
  chestBackups: "Truhe: Schatz",
  inventoryHelp: "Linksklick: Stapel nehmen oder ablegen. Rechtsklick: die Hälfte nehmen oder eins ablegen. Umschalt + Klick: auf die andere Seite schicken. Einen gehaltenen Stapel ziehen, um ihn zu verteilen.",
  librarian: "Bibliothekar",
  librarianHmm: "hmm. (der Bibliothekar sieht dich an, als wüsste er etwas)",
  soldOut: "Verkauft",
  mapLegend: "■ Lager · ▲ Dorf · ◆ Portalruine · ? Höhle",
  mapNoSignal: "Die Karte dreht sich ziellos. Sie funktioniert nur in der Oberwelt.",
  deathTitle: "Du bist gestorben!",
  deathScore: "Punktestand:",
  respawn: "Wiederbeleben",
  noise: "Lärm",
  lastSeen: "{ghost} zuletzt online: vor {days} Tagen.",
  lastSeenToday: "{ghost} zuletzt online: heute.",
  villager: "Dorfbewohner",
  nitwit: "Nichtsnutz",
  craftingTable: "Werkbank",
  lectern: "Lesepult",
  portalGap: "Ein fehlender Obsidianblock",
  portalFrame: "Portalruine",
  bed: "Bett",
  button: "Steinknopf",
  frame: "Endportalrahmen",
  gateway: "Endtransitportal",
  itemFrame: "Rahmen",
  commandBlock: "Befehlsblock",
  itemRod: "Lohenrute",
  itemArrow: "Pfeil",
  itemEmerald: "Smaragd",
  itemMap: "Karte",
  itemRegister: "Admin-Register",
  itemFlint: "Feuerzeug",
  itemObsidian: "Obsidian",
  itemElytra: "Elytren",
  itemGold: "Goldklumpen",
  itemDirt: "Erde",
  hintSword: "Stelle an der Werkbank ein Schwert her.",
  hintObsidian: "Nimm Obsidian in die Hand, um die Lücke zu füllen.",
  hintFlint: "Entzünde es mit dem Feuerzeug.",
  hintNotYet: "Noch nicht. Dir fehlen noch Lohenruten aus dem Nether.",
  hintEyeKnown: "Das Auge hat dir den Weg schon gezeigt.",
  hintEyes: "Zurück zur Werkbank: Ruten zu Staub, Staub zu Augen.",
  hintThrowEye: "Benutze ein Enderauge (Rechtsklick).",
  hintCrystalsBow: "Schieß mit dem Bogen auf die Kristalle: Rechtsklick halten, dann loslassen.",
  hintNether: "Der Nether. Ganz schön heiß hier.",
  hintFortress: "Die Festung liegt hinter der Lava. Lohen bewachen sie.",
  hintRodsDone: "Drei Ruten. Zurück durchs Portal.",
  hintQuiet: "Schleich (Shift). Hier unten hört etwas zu.",
  hintGatewayPearl: "Wirf eine Enderperle ins Transitportal.",
  hintNoPearl: "Keine Perlen mehr. Endermen lassen welche fallen.",
  hintElytra: "Spring ab und drück in der Luft noch mal Springen, um zu gleiten.",
  hintEndCity: "Eine Endsiedlung. Steig die Turmtreppe hoch: Der Admin hat die Elytren auf dem Schiff gelassen.",
  hintFramesUse: "Setze die Enderaugen in die leeren Rahmen ein.",
  hintFollowEye: "Das Auge weiß, wo das Portal ist. Folge ihm.",
  objRuined: "Entzünde die Portalruine",
  objMap: "Hol dir die Karte des Bibliothekars",
  objCave: "Was ist in der Höhle?",
  objQuiet: "Mach keinen Lärm",
  objButton: "Drück den Knopf",
  objRods: "Besorge Lohenruten",
  objReturn: "Geh zurück durchs Portal",
  objGhast: "Schlag die Feuerkugel des Ghasts zurück",
  objGatewayPearl: "Oder deine Perle ins Transitportal werfen?",
  objElytra: "Finde die Elytren",
  objIslet: "Gleite zum Inselchen",
  ghostPortal: "ich hätte es fast fertig gehabt. zwei blöcke fehlten.",
  ghostBack: "jetzt die augen. du weißt, wo die werkbank steht.",
  ghostBlaze: "lohen vergeben nicht. ich auch nicht, wenn jemand nach OP gefragt hat.",
  ghostKeepInventory: "keepInventory ist an. gern geschehen.",
  ghostShulker: "shulker lassen dich gratis fliegen. die landung kostet extra.",
  ghostBed: "ich hab dich gewarnt.",
  ghostAncient: "du hast die stadt also auch gefunden.",
  voiceWill: "wird er ihn drücken?",
  voiceAlways: "das tun sie immer.",
  voiceAgain: "schon wieder.",
  voiceLearning: "lass ihn. er lernt noch.",
  voiceNo: "nein.",
  voiceDone: "…tja, jetzt hast du es getan.",
  voiceAlmost: "fast geschafft.",
  voiceChoose: "jetzt kommt das schwerste: wählen.",
  creeperDenied: "warum gehen alle immer weg?",
  villagerHmm: "Dorfbewohner: hmm.",
  nitwitHmm: "Nichtsnutz: hmm?",
  farmerHmm: "Bauer: hmm. (er will 22 Stöcke für einen Smaragd. ihr wisst beide, dass das Abzocke ist)",
  signIncidents: "Tage, seit ein\nCreeper mein Haus\ngesprengt hat:\n0",
  signRestart: "Hier entsteht\nmeine Burg.",
  signBackups: "SCHATZ.\nNICHT ANFASSEN.\n—Bfuuny",
  signBorder: "Ende der Karte.\nBudget aufgebraucht.\n—{ghost}",
  signToast: "Toast\n(wir vermissen dich)",
  signCave: "Nein.\n(im Ernst)",
  signQuiet: "Ruhe, bitte.\nDer Nachbar von unten\nhat keine Augen,\nhört aber ALLES.",
  signCasi: "fast.\n—{ghost}",
  signBed: "Hier nicht schlafen.\n(auf die harte Tour gelernt)",
  signDiamond: "Hier habe ich\nden Diamanten verloren.\nSuch ihn nicht.\nHab ich schon.",
  signUptime: "Bin in 5 Minuten\nzurück.\n—{ghost}\n(vor {days} Tagen)",
  diary5: "Ich bin in die Stadt da unten hinabgestiegen. Ihr Rahmen ist genau wie dieser, nur größer.\nJemand hat ihn absichtlich abgeschaltet.",
  register1: "Admin-Register\n\n~~Bfuuny~~ hat den Knopf gedrückt. Zweimal.\n~~BlasterDaster~~ hat den Knopf gedrückt.\n~~Ketbome~~ hat den Knopf gedrückt.",
  registerLoop: "~~{ghost}~~ hat den Knopf gedrückt.",
  register2: "Jeder durchgestrichene Name ist ein Admin, der den Knopf gedrückt hat und nie zurückkam.\nWer streicht sie durch? Die Dorfbewohner.\nhmm.",
  bookAdmin2011: "Journal",
  bookAdmin2011By: "von BlasterDaster",
  admin2011a: "Wenn du es bis hier unten geschafft hast, gehörst du zu den Neugierigen.\nDer erste Knopf war auf keinem Panel. Er war hier.",
  admin2011b: "Die Portale sind älter als die Server. Wir schalten sie nur ein.\nMach keinen Lärm. Er hört zu.\n— BlasterDaster",
  bookStop: "Befehlsblock",
  stopBook: "Befehl: /stop\n\n(nie ausgeführt)",
  deathLava: "hielt Lava für einen Whirlpool",
  deathVoid: "fiel in die Leere. Fällt immer noch. Lässt grüßen.",
  deathFall: "versuchte den Wassereimer-Trick. Ohne Eimer.",
  deathBed: "legte sich im Nether schlafen. Das Bett war dagegen.",
  deathWarden: "nieste in der antiken Stätte. Der Wärter sagte nicht mal Gesundheit.",
  deathEnderman: "sah einem Enderman in die Augen. Der Enderman sah zurück.",
  deathBlaze: "fragte eine Lohe, ob sie heiß ist. War sie.",
  deathDragon: "wurde vom Enderdrachen erschlagen, während er einen Screenshot zum Angeben machte",
  deathBreath: "roch am Drachenatem. Das hat niemand verdient.",
  deathElytra: "knallte mit Vollgas gegen eine Wand. Der Wand geht's gut.",
  deathShulker: "schwebte in den Himmel. Dann nicht mehr.",
  deathSilverfish: "wurde von einem Silberfischchen gefressen. Einem Silberfischchen.",
  deathGhast: "wurde an den Absender zurückgeschickt",
  advDeeper: "Wir müssen noch tiefer",
  advButton: "Was macht dieser Knopf?",
  advRods: "Spiel mit dem Feuer",
  advReturn: "Zurück zum Absender",
  advSky: "Hinterm Horizont geht’s weiter",
  subExplosion: "Explosion",
  subBow: "Bogen schießt",
  subArrow: "Pfeil trifft",
  subEat: "Essen",
  subHurtPlayer: "Spieler nimmt Schaden",
  subVillager: "Dorfbewohner murmelt",
  subSheep: "Schaf mäht",
  subPig: "Schwein grunzt",
  subHiss: "Creeper zischt",
  subFlint: "Feuerzeug zündet",
  subFireball: "Feuerkugel zischt",
  subBlaze: "Lohe atmet",
  subGhast: "Ghast jammert",
  subHeartbeat: "Wärterherz schlägt",
  subRoar: "Wärter brüllt",
  subShriek: "Sculk-Kreischer kreischt",
  subSculk: "Sculk-Sensor klickt",
  subSqueak: "Silberfischchen zischt",
  subZap: "Shulker-Geschoss",
  subLevitate: "Schweben",
  subNetherPortal: "Portal öffnet sich",
  deathCreeper: "wurde von Kevin geknuddelt",
  creeperGranted: "ich wollte doch nur knuddeln.",
  mobSlain: "wurde von {player} erschlagen",
  pigDown: "ist down. Schon wieder.",
  clickToPlay: "Klicke, um weiterzuspielen",
  noWebgl: "Dein Browser kann das Spiel nicht in 3D darstellen (WebGL2 fehlt). Aktiviere die Hardwarebeschleunigung in den Einstellungen, starte ihn neu und versuch es noch einmal. Bis dahin: hier ist das Ende.",
  signBfuunyBed: "Toller Ort\nzum Schlafen.\nVertrau mir.\n—Bfuuny",
  signBfuunyShip: "Die guten Elytren\nsind auf dem\nanderen Schiff.\n—Bfuuny",
  signBfuunyExit: "AUSGANG\n→\n—Bfuuny",
  bfuunyChest: "haha. das ist Erde. alles.",
  bfuunyBed: "haha. ich sagte, vertrau mir.",
  ghostWardenHit: "haust du ihn etwa? den wärter? mutig.",
  ghostWarden: "…ok. das hat noch nie jemand gemacht.",
};

export default de;
