import type { LoreKey } from './en';

const de: Record<LoreKey, string> = {
  endTitle: 'Das Ende',
  endSubtitle: 'Du bist ins Ende gedriftet. Hier gab es doch nichts zu zerstören.',
  return: 'Zurück in die Oberwelt',
  advancement: 'Fortschritt erzielt!',
  itemEgg: 'Drachenei',
  intro: "Ketbomes Testserver #47. Status: fast fertig.",
  endTagline: 'Oder der Anfang?',
  goalReached: 'Ziel erreicht!',
  advEyeSpy: 'Adlerauge',
  advEnterEnd: 'Das Ende?',
  advFreeEnd: 'Befreie das Ende',
  advNextGen: 'Die nächste Generation',
  chatAdvancement: '{player} hat den Fortschritt erzielt',
  chatGoal: '{player} hat das Ziel erreicht',
  player: 'Spieler',
  bossName: 'Enderdrache',
  objectives: 'Ziele',
  objCrystals: 'Zerstöre die Endkristalle',
  objDragon: 'Besiege den Enderdrachen',
  objEgg: 'Fange das Drachenei',
  objPortal: 'Spring ins Ausgangsportal',
  hintHealing: 'Die Kristalle heilen ihn. Zerstöre sie zuerst.',
  hintPerch: 'Der Drache schwebt über dem Portal. Schlag jetzt zu!',
  hintTakeoff: 'Der Drache hebt ab. In der Luft treffen ihn Pfeile.',
  hintCharge: 'Der Drache stürzt auf dich zu. Weich zur Seite aus!',
  hintArrowsBounce: 'Solange er sitzt, prallen Pfeile ab. Nimm das Schwert.',
  hintEnraged: 'Der Drache ist wütend!',
  hintEnderman: 'Schau ihnen nicht in die Augen.',
  hintEgg: 'Das Ei hat sich wegteleportiert. Versuch es noch mal.',
  hintPortal: 'Das Ausgangsportal ist offen.',
  subEye: 'Enderauge eingesetzt',
  subPortal: 'Endportal öffnet sich',
  subTravel: 'Portal rauscht',
  subLava: 'Lava blubbert',
  subGrowl: 'Enderdrache knurrt',
  subHurt: 'Enderdrache verletzt',
  subDeath: 'Enderdrache stirbt',
  subCrystal: 'Endkristall explodiert',
  subEnderman: 'Enderman teleportiert sich',
  subEgg: 'Drachenei teleportiert sich',
  subXp: 'Erfahrungskugel klingt',
  subGateway: 'Endtransitportal entsteht',
  mute: 'Ton aus',
  unmute: 'Ton an',
  skip: 'Überspringen',
  poem: "Ich sehe den Spieler, den du meinst.\n{player}?\nJa. Sei vorsichtig. Er hat jetzt eine höhere Stufe erreicht. Er kann unsere Gedanken lesen.\nDas spielt keine Rolle. Er glaubt, wir seien Teil des Spiels.\nIch mag diesen Spieler. Er hat gut gespielt. Er hat nicht aufgegeben.\nEr kam auf einen Server, der nie fertig wurde. Er hat ihn trotzdem gespielt.\nEr baut Welten, in denen seine Freunde spielen. Er hält sie offen, während sie schlafen.\nEr repariert, was kaputtgeht. Er bewahrt, was zählt. Er hat nie um Dank gebeten.\nVor ihm waren drei. Einer baute. Einer gewann. Einer starb immer wieder und lachte jedes Mal.\nSie sind noch hier. Sie haben auf ihn gewartet.\nWovon hat dieser Spieler geträumt?\nDieser Spieler träumte von Sonnenlicht und Bäumen. Von Feuer und Wasser. Er träumte, er erschaffe. Und er träumte, er zerstöre. Er träumte, er jage und werde gejagt. Er träumte von Zuflucht.\nUnd das Universum sagte: Du bist nicht allein\nUnd das Universum sagte: Du bist nicht getrennt von allem anderen\nUnd das Universum sagte: Du bist das Universum, das sich selbst schmeckt, mit sich selbst spricht, seinen eigenen Code liest\nUnd das Universum sagte: Ich liebe dich, weil du Liebe bist.\nUnd das Spiel war vorbei, und der Spieler erwachte aus dem Traum. Und der Spieler begann einen neuen Traum. Und der Spieler träumte wieder, träumte besser. Und der Spieler war das Universum. Und der Spieler war Liebe.\nDu bist der Spieler.\nWach auf.",
  poemCredit: "Endgedicht von Julian Gough (CC0), gekürzt. Fünf Zeilen wurden für Minepanel geschrieben.",
  poemHint: 'Leertaste oder gedrückt halten zum Beschleunigen',
  itemNote: "Notiz",
  itemDiamond: "Diamant",
  itemStick: "Stock",
  itemPearl: "Enderperle",
  itemBlaze: "Lohenstaub",
  itemBow: "Bogen",
  itemApple: "Goldener Apfel",
  itemSword: "Diamantschwert",
  itemEye: "Enderauge",
  chest: "Truhe",
  crafting: "Handwerk",
  inventory: "Inventar",
  takeAll: "Alles nehmen",
  recipeBook: "Rezeptbuch",
  craftHelp: "Lege Gegenstände ins Raster und nimm das Ergebnis. Umschalt + Klick auf das Ergebnis stellt alles her, was das Raster hergibt. Das Rezeptbuch legt einen Satz aus (Umschalt: so viele wie möglich).",
  emptySlot: "Leerer Platz",
  close: "Schließen",
  page: "Seite {n} von {total}",
  prevPage: "Vorherige Seite",
  nextPage: "Nächste Seite",
  diaryTitle: "Tagebuch",
  diaryBy: "von {ghost}",
  sign: "Schild",
  note: "Server #47. Diesen mache ich fertig, versprochen.\nIch habe dir dagelassen, was ich hatte, in der Kiste. Die Werkbank steht noch.\nTrau Bfuunys Kisten nicht. Tritt nicht gegen BlasterDaster an. Du verlierst.\nBehalte eine Perle. Du wirst verstehen.\n— {ghost}",
  diary1: "Server #47, Tag 1. Das Lager steht. Als Nächstes die Burg.\n(die Burg kam nie)",
  diary2: "Tag 3. Das Portal hatte schon drei Augen.\nBlasterDaster war natürlich zuerst da. Er hat ein Schild hinterlassen: \"zu langsam\".",
  diary3: "Endermen klauen mir ständig Blöcke. Ich glaube, die bauen auch etwas.\nWahrscheinlich besser als ich.",
  diary4: "Ich gehe ins End und baue den endgültigen Server.\nBesiege den Drachen, dann nimm das Gateway. Wir warten.\n— {ghost}",
  tomb: "Hier liegt Bfuuny.\nSchon wieder.\n(Tod #312: er hat dem Drachen gewinkt)",
  ghostArrival: "du hast es geschafft.",
  ghostCrystal: "ich habe viel länger gebraucht.",
  ghostPerch: "jetzt. während er ruht.",
  ghostVictory: "geh noch nicht.",
  ghostGateway: "das gateway. da warten wir alle. bring eine perle mit.",
  ghostNotYet: "der enderman bewacht bfuunys grab. irgendwer muss es ja tun.",
  ghostThanks: "danke, dass du Minepanel benutzt. wirklich. wir sind zu dritt und haben viel kaffee.",
  chatJoined: "{ghost} hat das Spiel betreten",
  chatLeft: "{ghost} hat das Spiel verlassen",
  stayTitle: "GG",
  staySubtitle: "Bfuuny ist schon wieder gestorben.",
  hintCamp: "Hier hat jemand gelagert. Öffne die Truhe.",
  hintDig: "Grab nie senkrecht nach unten.",
  hintLectern: "Auf dem Lesepult steht etwas geschrieben.",
  hintJump: "Spring ins Portal.",
  hintMeet: "Gleite hinunter zur Insel. Sie warten auf dich.",
  objChest: "Durchsuche die Truhe",
  objSword: "Stelle ein Schwert her",
  objEyes: "Stelle Enderaugen her",
  objThrow: "Wirf ein Enderauge",
  objDig: "Grab nach unten",
  objFrame: "Vervollständige den Portalrahmen",
  objJump: "Spring ins Portal",
  objDiary: "Lies das Tagebuch auf dem Lesepult",
  advStrike: "Zu den Waffen!",
  advGetaway: "Im Transit",
  subChest: "Truhe öffnet sich",
  subPage: "Seite wird umgeblättert",
  subBreak: "Block zerstört",
  subThrow: "Enderauge geworfen",
  subShatter: "Enderauge zerbricht",
  subWhisper: "Etwas flüstert",
  controlsTitle: "Steuerung",
  paused: "Spiel angehalten",
  play: "Spielen",
  resume: "Zurück zum Spiel",
  leave: "Zurück zum Panel",
  ctrlMove: "WASD — bewegen",
  ctrlJump: "Leertaste — springen (in der Luft mit Elytren: gleiten)",
  ctrlSneak: "Shift — schleichen",
  ctrlSprint: "Ctrl — sprinten",
  ctrlAttack: "Linksklick — schlagen / abbauen",
  ctrlUse: "Rechtsklick — benutzen, Block setzen (halten: Bogen spannen, essen)",
  ctrlHotbar: "1-9 / Mausrad — Schnellzugriffsleiste",
  ctrlInventory: "E — Inventar",
  ctrlPause: "Esc — Pause",
  ctrlTouch: "Linker Daumen: bewegen. Rechts ziehen: umsehen. Tasten: schlagen, benutzen, springen, schleichen, sprinten, Inventar und Pause.",
  touchAttack: "Schlagen",
  touchUse: "Benutzen",
  touchJump: "Springen",
  touchPause: "Pause",
  touchInventory: "Inventar",
  touchSneak: "Schleichen",
  touchSprint: "Sprinten",
  chestBackups: "Truhe: Schatz",
  inventoryHelp: "Linksklick: Stapel nehmen oder ablegen. Rechtsklick: die Hälfte nehmen oder eins ablegen. Umschalt + Klick: auf die andere Seite schicken. Einen gehaltenen Stapel ziehen, um ihn zu verteilen.",
  librarian: "Bibliothekar",
  librarianHmm: "hmm. (der Bibliothekar sieht dich an, als wüsste er etwas)",
  soldOut: "Verkauft",
  mapLegend: "■ Lager · ▲ Dorf · ◆ Portalruine · ? Höhle",
  mapNoSignal: "Die Karte dreht sich ziellos. Sie funktioniert nur in der Oberwelt.",
  deathTitle: "Du bist gestorben!",
  deathScore: "Punktestand:",
  respawn: "Wiederbeleben",
  noise: "Lärm",
  lastSeen: "{ghost} zuletzt online: vor {days} Tagen.",
  lastSeenToday: "{ghost} zuletzt online: heute.",
  villager: "Dorfbewohner",
  nitwit: "Nichtsnutz",
  craftingTable: "Werkbank",
  lectern: "Lesepult",
  portalGap: "Ein fehlender Obsidianblock",
  portalFrame: "Portalruine",
  bed: "Bett",
  button: "Steinknopf",
  frame: "Endportalrahmen",
  gateway: "Endtransitportal",
  itemFrame: "Rahmen",
  commandBlock: "Befehlsblock",
  itemRod: "Lohenrute",
  itemArrow: "Pfeil",
  itemEmerald: "Smaragd",
  itemMap: "Karte",
  itemRegister: "Bfuunys Todesregister",
  itemFlint: "Feuerzeug",
  itemObsidian: "Obsidian",
  itemElytra: "Elytren",
  itemGold: "Goldbarren",
  itemDirt: "Erde",
  hintSword: "Stelle an der Werkbank ein Schwert her.",
  hintObsidian: "Nimm Obsidian in die Hand, um die Lücke zu füllen.",
  hintFlint: "Entzünde es mit dem Feuerzeug.",
  hintNotYet: "Noch nicht. Dir fehlen noch Lohenruten aus dem Nether.",
  hintEyeKnown: "Das Auge hat dir den Weg schon gezeigt.",
  hintEyes: "Zurück zur Werkbank: Ruten zu Staub, Staub zu Augen.",
  hintThrowEye: "Benutze ein Enderauge (Rechtsklick).",
  hintCrystalsBow: "Schieß mit dem Bogen auf die Kristalle: Rechtsklick halten, dann loslassen.",
  hintNether: "Der Nether. Ganz schön heiß hier.",
  hintFortress: "Die Festung liegt hinter der Lava. Lohen bewachen sie.",
  hintRodsDone: "Drei Ruten. Zurück durchs Portal.",
  hintQuiet: "Schleich (Shift). Hier unten hört etwas zu.",
  hintGatewayPearl: "Wirf eine Enderperle ins Transitportal.",
  hintNoPearl: "Keine Perlen mehr. Endermen lassen welche fallen.",
  hintElytra: "Spring ab und drück in der Luft noch mal Springen, um zu gleiten.",
  hintEndCity: "Eine Endsiedlung. Steig die Turmtreppe hoch: Der Admin hat die Elytren auf dem Schiff gelassen.",
  hintFramesUse: "Setze die Enderaugen in die leeren Rahmen ein.",
  hintFollowEye: "Das Auge weiß, wo das Portal ist. Folge ihm.",
  objRuined: "Entzünde die Portalruine",
  objMap: "Hol dir die Karte des Bibliothekars",
  objCave: "Was ist in der Höhle?",
  objQuiet: "Mach keinen Lärm",
  objButton: "Drück den Knopf",
  objRods: "Besorge Lohenruten",
  objReturn: "Geh zurück durchs Portal",
  objGhast: "Schlag die Feuerkugel des Ghasts zurück",
  objGatewayPearl: "Oder deine Perle ins Transitportal werfen?",
  objElytra: "Finde die Elytren",
  objIslet: "Gleite zum Inselchen",
  ghostPortal: "ich hätte es fast fertig gehabt. zwei blöcke fehlten.",
  ghostBack: "jetzt die augen. du weißt, wo die werkbank steht.",
  ghostBlaze: "lohen vergeben nicht. ich auch nicht, wenn jemand admin werden wollte.",
  ghostKeepInventory: "sterben kostet dich hier nicht deine sachen. gern geschehen.",
  ghostShulker: "shulker lassen dich gratis fliegen. die landung kostet extra.",
  ghostBed: "ich hab dich gewarnt.",
  ghostAncient: "du hast die stadt also auch gefunden.",
  creeperDenied: "warum gehen alle immer weg?",
  villagerHmm: "Dorfbewohner: hmm.",
  nitwitHmm: "Nichtsnutz: hmm?",
  farmerHmm: "Bauer: hmm. (bietet dir eine Karotte für einen Smaragd. sagt, das ist ein Freundschaftspreis)",
  signIncidents: "Tage, seit ein\nCreeper mein Haus\ngesprengt hat:\n0",
  signRestart: "Hier entsteht\nmeine Burg.",
  signBackups: "SCHATZ.\nNICHT ANFASSEN.\n—Bfuuny",
  signBorder: "Ende der Karte.\nBudget aufgebraucht.\n—{ghost}",
  signToast: "Server-Haustier:\ndas Kaninchen.\nNützlicher als Bfuuny.",
  signCave: "Nein.\n(im Ernst)",
  signQuiet: "Ruhe, bitte.\nDer Nachbar von unten\nhat keine Augen,\nhört aber ALLES.",
  signCasi: "fast.\n—{ghost}",
  signBed: "Hier nicht schlafen.\n(auf die harte Tour gelernt)",
  signDiamond: "Hier habe ich\nden Diamanten verloren.\nSuch ihn nicht.\nHab ich schon.",
  signUptime: "Bin in 5 Minuten\nzurück.\n—{ghost}\n(vor {days} Tagen)",
  diary5: "Ich war in der antiken Stadt. BlasterDaster sagt, er hat den Warden mit einem Holzschwert erledigt.\nIch glaube ihm nicht. Ein bisschen schon.",
  register1: "Bfuunys Todesregister\n\n#1 vom Spawn gefallen.\n#2 vom Spawn gefallen. Schon wieder.\n#58 im Nether geschlafen. \"ist gemütlich\".\n#128 Kevin umarmt.\n#311 \"ich schau nur, wie heiß die Lava ist\".",
  register2: "Seiten 3 bis 40: mehr vom Gleichen.\nDie Dorfbewohner führen Buch. Sie scheinen Spaß daran zu haben.\nhmm.",
  bookAdmin2011: "Profi-Guide",
  bookAdmin2011By: "von BlasterDaster",
  admin2011a: "BlasterDasters Profi-Guide, Teil 1:\nSchleichen. Nicht sprinten. Nicht springen. Nicht laut atmen.\nWenn du einen Herzschlag hörst, der nicht deiner ist: Lauf. Nein, warte. Nicht laufen.",
  admin2011b: "Teil 2: Schieß einen Pfeil woandershin. Er geht immer nachsehen.\nZweimal erledigt. Bfuuny ist beim Zuschauen viermal gestorben.\nPS: Drück nicht den Knopf am Rahmen. Diesmal kein Witz.\n— BlasterDaster",
  bookStop: "Befehlsblock",
  stopBook: "Befehl: /give @p diamond 64\n\n(Bfuuny hat gefragt. nein.)",
  deathLava: "hielt Lava für einen Whirlpool",
  deathVoid: "fiel in die Leere. Fällt immer noch. Lässt grüßen.",
  deathFall: "versuchte den Wassereimer-Trick. Ohne Eimer.",
  deathBed: "legte sich im Nether schlafen. Das Bett war dagegen.",
  deathWarden: "nieste in der antiken Stätte. Der Wärter sagte nicht mal Gesundheit.",
  deathEnderman: "sah einem Enderman in die Augen. Der Enderman sah zurück.",
  deathBlaze: "fragte eine Lohe, ob sie heiß ist. War sie.",
  deathDragon: "wurde vom Enderdrachen erschlagen, während er einen Screenshot zum Angeben machte",
  deathBreath: "roch am Drachenatem. Das hat niemand verdient.",
  deathElytra: "knallte mit Vollgas gegen eine Wand. Der Wand geht's gut.",
  deathShulker: "schwebte in den Himmel. Dann nicht mehr.",
  deathSilverfish: "wurde von einem Silberfischchen gefressen. Einem Silberfischchen.",
  deathGhast: "wurde an den Absender zurückgeschickt",
  advDeeper: "Wir müssen noch tiefer",
  advButton: "Was macht dieser Knopf?",
  advRods: "Spiel mit dem Feuer",
  advReturn: "Zurück zum Absender",
  advSky: "Hinterm Horizont geht’s weiter",
  subExplosion: "Explosion",
  subBow: "Bogen schießt",
  subArrow: "Pfeil trifft",
  subEat: "Essen",
  subHurtPlayer: "Spieler nimmt Schaden",
  subVillager: "Dorfbewohner murmelt",
  subSheep: "Schaf mäht",
  subPig: "Schwein grunzt",
  subHiss: "Creeper zischt",
  subFlint: "Feuerzeug zündet",
  subFireball: "Feuerkugel zischt",
  subBlaze: "Lohe atmet",
  subGhast: "Ghast jammert",
  subHeartbeat: "Wärterherz schlägt",
  subRoar: "Wärter brüllt",
  subShriek: "Sculk-Kreischer kreischt",
  subSculk: "Sculk-Sensor klickt",
  subSqueak: "Silberfischchen zischt",
  subZap: "Shulker-Geschoss",
  subLevitate: "Schweben",
  subNetherPortal: "Portal öffnet sich",
  deathCreeper: "wurde von Kevin geknuddelt",
  creeperGranted: "ich wollte doch nur knuddeln.",
  mobSlain: "wurde von {player} erschlagen",
  pigDown: "hat es kommen sehen.",
  clickToPlay: "Klicke, um weiterzuspielen",
  noWebgl: "Dein Browser kann das Spiel nicht in 3D darstellen (WebGL2 fehlt). Aktiviere die Hardwarebeschleunigung in den Einstellungen, starte ihn neu und versuch es noch einmal. Bis dahin: hier ist das Ende.",
  signBfuunyBed: "Toller Ort\nzum Schlafen.\nVertrau mir.\n—Bfuuny",
  signBfuunyShip: "Die guten Elytren\nsind auf dem\nanderen Schiff.\n—Bfuuny",
  signBfuunyExit: "AUSGANG\n→\n—Bfuuny",
  bfuunyChest: "haha. das ist Erde. alles.",
  bfuunyBed: "haha. ich sagte, vertrau mir.",
  ghostWardenHit: "haust du ihn etwa? den wärter? mutig.",
  ghostWarden: "…ok. das hat noch nie jemand gemacht.",
  itemLog: "Eichenstamm",
  itemPlanks: "Eichenholzbretter",
  itemCobble: "Bruchstein",
  itemNetherrack: "Netherrack",
  itemEndStone: "Endstein",
  itemPickaxe: "Diamantspitzhacke",
  itemHelmet: "Goldhelm",
  piglin: "Piglin",
  armor: "Rüstung",
  armorSlot: "Helm",
  hintPiglin: "Halte einen Goldbarren und klicke einen Piglin mit Rechtsklick an, um zu tauschen.",
  hintHelmet: "Setz den Goldhelm auf (Rechtsklick damit). Piglins trauen nur Gold.",
  hintPearlsLeft: "Drei Ruten. Dir fehlen noch Enderperlen: Die Piglins tauschen sie gegen Gold.",
  objPearls: "Tausche Enderperlen bei den Piglins",
  ghostPiglin: "piglins. kein gold auf dem kopf, keine freunde.",
  ghostDarkness: "die lichter sind aus. das ist nie ein gutes zeichen.",
  deathSkeleton: "wurde von einem Skelett erschossen. Es hat keine Augen. Es brauchte keine.",
  deathPiglin: "kam ohne Gold. Die Piglins nahmen es persönlich.",
  subEquip: "Ausrüstung angelegt",
  subPiglin: "Piglin schnaubt",
  subSkeleton: "Skelett klappert",
  bfuunyDirt: "siehst du? ich hab gesagt, es ist ein schatz.",
  introBlaster: "neuer spieler. 20 drauf, dass Kevin ihn zuerst erwischt.",
  introBfuuny: "abgemacht. ich hab gestern 20 an Kevin verloren.",
  respawnBfuuny: "willkommen im club. ich bin der präsident.",
  respawnBlaster: "mehr üben.",
  buttonBfuuny: "äh. wer hat 'The Rake' eingeladen?",
  buttonBlaster: "ich hab gesagt, nicht drücken. wenn du hinter dir etwas atmen hörst, dreh dich NICHT um.",
  victoryKetbome: "gg! das ausgangsportal bringt dich nach hause.",
  victoryBlaster: "oder wirf eine perle ins gateway. da sind wir.",
  endKetbome1: "du hast es geschafft! willkommen auf dem endgültigen server.",
  endKetbome2: "er ist... fast fertig.",
  endBlaster: "gg. gar nicht schlecht.",
  endBfuuny: "passt auf, den sprung schaff ich locker",
  endBlaster2: "jedes. einzelne. mal.",
  endStar: "wenn es dir gefällt: ein stern auf GitHub, ein beitrag oder teilen in sozialen netzwerken hilft mehr, als du denkst.",
  endBfuunyBack: "bin wieder da. was hab ich verpasst?",
  bfuunyDiedKevin: "wurde von Kevin gesprengt. Er wollte eine Umarmung.",
  bfuunyDiedPiglin: "wurde von einem Piglin erschlagen. Er hat den Helm vergessen.",
  bfuunyDiedWarden: "wurde von einem Schallkreischen ausgelöscht",
  bfuunyDiedVoid: "fiel aus der Welt. Schon wieder.",
  signBlasterSlow: "zu langsam.\n—BlasterDaster",
  signBlasterRods: "Lohenruten: 3/3\nin 40 Sekunden.\n—BlasterDaster",
  signBfuunyGrave: "R.I.P. Bfuuny\n(ihm geht's gut)\n(er kommt wieder)",
  signServer48: "Server #48\nDemnächst.\n—Ketbome",
  deathRake: "traf The Rake. Es wollte nicht reden.",
  deathZombie: "wollte einen Zombie umarmen. Es war nicht Kevin.",
  deathZombieVillager: "wollte mit einem Zombiedorfbewohner handeln. Er wollte Gehirne.",
  deathDrowned: "ging schwimmen. Die Ertrunkenen waren keine Rettungsschwimmer.",
  deathSpider: "hat nicht an die Decke geschaut.",
  deathWitch: "hat einen Trank von einer Fremden angenommen.",
  deathSlime: "hat einen winzigen Schleim unterschätzt. Dann waren es vier.",
  deathPhantom: "hat nicht geschlafen. Ketbome auch nicht, aber der ist das gewohnt.",
  deathZombifiedPiglin: "hat einen zombifizierten Piglin geschlagen. Nur einen.",
  deathHoglin: "hat einen Hoglin Schweinchen genannt.",
  deathMagmaCube: "wollte einen Magmawürfel austreten.",
  deathWitherSkeleton: "wollte einen Witherskelettschädel. Das Skelett wollte ihn behalten.",
  deathEndermite: "hat so viele Perlen geworfen, dass aus einer etwas herauskroch.",
  subRake: "Etwas kreischt",
  rakeBfuuny: "hat das noch jemand gesehen???",
  rakeBlaster: "hab ich doch gesagt. der knopf.",
  thanksTitle: "Danke fürs Spielen",
  thanksBody: "Minepanel wird von ein paar Leuten in ihrer Freizeit gemacht, und es zu benutzen hilft schon.\nWenn es dir gefällt, helfen ein Stern auf GitHub, ein Beitrag oder Teilen in sozialen Netzwerken, damit es mehr Leute erreicht.",
  thanksStar: "Stern auf GitHub",
  thanksClose: "Zurück zum Panel",
  subBreath: "Etwas atmet hinter dir",
  hintSleepDay: "Du kannst nur nachts oder während eines Gewitters schlafen",
  hintSleepMonsters: "Du kannst jetzt nicht schlafen, es sind Monster in der Nähe",
  ghostSleep: "du hast mehr geschlafen als ich auf dem ganzen Server #47.",
  advTreasure: "Wahrer Schatz",
  advPacifist: "Pazifist",
  advKevin: "Kevins Freund",
  advNotAJoke: "Das war kein Witz",
  advRake: "Ich atme noch",
  advNoElytra: "Wer braucht schon Flügel",
  lineTreasure: "…du hast sie behalten? die behält nie jemand.",
  linePacifist: "kein einziger enderman. respekt.",
  lineKevin: "umarmung?",
  lineNotAJoke: "zweimal. ZWEIMAL.",
  lineRake: "du hast überlebt? ich nicht.",
  lineNoElytra: "ok. nicht mal ich hab das geschafft.",
  thanksServer48: "Server #48 besuchen",
  signServer48Day1: "Server #48. Tag 1.\nAngefangen.\n—Ketbome",
  signServer48Blaster: "Server #48 (meiner).\nFertig.\n—BlasterDaster",
  s48Ketbome: "angefangen.",
  s48Blaster: "meiner ist schon fertig.",
  s48Bfuuny: "wo ist der rand der karte? ah, da.",
  s48Ketbome2: "morgen baue ich ein geländer.",
  guide3a: "BlasterDasters Profi-Guide, Teil 3: der Nether.\nGhasts weinen, weil ich gewinne.\nPiglins geben mir Rabatt. Muss das Charisma sein.",
  guide3b: "Lava ist kein Whirlpool.\nBfuuny hat diesen Teil nicht gelesen.\nBfuuny liest nicht.\n— BlasterDaster",
  register3: "Seite 41: Gäste.\n{player}: {deaths}.\nBfuuny sagt, deine zählen nicht.\nSie zählen.",
  rabbitName: "Flocke",
  signVillage: "Dorf Minepanel.\nSeine Bewohner haben\ndas Panel mitgebaut.\nDanke!",
  signTempleBfuuny: "Nicht in die\nMitte treten.\n(ich bin reingetreten)\n—Bfuuny",
  signRuinDesert: "Server #12:\ndie Pyramide.\nEine Ecke steht.\n—Ketbome",
  signRuinTaiga: "Server #23:\ndas Iglu. Sollte aus\nSchnee sein. Ist aus Erde.\n—Ketbome",
  signRuinSwamp: "Server #31:\nSchleimfarm.\nSchleime bisher: 0.\n—Ketbome",
  signRuinCoast: "Server #40:\nder Hafen.\nDas Schild ist fertig.\n—Ketbome",
  signWreckNote: "Vergrabener Schatz:\n3 Schritte nördlich\nvom Strandkaktus.\n—Bfuuny",
  ghostTreasure: "mein diamant! ich hab ihn im nether verloren. frag nicht, wie er hierher kam.",
  advRuins: "Unvollendete Werke",
  ghostRuins: "du hast alle gesehen. jetzt weißt du, warum ich nie etwas fertig mache.",
  deathTnt: "ist in die Mitte getreten. Bfuuny hat gewarnt.",
  deathCactus: "hat sich an einen Kaktus gelehnt. Zu lange.",
  pigName: "Speck",
};

export default de;
