export const en = {
  endTitle: 'The End',
  endSubtitle: 'You drifted into the End. There was nothing to destroy here after all.',
  return: 'Return to the Overworld',
  advancement: 'Advancement Made!',
  itemEgg: 'Dragon Egg',
  intro: 'You were told not to press it.',
  endTagline: 'Or the beginning?',
  goalReached: 'Goal Reached!',
  advEyeSpy: 'Eye Spy',
  advEnterEnd: 'The End?',
  advFreeEnd: 'Free the End',
  advNextGen: 'The Next Generation',
  chatAdvancement: '{player} has made the advancement',
  chatGoal: '{player} has reached the goal',
  player: 'Player',
  bossName: 'Ender Dragon',
  objectives: 'Objectives',
  objCrystals: 'Destroy the End Crystals',
  objDragon: 'Slay the Ender Dragon',
  objEgg: 'Catch the Dragon Egg',
  objPortal: 'Jump into the exit portal',
  hintHealing: 'The crystals are healing it. Break them first.',
  hintPerch: 'The dragon is over the portal. Strike now!',
  hintEnderman: "Don't look them in the eyes.",
  hintEgg: 'The egg teleported away. Try again.',
  hintPortal: 'The exit portal is open.',
  subEye: 'Eye of Ender attaches',
  subPortal: 'End Portal opens',
  subTravel: 'Portal whooshes',
  subLava: 'Lava pops',
  subGrowl: 'Ender Dragon growls',
  subHurt: 'Ender Dragon hurts',
  subDeath: 'Ender Dragon dies',
  subCrystal: 'End Crystal explodes',
  subEnderman: 'Enderman teleports',
  subEgg: 'Dragon Egg teleports',
  subXp: 'Experience Orb tinkles',
  subGateway: 'End Gateway spawns',
  mute: 'Mute sound',
  unmute: 'Unmute sound',
  skip: 'Skip',
  poem: "I see the player you mean.\n{player}?\nYes. Take care. It has reached a higher level now. It can read our thoughts.\nThat doesn't matter. It thinks we are part of the game.\nI like this player. It played well. It did not give up.\nIt was told not to press the button.\nIt pressed it anyway. They always do. That is how they find us.\nIt keeps worlds running for others. It reads their logs while they sleep.\nIt restarts what breaks. It keeps what matters. It never asked to be thanked.\nThere was another before. It played well too. It stayed.\nThis one will wake up.\nWhat did this player dream?\nThis player dreamed of sunlight and trees. Of fire and water. It dreamed it created. And it dreamed it destroyed. It dreamed it hunted, and was hunted. It dreamed of shelter.\nAnd the universe said you are not alone\nAnd the universe said you are not separate from every other thing\nAnd the universe said you are the universe tasting itself, talking to itself, reading its own code\nAnd the universe said I love you because you are love.\nAnd the game was over and the player woke up from the dream. And the player began a new dream. And the player dreamed again, dreamed better. And the player was the universe. And the player was love.\nYou are the player.\nWake up.",
  poemCredit: "End Poem by Julian Gough (CC0), abridged. Six lines were written for Minepanel.",
  poemHint: 'Hold Space, or press and hold, to speed up',
  itemNote: "Note",
  itemDiamond: "Diamond",
  itemStick: "Stick",
  itemPearl: "Ender Pearl",
  itemBlaze: "Blaze Powder",
  itemBow: "Bow",
  itemApple: "Golden Apple",
  itemSword: "Diamond Sword",
  itemEye: "Eye of Ender",
  chest: "Chest",
  crafting: "Crafting",
  inventory: "Inventory",
  takeAll: "Take all",
  recipeBook: "Recipe book",
  craftHelp: "Put items on the grid and take the result. Shift + click the result to craft everything the grid holds. The recipe book lays out a set (Shift: as many as you can).",
  emptySlot: "Empty slot",
  close: "Close",
  page: "Page {n} of {total}",
  prevPage: "Previous page",
  nextPage: "Next page",
  diaryTitle: "Diary",
  diaryBy: "by {ghost}",
  sign: "Sign",
  note: "For the next one.\nI knew you would press it. We all do.\nI left you what I had left. The table is still there.\nKeep one pearl. You'll understand.\n— {ghost}",
  diary1: "I kept this server running for years. I restarted what broke. Nobody ever knew my name.\nTonight I pressed the button.",
  diary2: "The portal already had three eyes in it.\nI was not the first. Someone was here before me, and before them, someone else.",
  diary3: "They say endermen carry blocks because they miss something.\nThat they cannot stand being looked at because it reminds them who they were.",
  diary4: "I am going down.\nIf anyone reads this: kill the dragon. Then choose.\n— {ghost}",
  tomb: "Here stayed\n{ghost}.\nIt was not the dragon.",
  ghostArrival: "you made it.",
  ghostCrystal: "it took me much longer.",
  ghostPerch: "now. while it rests.",
  ghostVictory: "don't leave yet.",
  ghostGateway: "the gateway. come.",
  ghostNotYet: "not yet.",
  ghostThanks: "thank you for coming.",
  chatJoined: "{ghost} joined the game",
  chatLeft: "{ghost} left the game",
  stayTitle: "You stayed.",
  staySubtitle: "Someone will press it.",
  hintCamp: "Someone camped here. Open the chest.",
  hintDig: "Never dig straight down.",
  hintLectern: "Something is written on the lectern.",
  hintJump: "Jump into the portal.",
  hintMeet: "Someone is waiting for you.",
  objChest: "Check the chest",
  objSword: "Craft a sword",
  objEyes: "Craft Eyes of Ender",
  objThrow: "Throw an Eye of Ender",
  objDig: "Dig down",
  objFrame: "Complete the portal frame",
  objJump: "Jump into the portal",
  objDiary: "Read the diary on the lectern",
  advStrike: "Time to Strike!",
  advGetaway: "Remote Getaway",
  subChest: "Chest opens",
  subPage: "Page turns",
  subBreak: "Block broken",
  subThrow: "Eye of Ender shoots",
  subShatter: "Eye of Ender breaks",
  subWhisper: "Something whispers",
  controlsTitle: "Controls",
  paused: "Game paused",
  play: "Play",
  resume: "Back to game",
  leave: "Leave to the panel",
  ctrlMove: "WASD — move",
  ctrlJump: "Space — jump (in the air with elytra: glide)",
  ctrlSneak: "Shift — sneak",
  ctrlSprint: "Ctrl — sprint",
  ctrlAttack: "Left click — hit / mine",
  ctrlUse: "Right click — use (hold: draw the bow, eat)",
  ctrlHotbar: "1-9 / wheel — hotbar",
  ctrlInventory: "E — inventory",
  ctrlPause: "Esc — pause",
  ctrlTouch: "Left thumb: move. Drag on the right: look. Buttons: hit, use, jump, sneak, sprint, inventory and pause.",
  touchAttack: "Hit",
  touchUse: "Use",
  touchJump: "Jump",
  touchPause: "Pause",
  touchInventory: "Inventory",
  touchSneak: "Sneak",
  touchSprint: "Sprint",
  chestBackups: "Chest: treasure",
  inventoryHelp: "Left click: take or drop a stack. Right click: take half or drop one. Shift + click: send it across. Drag a held stack to share it out.",
  librarian: "Librarian",
  librarianHmm: "hmm. (the librarian looks at you like they know something)",
  soldOut: "Sold",
  mapLegend: "■ camp · ▲ village · ◆ ruined portal · ? cave",
  mapNoSignal: "The map spins aimlessly. It only works in the Overworld.",
  deathTitle: "You Died!",
  deathScore: "Score:",
  respawn: "Respawn",
  noise: "Noise",
  lastSeen: "{ghost} was last seen {days} days ago.",
  lastSeenToday: "{ghost} was last seen today.",
  villager: "Villager",
  nitwit: "Nitwit",
  craftingTable: "Crafting Table",
  lectern: "Lectern",
  portalGap: "A missing obsidian block",
  portalFrame: "Ruined portal",
  bed: "Bed",
  button: "Stone Button",
  frame: "End Portal Frame",
  gateway: "End Gateway",
  itemFrame: "Item Frame",
  commandBlock: "Command Block",
  itemRod: "Blaze Rod",
  itemArrow: "Arrow",
  itemEmerald: "Emerald",
  itemMap: "Map",
  itemRegister: "Admin Register",
  itemFlint: "Flint and Steel",
  itemObsidian: "Obsidian",
  itemElytra: "Elytra",
  itemGold: "Gold Nugget",
  itemDirt: "Dirt",
  hintSword: "Craft a sword at the crafting table.",
  hintObsidian: "Hold obsidian to fill the gap.",
  hintFlint: "Light it with flint and steel.",
  hintNotYet: "Not yet. You still need blaze rods from the Nether.",
  hintEyeKnown: "The eye already showed you the way.",
  hintEyes: "Back to the table: rods into powder, powder into eyes.",
  hintThrowEye: "Use an Eye of Ender (right click).",
  hintCrystalsBow: "Shoot the crystals with the bow: hold right click, then let go.",
  hintNether: "The Nether. It's hot in here.",
  hintFortress: "The fortress is across the lava. Blazes guard it.",
  hintRodsDone: "Three rods. Head back through the portal.",
  hintQuiet: "Sneak (Shift). Something down here is listening.",
  hintGatewayPearl: "Throw an ender pearl into the gateway.",
  hintNoPearl: "No pearls left. Endermen drop them.",
  hintElytra: "Jump off and press jump again in mid-air to glide.",
  hintEndCity: "An End City. Climb the tower stairs: the admin left the elytra on the ship.",
  hintFramesUse: "Use the Eyes of Ender on the empty frames.",
  hintFollowEye: "The eye knows where the portal is. Follow it.",
  objRuined: "Light the ruined portal",
  objMap: "Get the librarian's map",
  objCave: "What is in the cave?",
  objQuiet: "Don't make noise",
  objButton: "Press the button",
  objRods: "Get blaze rods",
  objReturn: "Go back through the portal",
  objGhast: "Return the ghast's fireball",
  objGatewayPearl: "Or throw your pearl into the gateway?",
  objElytra: "Find the elytra",
  objIslet: "Glide to the islet",
  ghostPortal: "i almost finished it. two blocks short.",
  ghostBack: "now the eyes. you know where the table is.",
  ghostBlaze: "blazes don't forgive. neither did i, with people asking for OP.",
  ghostKeepInventory: "keepInventory is on. you're welcome.",
  ghostShulker: "shulkers give you a free flight. the landing costs extra.",
  ghostBed: "i did warn you.",
  ghostAncient: "so you found the city too.",
  voiceWill: "will they press it?",
  voiceAlways: "they always do.",
  voiceAgain: "again.",
  voiceLearning: "let them be. they're learning.",
  voiceNo: "no.",
  voiceDone: "…well, now you've done it.",
  voiceAlmost: "almost there.",
  voiceChoose: "now comes the hard part: choosing.",
  creeperDenied: "why does everyone leave?",
  villagerHmm: "Villager: hmm.",
  nitwitHmm: "Nitwit: hmm?",
  farmerHmm: "Farmer: hmm. (he wants 22 sticks for one emerald. you both know it's a robbery)",
  signIncidents: "Days since a\ncreeper blew up\nmy house:\n0",
  signRestart: "Coming soon:\nmy castle.",
  signBackups: "TREASURE.\nDO NOT TOUCH.\n—Bfuuny",
  signBorder: "End of the map.\nOut of budget.\n—{ghost}",
  signToast: "Toast\n(we miss you)",
  signCave: "No.\n(seriously)",
  signQuiet: "Quiet, please.\nThe neighbor downstairs\nhas no eyes,\nbut hears EVERYTHING.",
  signCasi: "almost.\n—{ghost}",
  signBed: "Do not sleep here.\n(learned it the hard way)",
  signDiamond: "This is where I lost\nthe diamond.\nDon't look for it.\nI already did.",
  signUptime: "Back in\n5 minutes.\n—{ghost}\n({days} days ago)",
  diary5: "I went down to the city below. Its frame is just like this one, only bigger.\nSomeone switched it off on purpose.",
  register1: "Admin Register\n\n~~Bfuuny~~ pressed the button. Twice.\n~~BlasterDaster~~ pressed the button.\n~~Ketbome~~ pressed the button.",
  registerLoop: "~~{ghost}~~ pressed the button.",
  register2: "Every crossed-out name is an admin who pressed the button and never came back.\nWho crosses them out? The villagers.\nhmm.",
  bookAdmin2011: "Journal",
  bookAdmin2011By: "by BlasterDaster",
  admin2011a: "If you made it down here, you're one of the curious ones.\nThe first button wasn't on any panel. It was here.",
  admin2011b: "The portals are older than the servers. We only switch them on.\nDon't make noise. It listens.\n— BlasterDaster",
  bookStop: "Command Block",
  stopBook: "Command: /stop\n\n(never ran it)",
  deathLava: "mistook lava for a hot tub",
  deathVoid: "fell into the void. Still falling. Says hi.",
  deathFall: "tried the water bucket trick. Without a bucket.",
  deathBed: "went to bed in the Nether. The bed disagreed.",
  deathWarden: "sneezed in the ancient city. The Warden did not say bless you.",
  deathEnderman: "looked an enderman in the eyes. The enderman looked back.",
  deathBlaze: "asked a blaze if it was hot. It was.",
  deathDragon: "was slain by the Ender Dragon while taking a screenshot to brag",
  deathBreath: "smelled the dragon's breath. Nobody deserves that.",
  deathElytra: "hit a wall at full speed. The wall is fine.",
  deathShulker: "levitated to the sky. Then stopped levitating.",
  deathSilverfish: "was eaten by a silverfish. A silverfish.",
  deathGhast: "was returned to sender",
  advDeeper: "We Need to Go Deeper",
  advButton: "What Does This Button Do?",
  advRods: "Into Fire",
  advReturn: "Return to Sender",
  advSky: "Sky's the Limit",
  subExplosion: "Explosion",
  subBow: "Bow fires",
  subArrow: "Arrow hits",
  subEat: "Eating",
  subHurtPlayer: "Player hurts",
  subVillager: "Villager mumbles",
  subSheep: "Sheep baahs",
  subPig: "Pig oinks",
  subHiss: "Creeper hisses",
  subFlint: "Flint and Steel click",
  subFireball: "Fireball whooshes",
  subBlaze: "Blaze breathes",
  subGhast: "Ghast cries",
  subHeartbeat: "Warden's heart beats",
  subRoar: "Warden roars",
  subShriek: "Sculk Shrieker shrieks",
  subSculk: "Sculk Sensor clicks",
  subSqueak: "Silverfish hisses",
  subZap: "Shulker bullet",
  subLevitate: "Levitating",
  subNetherPortal: "Portal opens",
  deathCreeper: "got a hug from Kevin",
  creeperGranted: "i just wanted a hug.",
  mobSlain: "was slain by {player}",
  pigDown: "is down. Again.",
  clickToPlay: "Click to keep playing",
  noWebgl: "Your browser can't draw the game in 3D (WebGL2 is missing). Turn on hardware acceleration in its settings, restart it and try again. Meanwhile, here is the ending.",
  signBfuunyBed: "Great place\nto sleep.\nTrust me.\n—Bfuuny",
  signBfuunyShip: "The good elytra\nare on the\nother ship.\n—Bfuuny",
  signBfuunyExit: "EXIT\n→\n—Bfuuny",
  bfuunyChest: "lol. it's dirt. all of it.",
  bfuunyBed: "lol. I said trust me.",
  ghostWardenHit: "are you hitting it? the Warden? brave.",
  ghostWarden: "…ok. nobody had ever done that.",
};

export type LoreKey = keyof typeof en;

export default en;
