export const en = {
  endTitle: 'The End',
  endSubtitle: 'You drifted into the End. There was nothing to destroy here after all.',
  return: 'Return to the Overworld',
  advancement: 'Advancement Made!',
  itemEgg: 'Dragon Egg',
  intro: "Ketbome's test server #47. Status: almost finished.",
  endTagline: 'Or the beginning?',
  goalReached: 'Goal Reached!',
  advEyeSpy: 'Eye Spy',
  advEnterEnd: 'The End?',
  advFreeEnd: 'Free the End',
  advNextGen: 'The Next Generation',
  chatAdvancement: '{player} has made the advancement',
  chatGoal: '{player} has reached the goal',
  player: 'Player',
  bossName: 'Ender Dragon',
  objectives: 'Objectives',
  objCrystals: 'Destroy the End Crystals',
  objDragon: 'Slay the Ender Dragon',
  objEgg: 'Catch the Dragon Egg',
  objPortal: 'Jump into the exit portal',
  hintHealing: 'The crystals are healing it. Break them first.',
  hintPerch: 'The dragon is over the portal. Strike now!',
  hintTakeoff: 'The dragon takes off. Arrows reach it in the air.',
  hintCharge: 'The dragon is diving at you. Sidestep!',
  hintArrowsBounce: 'Arrows glance off it while it rests. Use the sword.',
  hintEnraged: 'The dragon is enraged!',
  hintEnderman: "Don't look them in the eyes.",
  hintEgg: 'The egg teleported away. Try again.',
  hintPortal: 'The exit portal is open.',
  subEye: 'Eye of Ender attaches',
  subPortal: 'End Portal opens',
  subTravel: 'Portal whooshes',
  subLava: 'Lava pops',
  subGrowl: 'Ender Dragon growls',
  subHurt: 'Ender Dragon hurts',
  subDeath: 'Ender Dragon dies',
  subCrystal: 'End Crystal explodes',
  subEnderman: 'Enderman teleports',
  subEgg: 'Dragon Egg teleports',
  subXp: 'Experience Orb tinkles',
  subGateway: 'End Gateway spawns',
  mute: 'Mute sound',
  unmute: 'Unmute sound',
  skip: 'Skip',
  poem: "I see the player you mean.\n{player}?\nYes. Take care. It has reached a higher level now. It can read our thoughts.\nThat doesn't matter. It thinks we are part of the game.\nI like this player. It played well. It did not give up.\nIt came to a server that was never finished. It played it anyway.\nIt builds worlds for its friends to play in. It keeps them open while they sleep.\nIt fixes what breaks. It keeps what matters. It never asked to be thanked.\nThere were three before it. One built. One won. One died, over and over, and laughed every time.\nThey are still here. They were waiting for it.\nWhat did this player dream?\nThis player dreamed of sunlight and trees. Of fire and water. It dreamed it created. And it dreamed it destroyed. It dreamed it hunted, and was hunted. It dreamed of shelter.\nAnd the universe said you are not alone\nAnd the universe said you are not separate from every other thing\nAnd the universe said you are the universe tasting itself, talking to itself, reading its own code\nAnd the universe said I love you because you are love.\nAnd the game was over and the player woke up from the dream. And the player began a new dream. And the player dreamed again, dreamed better. And the player was the universe. And the player was love.\nYou are the player.\nWake up.",
  poemCredit: "End Poem by Julian Gough (CC0), abridged. Five lines were written for Minepanel.",
  poemHint: 'Hold Space, or press and hold, to speed up',
  itemNote: "Note",
  itemDiamond: "Diamond",
  itemStick: "Stick",
  itemPearl: "Ender Pearl",
  itemBlaze: "Blaze Powder",
  itemBow: "Bow",
  itemApple: "Golden Apple",
  itemSword: "Diamond Sword",
  itemEye: "Eye of Ender",
  chest: "Chest",
  crafting: "Crafting",
  inventory: "Inventory",
  takeAll: "Take all",
  recipeBook: "Recipe book",
  craftHelp: "Put items on the grid and take the result. Shift + click the result to craft everything the grid holds. The recipe book lays out a set (Shift: as many as you can).",
  emptySlot: "Empty slot",
  close: "Close",
  page: "Page {n} of {total}",
  prevPage: "Previous page",
  nextPage: "Next page",
  diaryTitle: "Diary",
  diaryBy: "by {ghost}",
  sign: "Sign",
  note: "Server #47. This one I finish, I promise.\nI left you what I had in the chest. The table is still there.\nDon't trust Bfuuny's chests. Don't race BlasterDaster. You'll lose.\nKeep one pearl. You'll understand.\n— {ghost}",
  diary1: "Server #47, day 1. The camp is ready. The castle comes next.\n(the castle never came)",
  diary2: "Day 3. The portal already had three eyes in it.\nBlasterDaster got here first, obviously. He left a sign: \"too slow\".",
  diary3: "Endermen keep stealing my blocks. I think they're building something too.\nProbably better than me.",
  diary4: "I'm going to the End to build the definitive server.\nKill the dragon, then take the gateway. We'll be waiting.\n— {ghost}",
  tomb: "Here lies Bfuuny.\nAgain.\n(death #312: he waved at the dragon)",
  ghostArrival: "you made it.",
  ghostCrystal: "it took me much longer.",
  ghostPerch: "now. while it rests.",
  ghostVictory: "don't leave yet.",
  ghostGateway: "the gateway. we're all waiting there. bring a pearl.",
  ghostNotYet: "that enderman guards bfuuny's grave. someone has to.",
  ghostThanks: "thanks for using Minepanel. really. it's the three of us and a lot of coffee.",
  chatJoined: "{ghost} joined the game",
  chatLeft: "{ghost} left the game",
  stayTitle: "GG",
  staySubtitle: "Bfuuny died again.",
  hintCamp: "Someone camped here. Open the chest.",
  hintDig: "Never dig straight down.",
  hintLectern: "Something is written on the lectern.",
  hintJump: "Jump into the portal.",
  hintMeet: "Glide down to the islet. They are waiting for you.",
  objChest: "Check the chest",
  objSword: "Craft a sword",
  objEyes: "Craft Eyes of Ender",
  objThrow: "Throw an Eye of Ender",
  objDig: "Dig down",
  objFrame: "Complete the portal frame",
  objJump: "Jump into the portal",
  objDiary: "Read the diary on the lectern",
  advStrike: "Time to Strike!",
  advGetaway: "Remote Getaway",
  subChest: "Chest opens",
  subPage: "Page turns",
  subBreak: "Block broken",
  subThrow: "Eye of Ender shoots",
  subShatter: "Eye of Ender breaks",
  subWhisper: "Something whispers",
  controlsTitle: "Controls",
  paused: "Game paused",
  play: "Play",
  resume: "Back to game",
  leave: "Leave to the panel",
  ctrlMove: "WASD — move",
  ctrlJump: "Space — jump (in the air with elytra: glide)",
  ctrlSneak: "Shift — sneak",
  ctrlSprint: "Ctrl — sprint",
  ctrlAttack: "Left click — hit / mine",
  ctrlUse: "Right click — use, place a block (hold: draw the bow, eat)",
  ctrlHotbar: "1-9 / wheel — hotbar",
  ctrlInventory: "E — inventory",
  ctrlPause: "Esc — pause",
  ctrlTouch: "Left thumb: move. Drag on the right: look. Buttons: hit, use, jump, sneak, sprint, inventory and pause.",
  touchAttack: "Hit",
  touchUse: "Use",
  touchJump: "Jump",
  touchPause: "Pause",
  touchInventory: "Inventory",
  touchSneak: "Sneak",
  touchSprint: "Sprint",
  chestBackups: "Chest: treasure",
  inventoryHelp: "Left click: take or drop a stack. Right click: take half or drop one. Shift + click: send it across. Drag a held stack to share it out.",
  librarian: "Librarian",
  librarianHmm: "hmm. (the librarian looks at you like they know something)",
  soldOut: "Sold",
  mapLegend: "■ camp · ▲ village · ◆ ruined portal · ? cave",
  mapNoSignal: "The map spins aimlessly. It only works in the Overworld.",
  deathTitle: "You Died!",
  deathScore: "Score:",
  respawn: "Respawn",
  noise: "Noise",
  lastSeen: "{ghost} was last seen {days} days ago.",
  lastSeenToday: "{ghost} was last seen today.",
  villager: "Villager",
  nitwit: "Nitwit",
  craftingTable: "Crafting Table",
  lectern: "Lectern",
  portalGap: "A missing obsidian block",
  portalFrame: "Ruined portal",
  bed: "Bed",
  button: "Stone Button",
  frame: "End Portal Frame",
  gateway: "End Gateway",
  itemFrame: "Item Frame",
  commandBlock: "Command Block",
  itemRod: "Blaze Rod",
  itemArrow: "Arrow",
  itemEmerald: "Emerald",
  itemMap: "Map",
  itemRegister: "Bfuuny's Death Register",
  itemFlint: "Flint and Steel",
  itemObsidian: "Obsidian",
  itemElytra: "Elytra",
  itemGold: "Gold Ingot",
  itemDirt: "Dirt",
  hintSword: "Craft a sword at the crafting table.",
  hintObsidian: "Hold obsidian to fill the gap.",
  hintFlint: "Light it with flint and steel.",
  hintNotYet: "Not yet. You still need blaze rods from the Nether.",
  hintEyeKnown: "The eye already showed you the way.",
  hintEyes: "Back to the table: rods into powder, powder into eyes.",
  hintThrowEye: "Use an Eye of Ender (right click).",
  hintCrystalsBow: "Shoot the crystals with the bow: hold right click, then let go.",
  hintNether: "The Nether. It's hot in here.",
  hintFortress: "The fortress is across the lava. Blazes guard it.",
  hintRodsDone: "Three rods. Head back through the portal.",
  hintQuiet: "Sneak (Shift). Something down here is listening.",
  hintGatewayPearl: "Throw an ender pearl into the gateway.",
  hintNoPearl: "No pearls left. Endermen drop them.",
  hintElytra: "Jump off and press jump again in mid-air to glide.",
  hintEndCity: "An End City. Climb the tower stairs: the admin left the elytra on the ship.",
  hintFramesUse: "Use the Eyes of Ender on the empty frames.",
  hintFollowEye: "The eye knows where the portal is. Follow it.",
  objRuined: "Light the ruined portal",
  objMap: "Get the librarian's map",
  objCave: "What is in the cave?",
  objQuiet: "Don't make noise",
  objButton: "Press the button",
  objRods: "Get blaze rods",
  objReturn: "Go back through the portal",
  objGhast: "Return the ghast's fireball",
  objGatewayPearl: "Or throw your pearl into the gateway?",
  objElytra: "Find the elytra",
  objIslet: "Glide to the islet",
  ghostPortal: "i almost finished it. two blocks short.",
  ghostBack: "now the eyes. you know where the table is.",
  ghostBlaze: "blazes don't forgive. neither did i, with people who asked to be admin.",
  ghostKeepInventory: "dying doesn't cost you your stuff here. you're welcome.",
  ghostShulker: "shulkers give you a free flight. the landing costs extra.",
  ghostBed: "i did warn you.",
  ghostAncient: "so you found the city too.",
  creeperDenied: "why does everyone leave?",
  villagerHmm: "Villager: hmm.",
  nitwitHmm: "Nitwit: hmm?",
  farmerHmm: "Farmer: hmm. (offers you one carrot for an emerald. says it's a friend price)",
  signIncidents: "Days since a\ncreeper blew up\nmy house:\n0",
  signRestart: "Coming soon:\nmy castle.",
  signBackups: "TREASURE.\nDO NOT TOUCH.\n—Bfuuny",
  signBorder: "End of the map.\nOut of budget.\n—{ghost}",
  signToast: "Server pet:\nthe rabbit.\nMore useful than Bfuuny.",
  signCave: "No.\n(seriously)",
  signQuiet: "Quiet, please.\nThe neighbor downstairs\nhas no eyes,\nbut hears EVERYTHING.",
  signCasi: "almost.\n—{ghost}",
  signBed: "Do not sleep here.\n(learned it the hard way)",
  signDiamond: "This is where I lost\nthe diamond.\nDon't look for it.\nI already did.",
  signUptime: "Back in\n5 minutes.\n—{ghost}\n({days} days ago)",
  diary5: "Went down to the ancient city. BlasterDaster says he killed the Warden with a wooden sword.\nI don't believe him. I believe him a little.",
  register1: "Bfuuny's Death Register\n\n#1 fell off the spawn.\n#2 fell off the spawn. Again.\n#58 slept in the Nether. \"it's cozy\".\n#128 hugged Kevin.\n#311 \"I'm just checking how hot the lava is\".",
  register2: "Pages 3 to 40: more of the same.\nThe villagers keep the count. They seem to enjoy it.\nhmm.",
  bookAdmin2011: "Pro Guide",
  bookAdmin2011By: "by BlasterDaster",
  admin2011a: "BlasterDaster's Pro Guide, part 1:\nSneak. Don't sprint. Don't jump. Don't breathe loud.\nIf you hear a heartbeat that isn't yours: run. No, wait. Don't run.",
  admin2011b: "Part 2: shoot an arrow somewhere else. It always goes to check.\nKilled it twice. Bfuuny died four times watching.\nPS: don't press the button by the frame. Not a joke this time.\n— BlasterDaster",
  bookStop: "Command Block",
  stopBook: "Command: /give @p diamond 64\n\n(Bfuuny asked. no.)",
  deathLava: "mistook lava for a hot tub",
  deathVoid: "fell into the void. Still falling. Says hi.",
  deathFall: "tried the water bucket trick. Without a bucket.",
  deathBed: "went to bed in the Nether. The bed disagreed.",
  deathWarden: "sneezed in the ancient city. The Warden did not say bless you.",
  deathEnderman: "looked an enderman in the eyes. The enderman looked back.",
  deathBlaze: "asked a blaze if it was hot. It was.",
  deathDragon: "was slain by the Ender Dragon while taking a screenshot to brag",
  deathBreath: "smelled the dragon's breath. Nobody deserves that.",
  deathElytra: "hit a wall at full speed. The wall is fine.",
  deathShulker: "levitated to the sky. Then stopped levitating.",
  deathSilverfish: "was eaten by a silverfish. A silverfish.",
  deathGhast: "was returned to sender",
  advDeeper: "We Need to Go Deeper",
  advButton: "What Does This Button Do?",
  advRods: "Into Fire",
  advReturn: "Return to Sender",
  advSky: "Sky's the Limit",
  subExplosion: "Explosion",
  subBow: "Bow fires",
  subArrow: "Arrow hits",
  subEat: "Eating",
  subHurtPlayer: "Player hurts",
  subVillager: "Villager mumbles",
  subSheep: "Sheep baahs",
  subPig: "Pig oinks",
  subHiss: "Creeper hisses",
  subFlint: "Flint and Steel click",
  subFireball: "Fireball whooshes",
  subBlaze: "Blaze breathes",
  subGhast: "Ghast cries",
  subHeartbeat: "Warden's heart beats",
  subRoar: "Warden roars",
  subShriek: "Sculk Shrieker shrieks",
  subSculk: "Sculk Sensor clicks",
  subSqueak: "Silverfish hisses",
  subZap: "Shulker bullet",
  subLevitate: "Levitating",
  subNetherPortal: "Portal opens",
  deathCreeper: "got a hug from Kevin",
  creeperGranted: "i just wanted a hug.",
  mobSlain: "was slain by {player}",
  pigDown: "saw it coming.",
  clickToPlay: "Click to keep playing",
  noWebgl: "Your browser can't draw the game in 3D (WebGL2 is missing). Turn on hardware acceleration in its settings, restart it and try again. Meanwhile, here is the ending.",
  signBfuunyBed: "Great place\nto sleep.\nTrust me.\n—Bfuuny",
  signBfuunyShip: "The good elytra\nare on the\nother ship.\n—Bfuuny",
  signBfuunyExit: "EXIT\n→\n—Bfuuny",
  bfuunyChest: "lol. it's dirt. all of it.",
  bfuunyBed: "lol. I said trust me.",
  ghostWardenHit: "are you hitting it? the Warden? brave.",
  ghostWarden: "…ok. nobody had ever done that.",
  itemLog: "Oak Log",
  itemPlanks: "Oak Planks",
  itemCobble: "Cobblestone",
  itemNetherrack: "Netherrack",
  itemEndStone: "End Stone",
  itemPickaxe: "Diamond Pickaxe",
  itemHelmet: "Golden Helmet",
  piglin: "Piglin",
  armor: "Armor",
  armorSlot: "Helmet",
  hintPiglin: "Hold a gold ingot and right click a piglin to barter.",
  hintHelmet: "Wear the golden helmet (right click with it). Piglins only trust gold.",
  hintPearlsLeft: "Three rods. You still need ender pearls: the piglins barter them for gold.",
  objPearls: "Barter ender pearls from piglins",
  ghostPiglin: "piglins. no gold on your head, no friends.",
  ghostDarkness: "the lights went out. that is never a good sign.",
  deathSkeleton: "was sniped by a skeleton. It has no eyes. It didn't need them.",
  deathPiglin: "showed up without gold. The piglins took it personally.",
  subEquip: "Gear equips",
  subPiglin: "Piglin snorts",
  subSkeleton: "Skeleton rattles",
  bfuunyDirt: "see? i told you it was treasure.",
  introBlaster: "new player. 20 bucks says Kevin gets them first.",
  introBfuuny: "deal. i lost 20 to Kevin yesterday.",
  respawnBfuuny: "welcome to the club. i'm the president.",
  respawnBlaster: "practice more.",
  buttonBfuuny: "uh. who invited 'The Rake'?",
  buttonBlaster: "i said don't press it. if you hear breathing behind you, DON'T turn around.",
  victoryKetbome: "gg! the exit portal takes you home.",
  victoryBlaster: "or throw a pearl into the gateway. that's where we are.",
  endKetbome1: "you made it! welcome to the definitive server.",
  endKetbome2: "it's... almost done.",
  endBlaster: "gg. not bad at all.",
  endBfuuny: "watch this, i can totally jump that",
  endBlaster2: "every. single. time.",
  endStar: "if you like it: a star on GitHub, a contribution, or sharing it on social media helps more than you think.",
  endBfuunyBack: "i'm back. what did i miss?",
  bfuunyDiedKevin: "was blown up by Kevin. He wanted a hug.",
  bfuunyDiedPiglin: "was slain by a piglin. He forgot the helmet.",
  bfuunyDiedWarden: "was obliterated by a sonically-charged shriek",
  bfuunyDiedVoid: "fell out of the world. Again.",
  signBlasterSlow: "too slow.\n—BlasterDaster",
  signBlasterRods: "Blaze rods: 3/3\nin 40 seconds.\n—BlasterDaster",
  signBfuunyGrave: "R.I.P. Bfuuny\n(he's fine)\n(he'll be back)",
  signServer48: "Server #48\nComing soon.\n—Ketbome",
  deathRake: "met The Rake. It did not want to talk.",
  deathZombie: "asked a zombie for a hug. It wasn't Kevin.",
  deathZombieVillager: "tried to trade with a zombie villager. It wanted brains.",
  deathDrowned: "went for a swim. The drowned were not lifeguards.",
  deathSpider: "didn't check the ceiling.",
  deathWitch: "accepted a potion from a stranger.",
  deathSlime: "underestimated a tiny slime. Then there were four.",
  deathPhantom: "didn't sleep. Neither does Ketbome, who is used to it.",
  deathZombifiedPiglin: "hit a zombified piglin. Just one.",
  deathHoglin: "called a hoglin a piggy.",
  deathMagmaCube: "tried to put out a magma cube by jumping on it.",
  deathWitherSkeleton: "wanted a wither skull. The skeleton wanted to keep it.",
  deathEndermite: "threw so many pearls that something crawled out of one.",
  subRake: "Something screeches",
  rakeBfuuny: "did anyone else see that???",
  rakeBlaster: "told you. the button.",
  thanksTitle: "Thanks for playing",
  thanksBody: "Minepanel is made by a few people in their spare time, and using it already helps.\nIf you like it, a star on GitHub, a contribution, or sharing it on social media helps it reach more people.",
  thanksStar: "Star on GitHub",
  thanksClose: "Back to the panel",
  subBreath: "Something breathes behind you",
  hintSleepDay: "You can sleep only at night or during thunderstorms",
  hintSleepMonsters: "You may not rest now; there are monsters nearby",
  ghostSleep: "you slept more than I did the whole of server #47.",
  advTreasure: "True Treasure",
  advPacifist: "Pacifist",
  advKevin: "Kevin's Friend",
  advNotAJoke: "It Was Not a Joke",
  advRake: "Still Breathing",
  advNoElytra: "Who Needs Wings",
  lineTreasure: "…you kept it? nobody ever keeps it.",
  linePacifist: "not a single enderman. respect.",
  lineKevin: "hug?",
  lineNotAJoke: "twice. TWICE.",
  lineRake: "you survived? I didn't survive.",
  lineNoElytra: "ok. not even I did that.",
  thanksServer48: "Visit Server #48",
  signServer48Day1: "Server #48. Day 1.\nI started.\n—Ketbome",
  signServer48Blaster: "Server #48 (mine).\nDone.\n—BlasterDaster",
  s48Ketbome: "i started.",
  s48Blaster: "already finished mine.",
  s48Bfuuny: "where's the edge of the map? oh, there it is.",
  s48Ketbome2: "i'll add railings tomorrow.",
  guide3a: "BlasterDaster's pro guide, part 3: the Nether.\nGhasts cry because I win.\nPiglins give me a discount. Must be the charisma.",
  guide3b: "Lava is not a hot tub.\nBfuuny didn't read this part.\nBfuuny doesn't read.\n— BlasterDaster",
  register3: "Page 41: guests.\n{player}: {deaths}.\nBfuuny says yours don't count.\nThey count.",
  rabbitName: "Fluffy",
  signVillage: "Minepanel Village.\nIts neighbors helped\nbuild the panel.\nThank you!",
  signTempleBfuuny: "Don't step in\nthe middle.\n(I stepped in the middle)\n—Bfuuny",
  signRuinDesert: "Server #12:\nthe pyramid.\nI made a corner.\n—Ketbome",
  signRuinTaiga: "Server #23:\nthe igloo. It was\ngoing to be snow.\nIt's dirt.\n—Ketbome",
  signRuinSwamp: "Server #31:\nslime farm.\nSlimes so far: 0.\n—Ketbome",
  signRuinCoast: "Server #40:\nthe harbor.\nI finished the sign.\n—Ketbome",
  signWreckNote: "Buried treasure:\n3 steps north\nof the beach cactus.\n—Bfuuny",
  ghostTreasure: "my diamond! I lost it in the Nether. don't ask how it got here.",
  advRuins: "Unfinished Business",
  ghostRuins: "you saw them all. now you know why I never finish anything.",
  deathTnt: "stepped in the middle. Bfuuny warned you.",
  deathCactus: "leaned on a cactus. For too long.",
  pigName: "Bacon",
};

export type LoreKey = keyof typeof en;

export default en;
