import type { LoreKey } from './en';

const es: Record<LoreKey, string> = {
  endTitle: 'El End',
  endSubtitle: 'Has llegado al End. Después de todo, aquí no había nada que destruir.',
  return: 'Volver al Overworld',
  advancement: '¡Progreso conseguido!',
  itemEgg: 'Huevo de dragón',
  intro: "Servidor de pruebas #47 de Ketbome. Estado: casi terminado.",
  endTagline: '¿O el comienzo?',
  goalReached: '¡Meta alcanzada!',
  advEyeSpy: 'Ojo avizor',
  advEnterEnd: '¿El fin?',
  advFreeEnd: 'Libera el End',
  advNextGen: 'La siguiente generación',
  chatAdvancement: '{player} ha conseguido el progreso',
  chatGoal: '{player} ha alcanzado la meta',
  player: 'Jugador',
  bossName: 'Dragón del End',
  objectives: 'Objetivos',
  objCrystals: 'Destruye los cristales del End',
  objDragon: 'Derrota al Dragón del End',
  objEgg: 'Atrapa el huevo de dragón',
  objPortal: 'Salta al portal de salida',
  hintHealing: 'Los cristales lo están curando. Rómpelos primero.',
  hintPerch: 'El dragón está sobre el portal. ¡Ataca ahora!',
  hintTakeoff: 'El dragón despega. En el aire, las flechas sí le entran.',
  hintCharge: '¡El dragón se lanza en picada hacia ti! Esquiva hacia un lado.',
  hintArrowsBounce: 'Posado, las flechas le rebotan. Usa la espada.',
  hintEnraged: '¡El dragón se ha enfurecido!',
  hintEnderman: 'No los mires a los ojos.',
  hintEgg: 'El huevo se teletransportó. Inténtalo de nuevo.',
  hintPortal: 'El portal de salida está abierto.',
  subEye: 'Ojo de Ender colocado',
  subPortal: 'Se abre el portal del End',
  subTravel: 'Zumbido del portal',
  subLava: 'Burbujeo de lava',
  subGrowl: 'Gruñido del Dragón del End',
  subHurt: 'Dragón del End herido',
  subDeath: 'Muere el Dragón del End',
  subCrystal: 'Explota un cristal del End',
  subEnderman: 'Enderman se teletransporta',
  subEgg: 'Huevo de dragón se teletransporta',
  subXp: 'Tintineo de experiencia',
  subGateway: 'Aparece un acceso del End',
  mute: 'Silenciar sonido',
  unmute: 'Activar sonido',
  skip: 'Saltar',
  poem: "Veo al jugador al que te refieres.\n¿{player}?\nSí. Cuidado. Ha alcanzado un nivel superior. Puede leer nuestros pensamientos.\nNo importa. Cree que somos parte del juego.\nMe gusta este jugador. Jugó bien. No se rindió.\nLlegó a un servidor que nunca se terminó. Lo jugó de todas formas.\nMantiene mundos en marcha para otros. Lee sus registros mientras duermen.\nReinicia lo que se rompe. Guarda lo que importa. Nunca pidió que le dieran las gracias.\nHubo tres antes. Uno construía. Uno ganaba. Uno moría una y otra vez, y se reía cada vez.\nSiguen aquí. Lo estaban esperando.\n¿Qué soñó este jugador?\nEste jugador soñó con la luz del sol y los árboles. Con el fuego y el agua. Soñó que creaba. Y soñó que destruía. Soñó que cazaba y que era cazado. Soñó con un refugio.\nY el universo dijo: no estás solo\nY el universo dijo: no estás separado de todo lo demás\nY el universo dijo: eres el universo saboreándose a sí mismo, hablándose a sí mismo, leyendo su propio código\nY el universo dijo: te amo porque eres amor.\nY el juego terminó y el jugador despertó del sueño. Y el jugador comenzó un nuevo sueño. Y el jugador soñó de nuevo, soñó mejor. Y el jugador era el universo. Y el jugador era amor.\nTú eres el jugador.\nDespierta.",
  poemCredit: "Poema del End de Julian Gough (CC0), abreviado. Cinco líneas se escribieron para Minepanel.",
  poemHint: 'Mantén Espacio o deja presionado para acelerar',
  itemNote: "Nota",
  itemDiamond: "Diamante",
  itemStick: "Palo",
  itemPearl: "Perla de Ender",
  itemBlaze: "Polvo de blaze",
  itemBow: "Arco",
  itemApple: "Manzana dorada",
  itemSword: "Espada de diamante",
  itemEye: "Ojo de Ender",
  chest: "Cofre",
  crafting: "Crafteo",
  inventory: "Inventario",
  takeAll: "Tomar todo",
  recipeBook: "Libro de recetas",
  craftHelp: "Pon objetos en la grilla y toma el resultado. Shift + clic en el resultado craftea todo lo que alcanza la grilla. El libro de recetas arma un set (Shift: todos los que puedas).",
  emptySlot: "Casilla vacía",
  close: "Cerrar",
  page: "Página {n} de {total}",
  prevPage: "Página anterior",
  nextPage: "Página siguiente",
  diaryTitle: "Diario",
  diaryBy: "de {ghost}",
  sign: "Cartel",
  note: "Servidor #47. Este sí lo termino, lo prometo.\nTe dejé lo que tenía en el cofre. La mesa sigue ahí.\nNo confíes en los cofres de Bfuuny. No compitas con BlasterDaster. Vas a perder.\nGuarda una perla. Ya vas a entender.\n— {ghost}",
  diary1: "Servidor #47, día 1. El campamento está listo. Después viene el castillo.\n(el castillo nunca llegó)",
  diary2: "Día 3. El portal ya tenía tres ojos.\nBlasterDaster llegó primero, obvio. Dejó un cartel: \"muy lento\".",
  diary3: "Los endermen me siguen robando bloques. Creo que ellos también están construyendo algo.\nSeguro mejor que yo.",
  diary4: "Me voy al End a construir el servidor definitivo.\nMata al dragón y después toma el gateway. Te esperamos.\n— {ghost}",
  tomb: "Aquí yace Bfuuny.\nOtra vez.\n(muerte #312: le hizo adiós al dragón)",
  ghostArrival: "llegaste.",
  ghostCrystal: "yo tardé mucho más.",
  ghostPerch: "ahora. mientras descansa.",
  ghostVictory: "no te vayas todavía.",
  ghostGateway: "el gateway. ahí te esperamos todos. trae una perla.",
  ghostNotYet: "ese enderman cuida la tumba de bfuuny. alguien tiene que hacerlo.",
  ghostThanks: "gracias por usar Minepanel. de verdad. somos tres y mucho café.",
  chatJoined: "{ghost} se ha unido a la partida",
  chatLeft: "{ghost} ha abandonado la partida",
  stayTitle: "GG",
  staySubtitle: "Bfuuny murió otra vez.",
  hintCamp: "Alguien acampó aquí. Abre el cofre.",
  hintDig: "Nunca caves en línea recta.",
  hintLectern: "Hay algo escrito en el atril.",
  hintJump: "Salta al portal.",
  hintMeet: "Planea hasta el islote. Te están esperando.",
  objChest: "Revisa el cofre",
  objSword: "Craftea una espada",
  objEyes: "Craftea ojos de Ender",
  objThrow: "Lanza un ojo de Ender",
  objDig: "Cava hacia abajo",
  objFrame: "Completa el marco del portal",
  objJump: "Salta al portal",
  objDiary: "Lee el diario del atril",
  advStrike: "¡Hora de atacar!",
  advGetaway: "Escapada remota",
  subChest: "Se abre un cofre",
  subPage: "Pasa una página",
  subBreak: "Bloque roto",
  subThrow: "Ojo de Ender lanzado",
  subShatter: "Ojo de Ender se rompe",
  subWhisper: "Algo susurra",
  controlsTitle: "Controles",
  paused: "Juego en pausa",
  play: "Jugar",
  resume: "Volver al juego",
  leave: "Salir al panel",
  ctrlMove: "WASD — moverte",
  ctrlJump: "Espacio — saltar (en el aire con élitros: planear)",
  ctrlSneak: "Shift — agacharte",
  ctrlSprint: "Ctrl — correr",
  ctrlAttack: "Clic izquierdo — golpear / minar",
  ctrlUse: "Clic derecho — usar, poner un bloque (mantener: tensar el arco, comer)",
  ctrlHotbar: "1-9 / rueda — barra de objetos",
  ctrlInventory: "E — inventario",
  ctrlPause: "Esc — pausa",
  ctrlTouch: "Pulgar izquierdo: moverte. Arrastra a la derecha: mirar. Botones: golpear, usar, saltar, agacharte, correr, inventario y pausa.",
  touchAttack: "Golpear",
  touchUse: "Usar",
  touchJump: "Saltar",
  touchPause: "Pausa",
  touchInventory: "Inventario",
  touchSneak: "Agacharse",
  touchSprint: "Correr",
  chestBackups: "Cofre: tesoro",
  inventoryHelp: "Clic izquierdo: tomar o soltar un stack. Clic derecho: tomar la mitad o soltar uno. Shift + clic: mandarlo al otro lado. Arrastra un stack para repartirlo.",
  librarian: "Bibliotecario",
  librarianHmm: "hmm. (el bibliotecario te mira como si supiera algo)",
  soldOut: "Vendido",
  mapLegend: "■ campamento · ▲ aldea · ◆ portal en ruinas · ? cueva",
  mapNoSignal: "El mapa gira sin rumbo. Solo funciona en el Overworld.",
  deathTitle: "¡Has muerto!",
  deathScore: "Puntuación:",
  respawn: "Reaparecer",
  noise: "Ruido",
  lastSeen: "Última conexión de {ghost}: hace {days} días.",
  lastSeenToday: "Última conexión de {ghost}: hoy.",
  villager: "Aldeano",
  nitwit: "Aldeano tonto",
  craftingTable: "Mesa de crafteo",
  lectern: "Atril",
  portalGap: "Falta un bloque de obsidiana",
  portalFrame: "Portal en ruinas",
  bed: "Cama",
  button: "Botón de piedra",
  frame: "Marco del portal del End",
  gateway: "Acceso del End",
  itemFrame: "Marco",
  commandBlock: "Bloque de comandos",
  itemRod: "Vara de blaze",
  itemArrow: "Flecha",
  itemEmerald: "Esmeralda",
  itemMap: "Mapa",
  itemRegister: "Registro de muertes de Bfuuny",
  itemFlint: "Encendedor",
  itemObsidian: "Obsidiana",
  itemElytra: "Élitros",
  itemGold: "Lingote de oro",
  itemDirt: "Tierra",
  hintSword: "Craftea una espada en la mesa de crafteo.",
  hintObsidian: "Sostén obsidiana para rellenar el hueco.",
  hintFlint: "Enciéndelo con el encendedor.",
  hintNotYet: "Todavía no. Te faltan varas de blaze del Nether.",
  hintEyeKnown: "El ojo ya te mostró el camino.",
  hintEyes: "Vuelve a la mesa: varas a polvo, polvo a ojos.",
  hintThrowEye: "Usa un ojo de Ender (clic derecho).",
  hintCrystalsBow: "Dispárales a los cristales con el arco: mantén clic derecho y suelta.",
  hintNether: "El Nether. Hace calor aquí.",
  hintFortress: "La fortaleza está cruzando la lava. La cuidan blazes.",
  hintRodsDone: "Tres varas. Vuelve por el portal.",
  hintQuiet: "Agáchate (Shift). Algo aquí abajo escucha.",
  hintGatewayPearl: "Lanza una perla de Ender al acceso.",
  hintNoPearl: "No te quedan perlas. Los endermen las sueltan.",
  hintElytra: "Salta al vacío y vuelve a saltar en el aire para planear.",
  hintEndCity: "Una ciudad del End. Sube la escalera de la torre: el admin dejó los élitros en el barco.",
  hintFramesUse: "Usa los ojos de Ender sobre los marcos vacíos.",
  hintFollowEye: "El ojo sabe dónde está el portal. Síguelo.",
  objRuined: "Enciende el portal en ruinas",
  objMap: "Consigue el mapa del bibliotecario",
  objCave: "¿Qué hay en la cueva?",
  objQuiet: "No hagas ruido",
  objButton: "Presiona el botón",
  objRods: "Consigue varas de blaze",
  objReturn: "Vuelve por el portal",
  objGhast: "Devuélvele la bola de fuego al ghast",
  objGatewayPearl: "¿O lanzas tu perla al acceso?",
  objElytra: "Encuentra los élitros",
  objIslet: "Planea hasta el islote",
  ghostPortal: "casi lo termino. faltaban dos bloques.",
  ghostBack: "ahora los ojos. ya sabes dónde está la mesa.",
  ghostBlaze: "los blazes no perdonan. yo tampoco perdonaba a los que pedían OP.",
  ghostKeepInventory: "keepInventory activado. de nada.",
  ghostShulker: "los shulkers te hacen volar gratis. el aterrizaje se cobra aparte.",
  ghostBed: "te lo advertí.",
  ghostAncient: "así que también encontraste la ciudad.",
  creeperDenied: "¿por qué todos se van?",
  villagerHmm: "Aldeano: hmm.",
  nitwitHmm: "Aldeano tonto: hmm?",
  farmerHmm: "Granjero: hmm. (quiere 22 palos por una esmeralda. los dos saben que es un robo)",
  signIncidents: "Días sin que\nun creeper me\nvuele la casa:\n0",
  signRestart: "Próximamente:\nmi castillo.",
  signBackups: "TESORO.\nNO TOCAR.\n—Bfuuny",
  signBorder: "Fin del mapa.\nPresupuesto agotado.\n—{ghost}",
  signToast: "Toast\n(te extrañamos)",
  signCave: "No.\n(en serio)",
  signQuiet: "Silencio, por favor.\nEl vecino de abajo\nno tiene ojos,\npero lo oye TODO.",
  signCasi: "casi.\n—{ghost}",
  signBed: "No dormir aquí.\n(lo aprendí mal)",
  signDiamond: "Aquí perdí\nel diamante.\nNo lo busques.\nYa lo busqué.",
  signUptime: "Vuelvo en\n5 minutos.\n—{ghost}\n(hace {days} días)",
  diary5: "Bajé a la ciudad antigua. BlasterDaster dice que mató al Warden con una espada de madera.\nNo le creo. Le creo un poquito.",
  register1: "Registro de muertes de Bfuuny\n\n#1 se cayó del spawn.\n#2 se cayó del spawn. Otra vez.\n#58 durmió en el Nether. \"es acogedor\".\n#128 abrazó a Kevin.\n#311 \"solo estoy viendo qué tan caliente está la lava\".",
  register2: "Páginas 3 a 40: más de lo mismo.\nLos aldeanos llevan la cuenta. Parece que lo disfrutan.\nhmm.",
  bookAdmin2011: "Guía pro",
  bookAdmin2011By: "de BlasterDaster",
  admin2011a: "Guía pro de BlasterDaster, parte 1:\nAgáchate. No corras. No saltes. No respires fuerte.\nSi escuchas un latido que no es el tuyo: skill issue.",
  admin2011b: "Parte 2: dispara una flecha a otro lado. Siempre va a revisar.\nLo maté dos veces. Bfuuny murió cuatro mirando.\nPD: no presiones el botón junto al marco. Esta vez no es broma.\n— BlasterDaster",
  bookStop: "Bloque de comandos",
  stopBook: "Comando: /stop\n\n(nunca lo ejecuté)",
  deathLava: "confundió la lava con un jacuzzi",
  deathVoid: "cayó al vacío. Sigue cayendo. Manda saludos.",
  deathFall: "intentó el truco del balde de agua. Sin balde.",
  deathBed: "se acostó a dormir en el Nether. La cama no estaba de acuerdo.",
  deathWarden: "estornudó en la ciudad antigua. El Warden no dijo salud.",
  deathEnderman: "miró a un enderman a los ojos. El enderman también.",
  deathBlaze: "le preguntó a un blaze si quemaba. Quemaba.",
  deathDragon: "fue eliminado por el Dragón del End mientras sacaba una captura para presumir",
  deathBreath: "olió el aliento del dragón. Nadie merece eso.",
  deathElytra: "chocó contra una pared a toda velocidad. La pared está bien.",
  deathShulker: "levitó hasta el cielo. Luego dejó de levitar.",
  deathSilverfish: "fue devorado por una lepisma. Una lepisma.",
  deathGhast: "fue devuelto al remitente",
  advDeeper: "Hay que ir más hondo",
  advButton: "¿Qué hace este botón?",
  advRods: "Hacia el fuego",
  advReturn: "Devolver al remitente",
  advSky: "El cielo es el límite",
  subExplosion: "Explosión",
  subBow: "Disparo de arco",
  subArrow: "Impacto de flecha",
  subEat: "Comiendo",
  subHurtPlayer: "Jugador herido",
  subVillager: "Aldeano murmura",
  subSheep: "Oveja bala",
  subPig: "Cerdo gruñe",
  subHiss: "Creeper sisea",
  subFlint: "Chispa de encendedor",
  subFireball: "Bola de fuego",
  subBlaze: "Blaze respira",
  subGhast: "Ghast llora",
  subHeartbeat: "Late el corazón del Warden",
  subRoar: "Warden ruge",
  subShriek: "Chillador de sculk chilla",
  subSculk: "Sensor de sculk hace clic",
  subSqueak: "Lepisma chilla",
  subZap: "Bala de shulker",
  subLevitate: "Levitando",
  subNetherPortal: "Se abre un portal",
  deathCreeper: "recibió un abrazo de Kevin",
  creeperGranted: "solo quería un abrazo.",
  mobSlain: "fue asesinado por {player}",
  pigDown: "se cayó. Otra vez.",
  clickToPlay: "Haz clic para seguir jugando",
  noWebgl: "Tu navegador no puede dibujar el juego en 3D (falta WebGL2). Activa la aceleración por hardware en su configuración, reinícialo y vuelve a intentarlo. Mientras, aquí tienes el final.",
  signBfuunyBed: "Buen lugar\npara dormir.\nConfía.\n—Bfuuny",
  signBfuunyShip: "Los élitros\nbuenos están\nen el otro barco.\n—Bfuuny",
  signBfuunyExit: "SALIDA\n→\n—Bfuuny",
  bfuunyChest: "jajaja. es tierra. toda.",
  bfuunyBed: "jajaja. dije que confiaras.",
  ghostWardenHit: "¿le estás pegando? ¿al Warden? qué valiente.",
  ghostWarden: "…ok. eso no lo había hecho nadie.",
  itemLog: "Tronco de roble",
  itemPlanks: "Tablas de roble",
  itemCobble: "Roca",
  itemNetherrack: "Netherrack",
  itemEndStone: "Piedra del End",
  itemPickaxe: "Pico de diamante",
  itemHelmet: "Casco de oro",
  piglin: "Piglin",
  armor: "Armadura",
  armorSlot: "Casco",
  hintPiglin: "Sostén un lingote de oro y haz clic derecho en un piglin para tradear.",
  hintHelmet: "Ponte el casco de oro (clic derecho con él). Los piglins solo confían en el oro.",
  hintPearlsLeft: "Tres varas. Aún te faltan perlas de ender: los piglins las cambian por oro.",
  objPearls: "Consigue perlas de ender con los piglins",
  ghostPiglin: "piglins. sin oro en la cabeza, no hay amigos.",
  ghostDarkness: "se apagaron las luces. eso nunca es buena señal.",
  deathSkeleton: "fue francotireado por un esqueleto. No tiene ojos. No los necesitó.",
  deathPiglin: "llegó sin oro. Los piglins se lo tomaron personal.",
  subEquip: "Equipo puesto",
  subPiglin: "Piglin resopla",
  subSkeleton: "Esqueleto traquetea",
  bfuunyDirt: "¿ves? te dije que era un tesoro.",
  introBlaster: "jugador nuevo. apuesto 20 a que Kevin lo mata primero.",
  introBfuuny: "hecho. ayer le perdí 20 a Kevin.",
  respawnBfuuny: "bienvenido al club. tenemos chaquetas.",
  respawnBlaster: "skill issue.",
  buttonBfuuny: "eh. ¿quién invitó a 'The Rake'?",
  buttonBlaster: "dije que no lo presionaras. si escuchas algo respirando detrás tuyo, NO te des vuelta.",
  victoryKetbome: "¡gg! el portal de salida te lleva a casa.",
  victoryBlaster: "o tira una perla al gateway. ahí estamos nosotros.",
  endKetbome1: "¡llegaste! bienvenido al servidor definitivo.",
  endKetbome2: "está... casi listo.",
  endBlaster: "gg. nada mal.",
  endBfuuny: "miren esto, ese salto lo hago fácil",
  endBlaster2: "todas. las. veces.",
  endStar: "si te gusta: una estrella en GitHub, una contribución o compartirlo en redes ayuda más de lo que crees.",
  endBfuunyBack: "volví. ¿qué me perdí?",
  bfuunyDiedKevin: "explotó por culpa de Kevin. Quería un abrazo.",
  bfuunyDiedPiglin: "fue asesinado por un piglin. Olvidó el casco.",
  bfuunyDiedWarden: "fue aniquilado por un chillido sónico",
  bfuunyDiedVoid: "se cayó del mundo. Otra vez.",
  signBlasterSlow: "muy lento.\n—BlasterDaster",
  signBlasterRods: "Varas de blaze: 3/3\nen 40 segundos.\n—BlasterDaster",
  signBfuunyGrave: "Q.E.P.D. Bfuuny\n(está bien)\n(ya vuelve)",
  signServer48: "Servidor #48\nPróximamente.\n—Ketbome",
  deathRake: "se encontró con The Rake. No quería conversar.",
  subRake: "Algo chilla",
  rakeBfuuny: "¿¿alguien más vio eso??",
  rakeBlaster: "te lo dije. el botón.",
  thanksTitle: "Gracias por jugar",
  thanksBody: "Minepanel lo hacen unas pocas personas en su tiempo libre, y usarlo ya ayuda.\nSi te gusta, una estrella en GitHub, una contribución o compartirlo en redes ayuda a que llegue a más gente.",
  thanksStar: "Estrella en GitHub",
  thanksClose: "Volver al panel",
  subBreath: "Algo respira detrás de ti",
};

export default es;
