import type { LoreKey } from './en';

const fr: Record<LoreKey, string> = {
  endTitle: "L'End",
  endSubtitle: "Vous avez dérivé dans l'End. Il n'y avait finalement rien à détruire ici.",
  return: "Retour à l'Overworld",
  advancement: 'Progrès accompli !',
  itemEgg: 'Œuf de dragon',
  intro: "Serveur de test n°47 de Ketbome. Statut : presque fini.",
  endTagline: 'Ou le commencement ?',
  goalReached: 'Objectif atteint !',
  advEyeSpy: 'Œil espion',
  advEnterEnd: 'La Fin ?',
  advFreeEnd: "Libérer l'End",
  advNextGen: 'La nouvelle génération',
  chatAdvancement: '{player} a accompli le progrès',
  chatGoal: "{player} a atteint l'objectif",
  player: 'Joueur',
  bossName: "Dragon de l'Ender",
  objectives: 'Objectifs',
  objCrystals: "Détruire les cristaux de l'End",
  objDragon: "Vaincre le dragon de l'Ender",
  objEgg: "Attraper l'œuf de dragon",
  objPortal: 'Sauter dans le portail de sortie',
  hintHealing: "Les cristaux le soignent. Brisez-les d'abord.",
  hintPerch: 'Le dragon survole le portail. Frappez maintenant !',
  hintTakeoff: "Le dragon s'envole. En vol, les flèches le touchent.",
  hintCharge: 'Le dragon pique sur vous. Esquivez sur le côté !',
  hintArrowsBounce: "Posé, les flèches ricochent sur lui. Prenez l'épée.",
  hintEnraged: 'Le dragon est enragé !',
  hintEnderman: 'Ne les regardez pas dans les yeux.',
  hintEgg: "L'œuf s'est téléporté. Réessayez.",
  hintPortal: 'Le portail de sortie est ouvert.',
  subEye: "Œil de l'Ender placé",
  subPortal: "Le portail de l'End s'ouvre",
  subTravel: 'Le portail vrombit',
  subLava: 'La lave bouillonne',
  subGrowl: "Le dragon de l'Ender grogne",
  subHurt: "Le dragon de l'Ender est blessé",
  subDeath: "Le dragon de l'Ender meurt",
  subCrystal: "Un cristal de l'End explose",
  subEnderman: 'Un Enderman se téléporte',
  subEgg: "L'œuf de dragon se téléporte",
  subXp: "Un orbe d'expérience tinte",
  subGateway: "Un portail de l'End apparaît",
  mute: 'Couper le son',
  unmute: 'Activer le son',
  skip: 'Passer',
  poem: "Je vois le joueur dont tu parles.\n{player} ?\nOui. Prends garde. Il a atteint un niveau supérieur. Il peut lire nos pensées.\nPeu importe. Il croit que nous faisons partie du jeu.\nJ'aime ce joueur. Il a bien joué. Il n'a pas abandonné.\nIl est arrivé sur un serveur qui n'a jamais été fini. Il y a joué quand même.\nIl crée des mondes où ses amis peuvent jouer. Il les garde ouverts pendant qu'ils dorment.\nIl répare ce qui casse. Il garde ce qui compte. Il n'a jamais demandé de remerciements.\nIls étaient trois avant lui. L'un construisait. L'un gagnait. L'un mourait encore et encore, et riait à chaque fois.\nIls sont toujours là. Ils l'attendaient.\nDe quoi ce joueur a-t-il rêvé ?\nCe joueur a rêvé de soleil et d'arbres. De feu et d'eau. Il a rêvé qu'il créait. Et il a rêvé qu'il détruisait. Il a rêvé qu'il chassait, et qu'il était chassé. Il a rêvé d'un abri.\nEt l'univers dit : tu n'es pas seul\nEt l'univers dit : tu n'es pas séparé de toutes les autres choses\nEt l'univers dit : tu es l'univers qui se goûte lui-même, qui se parle à lui-même, qui lit son propre code\nEt l'univers dit : je t'aime parce que tu es amour.\nEt le jeu était terminé et le joueur s'éveilla du rêve. Et le joueur commença un nouveau rêve. Et le joueur rêva encore, rêva mieux. Et le joueur était l'univers. Et le joueur était amour.\nTu es le joueur.\nRéveille-toi.",
  poemCredit: "Poème de l'End de Julian Gough (CC0), abrégé. Cinq lignes ont été écrites pour Minepanel.",
  poemHint: 'Maintenez Espace ou appuyez longuement pour accélérer',
  itemNote: "Mot",
  itemDiamond: "Diamant",
  itemStick: "Bâton",
  itemPearl: "Perle de l'Ender",
  itemBlaze: "Poudre de Blaze",
  itemBow: "Arc",
  itemApple: "Pomme dorée",
  itemSword: "Épée en diamant",
  itemEye: "Œil de l'Ender",
  chest: "Coffre",
  crafting: "Fabrication",
  inventory: "Inventaire",
  takeAll: "Tout prendre",
  recipeBook: "Livre de recettes",
  craftHelp: "Placez des objets dans la grille et prenez le résultat. Maj + clic sur le résultat fabrique tout ce que la grille permet. Le livre de recettes dispose un lot (Maj : autant que possible).",
  emptySlot: "Emplacement vide",
  close: "Fermer",
  page: "Page {n} sur {total}",
  prevPage: "Page précédente",
  nextPage: "Page suivante",
  diaryTitle: "Journal",
  diaryBy: "par {ghost}",
  sign: "Pancarte",
  note: "Serveur n°47. Celui-là, je le finis, promis.\nJe t'ai laissé ce que j'avais dans le coffre. L'établi est toujours là.\nNe fais pas confiance aux coffres de Bfuuny. Ne fais pas la course avec BlasterDaster. Tu perdras.\nGarde une perle. Tu comprendras.\n— {ghost}",
  diary1: "Serveur n°47, jour 1. Le camp est prêt. Ensuite, le château.\n(le château n'est jamais venu)",
  diary2: "Jour 3. Le portail avait déjà trois yeux.\nBlasterDaster est arrivé le premier, évidemment. Il a laissé un panneau : \"trop lent\".",
  diary3: "Les endermen n'arrêtent pas de me voler des blocs. Je crois qu'eux aussi construisent quelque chose.\nSûrement mieux que moi.",
  diary4: "Je pars dans l'End construire le serveur définitif.\nTue le dragon, puis prends la passerelle. On t'attend.\n— {ghost}",
  tomb: "Ci-gît Bfuuny.\nEncore.\n(mort n°312 : il a fait coucou au dragon)",
  ghostArrival: "te voilà.",
  ghostCrystal: "il m'a fallu bien plus longtemps.",
  ghostPerch: "maintenant. pendant qu'il se repose.",
  ghostVictory: "ne pars pas encore.",
  ghostGateway: "la passerelle. on t'attend tous là-bas. prends une perle.",
  ghostNotYet: "cet enderman garde la tombe de bfuuny. il faut bien que quelqu'un le fasse.",
  ghostThanks: "merci d'utiliser Minepanel. vraiment. on est trois et beaucoup de café.",
  chatJoined: "{ghost} a rejoint la partie",
  chatLeft: "{ghost} a quitté la partie",
  stayTitle: "GG",
  staySubtitle: "Bfuuny est encore mort.",
  hintCamp: "Quelqu'un a campé ici. Ouvrez le coffre.",
  hintDig: "Ne creusez jamais tout droit vers le bas.",
  hintLectern: "Quelque chose est écrit sur le pupitre.",
  hintJump: "Sautez dans le portail.",
  hintMeet: "Plane jusqu'à l'îlot. Ils t'attendent.",
  objChest: "Fouiller le coffre",
  objSword: "Fabriquer une épée",
  objEyes: "Fabriquer des yeux de l'Ender",
  objThrow: "Lancer un œil de l'Ender",
  objDig: "Creuser vers le bas",
  objFrame: "Compléter le cadre du portail",
  objJump: "Sauter dans le portail",
  objDiary: "Lire le journal sur le pupitre",
  advStrike: "À l'attaque !",
  advGetaway: "Escapade à distance",
  subChest: "Un coffre s'ouvre",
  subPage: "Une page se tourne",
  subBreak: "Bloc détruit",
  subThrow: "Œil de l'Ender lancé",
  subShatter: "Œil de l'Ender brisé",
  subWhisper: "Quelque chose chuchote",
  controlsTitle: "Contrôles",
  paused: "Jeu en pause",
  play: "Jouer",
  resume: "Reprendre la partie",
  leave: "Retour au panneau",
  ctrlMove: "WASD — se déplacer",
  ctrlJump: "Espace — sauter (en l'air avec des élytres : planer)",
  ctrlSneak: "Shift — s'accroupir",
  ctrlSprint: "Ctrl — courir",
  ctrlAttack: "Clic gauche — frapper / miner",
  ctrlUse: "Clic droit — utiliser, poser un bloc (maintenir : bander l'arc, manger)",
  ctrlHotbar: "1-9 / molette — barre d'action",
  ctrlInventory: "E — inventaire",
  ctrlPause: "Esc — pause",
  menuSubtitle: "L'aventure de l'End",
  menuSplash: "Presque fini !",
  menuBack: "Retour",
  ctrlScreenshot: "F2 — capture d'écran",
  ctrlMute: "M — activer/couper le son",
  ctrlTouch: "Pouce gauche : se déplacer. Glisser à droite : regarder. Boutons : frapper, utiliser, sauter, s'accroupir, courir, inventaire et pause.",
  touchAttack: "Frapper",
  touchUse: "Utiliser",
  touchJump: "Sauter",
  touchPause: "Pause",
  touchInventory: "Inventaire",
  touchSneak: "S'accroupir",
  touchSprint: "Courir",
  chestBackups: "Coffre : trésor",
  inventoryHelp: "Clic gauche : prendre ou poser une pile. Clic droit : prendre la moitié ou en poser un. Maj + clic : l'envoyer de l'autre côté. Glissez une pile tenue pour la répartir.",
  librarian: "Bibliothécaire",
  librarianHmm: "hmm. (le bibliothécaire vous regarde comme s'il savait quelque chose)",
  soldOut: "Vendu",
  mapLegend: "■ camp · ▲ village · ◆ portail en ruine · ? grotte",
  mapNoSignal: "La carte tourne sans but. Elle ne fonctionne que dans l'Overworld.",
  deathTitle: "Vous êtes mort(e) !",
  deathScore: "Score :",
  respawn: "Ressusciter",
  noise: "Bruit",
  lastSeen: "Dernière connexion de {ghost} : il y a {days} jours.",
  lastSeenToday: "Dernière connexion de {ghost} : aujourd'hui.",
  villager: "Villageois",
  nitwit: "Idiot",
  craftingTable: "Établi",
  lectern: "Pupitre",
  portalGap: "Un bloc d'obsidienne manquant",
  portalFrame: "Portail en ruine",
  bed: "Lit",
  button: "Bouton en pierre",
  frame: "Cadre de portail de l'End",
  gateway: "Passerelle de l'End",
  itemFrame: "Cadre",
  commandBlock: "Bloc de commande",
  itemRod: "Bâton de Blaze",
  itemArrow: "Flèche",
  itemEmerald: "Émeraude",
  itemMap: "Carte",
  itemRegister: "Registre des morts de Bfuuny",
  itemFlint: "Briquet",
  itemObsidian: "Obsidienne",
  itemElytra: "Élytres",
  itemGold: "Lingot d'or",
  itemDirt: "Terre",
  hintSword: "Fabriquez une épée sur l'établi.",
  hintObsidian: "Tenez de l'obsidienne en main pour combler le trou.",
  hintFlint: "Allumez-le avec le briquet.",
  hintNotYet: "Pas encore. Il vous faut des bâtons de Blaze du Nether.",
  hintEyeKnown: "L'œil vous a déjà montré le chemin.",
  hintEyes: "Retour à l'établi : les bâtons en poudre, la poudre en yeux.",
  hintThrowEye: "Utilisez un œil de l'Ender (clic droit).",
  hintCrystalsBow: "Tirez sur les cristaux à l'arc : maintenez le clic droit, puis relâchez.",
  hintNether: "Le Nether. Il fait chaud, ici.",
  hintFortress: "La forteresse est de l'autre côté de la lave. Des blazes la gardent.",
  hintRodsDone: "Trois bâtons. Repassez par le portail.",
  hintQuiet: "Accroupissez-vous (Shift). Ici, en bas, quelque chose écoute.",
  hintGatewayPearl: "Lancez une perle de l'Ender dans la passerelle.",
  hintNoPearl: "Plus de perles. Les endermen en lâchent.",
  hintElytra: "Sautez dans le vide, puis sautez à nouveau en l'air pour planer.",
  hintEndCity: "Une cité de l'End. Monte l'escalier de la tour : l'admin a laissé les élytres sur le navire.",
  hintFramesUse: "Utilisez les yeux de l'Ender sur les cadres vides.",
  hintFollowEye: "L'œil sait où se trouve le portail. Suis-le.",
  objRuined: "Allumer le portail en ruine",
  objMap: "Obtenir la carte du bibliothécaire",
  objCave: "Qu'y a-t-il dans la grotte ?",
  objQuiet: "Ne pas faire de bruit",
  objButton: "Appuyer sur le bouton",
  objRods: "Obtenir des bâtons de Blaze",
  objReturn: "Repasser par le portail",
  objGhast: "Renvoyer la boule de feu du ghast",
  objGatewayPearl: "Ou lancer votre perle dans la passerelle ?",
  objElytra: "Trouver les élytres",
  objIslet: "Planer jusqu'à l'îlot",
  ghostPortal: "je l'avais presque fini. il manquait deux blocs.",
  ghostBack: "maintenant, les yeux. tu sais où est l'établi.",
  ghostBlaze: "les blazes ne pardonnent pas. moi non plus, avec ceux qui voulaient être admin.",
  ghostKeepInventory: "ici, mourir ne te fait pas perdre tes affaires. de rien.",
  ghostShulker: "les shulkers te font voler gratis. l'atterrissage est en supplément.",
  ghostBed: "je t'avais prévenu.",
  ghostAncient: "alors toi aussi, tu as trouvé la cité.",
  creeperDenied: "pourquoi tout le monde s'en va ?",
  villagerHmm: "Villageois : hmm.",
  nitwitHmm: "Idiot : hmm ?",
  farmerHmm: "Fermier : hmm. (il t'offre une carotte contre une émeraude. il dit que c'est un prix d'ami)",
  signIncidents: "Jours sans qu'un\ncreeper m'explose\nla maison :\n0",
  signRestart: "Bientôt ici :\nmon château.",
  signBackups: "TRÉSOR.\nNE PAS TOUCHER.\n—Bfuuny",
  signBorder: "Fin de la carte.\nPlus de budget.\n—{ghost}",
  signToast: "Mascotte du serveur :\nle lapin.\nPlus utile que Bfuuny.",
  signCave: "Non.\n(sérieusement)",
  signQuiet: "Silence, merci.\nLe voisin du dessous\nn'a pas d'yeux,\nmais il entend TOUT.",
  signCasi: "presque.\n—{ghost}",
  signBed: "Ne pas dormir ici.\n(appris à mes dépens)",
  signDiamond: "C'est ici que j'ai perdu\nle diamant.\nNe le cherche pas.\nJe l'ai déjà fait.",
  signUptime: "De retour\ndans 5 minutes.\n—{ghost}\n(il y a {days} jours)",
  diary5: "Je suis descendu à la cité antique. BlasterDaster dit qu'il a tué le Warden avec une épée en bois.\nJe ne le crois pas. Un peu quand même.",
  register1: "Registre des morts de Bfuuny\n\n#1 tombé du spawn.\n#2 tombé du spawn. Encore.\n#58 a dormi dans le Nether. \"c'est cosy\".\n#128 a fait un câlin à Kevin.\n#311 \"je regarde juste si la lave est chaude\".",
  register2: "Pages 3 à 40 : la même chose.\nLes villageois tiennent le compte. Ils ont l'air d'aimer ça.\nhmm.",
  bookAdmin2011: "Guide pro",
  bookAdmin2011By: "par BlasterDaster",
  admin2011a: "Guide pro de BlasterDaster, partie 1 :\nAccroupis-toi. Ne cours pas. Ne saute pas. Ne respire pas fort.\nSi tu entends un battement de cœur qui n'est pas le tien : cours. Non, attends. Ne cours pas.",
  admin2011b: "Partie 2 : tire une flèche ailleurs. Il va toujours vérifier.\nJe l'ai tué deux fois. Bfuuny est mort quatre fois en regardant.\nPS : n'appuie pas sur le bouton près du cadre. Cette fois ce n'est pas une blague.\n— BlasterDaster",
  bookStop: "Bloc de commande",
  stopBook: "Commande : /give @p diamond 64\n\n(Bfuuny a demandé. non.)",
  deathLava: "a pris la lave pour un jacuzzi",
  deathVoid: "est tombé dans le vide. Il tombe encore. Il vous passe le bonjour.",
  deathFall: "a tenté le coup du seau d'eau. Sans seau.",
  deathBed: "s'est couché dans le Nether. Le lit n'était pas d'accord.",
  deathWarden: "a éternué dans la cité antique. Le Warden n'a pas dit « à tes souhaits ».",
  deathEnderman: "a regardé un enderman dans les yeux. L'enderman a soutenu son regard.",
  deathBlaze: "a demandé à un blaze s'il était chaud. Il l'était.",
  deathDragon: "s'est fait tuer par le dragon de l'Ender en faisant un screen pour frimer",
  deathBreath: "a senti l'haleine du dragon. Personne ne mérite ça.",
  deathElytra: "s'est pris un mur à pleine vitesse. Le mur va bien.",
  deathShulker: "a lévité jusqu'au ciel. Puis a cessé de léviter.",
  deathSilverfish: "s'est fait dévorer par un poisson d'argent. Un poisson d'argent.",
  deathGhast: "s'est fait retourner à l'envoyeur",
  advDeeper: "Aller au fond des choses",
  advButton: "À quoi sert ce bouton ?",
  advRods: "Dans le feu de l'action",
  advReturn: "Retour à l'envoyeur",
  advSky: "Vers l'infini et au-delà",
  subExplosion: "Explosion",
  subBow: "Tir d'arc",
  subArrow: "Flèche plantée",
  subEat: "En train de manger",
  subHurtPlayer: "Joueur blessé",
  subVillager: "Marmonnement de villageois",
  subSheep: "Bêlement de mouton",
  subPig: "Grouinement de cochon",
  subHiss: "Sifflement de Creeper",
  subFlint: "Briquet utilisé",
  subFireball: "Boule de feu lancée",
  subBlaze: "Souffle de Blaze",
  subGhast: "Pleurs de Ghast",
  subHeartbeat: "Battement de cœur de Warden",
  subRoar: "Rugissement de Warden",
  subShriek: "Hurlement de hurleur sculk",
  subSculk: "Capteur sculk qui réagit",
  subSqueak: "Sifflement de poisson d'argent",
  subZap: "Projectile de Shulker",
  subLevitate: "Lévitation",
  subNetherPortal: "Portail qui s'ouvre",
  deathCreeper: "a reçu un câlin de Kevin",
  creeperGranted: "je voulais juste un câlin.",
  mobSlain: "a été tué par {player}",
  pigDown: "l'avait vu venir.",
  clickToPlay: "Cliquez pour continuer à jouer",
  noWebgl: "Ton navigateur ne peut pas afficher le jeu en 3D (WebGL2 manquant). Active l'accélération matérielle dans ses paramètres, redémarre-le et réessaie. En attendant, voici la fin.",
  signBfuunyBed: "Super endroit\npour dormir.\nFais-moi confiance.\n—Bfuuny",
  signBfuunyShip: "Les bons élytres\nsont sur\nl'autre navire.\n—Bfuuny",
  signBfuunyExit: "SORTIE\n→\n—Bfuuny",
  bfuunyChest: "mdr. c'est de la terre. tout.",
  bfuunyBed: "mdr. j'avais dit de me faire confiance.",
  ghostWardenHit: "tu le tapes ? le Warden ? courageux.",
  ghostWarden: "…ok. personne n'avait jamais fait ça.",
  itemLog: "Bûche de chêne",
  itemPlanks: "Planches de chêne",
  itemCobble: "Pierre taillée",
  itemNetherrack: "Netherrack",
  itemEndStone: "Pierre de l'End",
  itemPickaxe: "Pioche en diamant",
  itemHelmet: "Casque en or",
  piglin: "Piglin",
  armor: "Armure",
  armorSlot: "Casque",
  hintPiglin: "Tiens un lingot d'or et fais un clic droit sur un piglin pour troquer.",
  hintHelmet: "Mets le casque en or (clic droit avec). Les piglins ne font confiance qu'à l'or.",
  hintPearlsLeft: "Trois bâtons. Il te manque encore des perles de l'Ender : les piglins les troquent contre de l'or.",
  objPearls: "Troquer des perles de l'Ender avec les piglins",
  ghostPiglin: "des piglins. pas d'or sur la tête, pas d'amis.",
  ghostDarkness: "les lumières se sont éteintes. ce n'est jamais bon signe.",
  deathSkeleton: "s'est fait sniper par un squelette. Il n'a pas d'yeux. Il n'en avait pas besoin.",
  deathPiglin: "est venu sans or. Les piglins l'ont mal pris.",
  subEquip: "Équipement mis",
  subPiglin: "Un piglin renifle",
  subSkeleton: "Un squelette cliquette",
  bfuunyDirt: "tu vois ? je t'avais dit que c'était un trésor.",
  introBlaster: "nouveau joueur. 20 balles que Kevin l'a en premier.",
  introBfuuny: "pari tenu. j'ai perdu 20 contre Kevin hier.",
  respawnBfuuny: "bienvenue au club. c'est moi le président.",
  respawnBlaster: "faut t'entraîner.",
  buttonBfuuny: "euh. qui a invité 'The Rake' ?",
  buttonBlaster: "j'avais dit de ne pas appuyer. si tu entends respirer derrière toi, ne te retourne PAS.",
  victoryKetbome: "gg ! le portail de sortie te ramène chez toi.",
  victoryBlaster: "ou lance une perle dans la passerelle. c'est là qu'on est.",
  endKetbome1: "tu y es arrivé ! bienvenue sur le serveur définitif.",
  endKetbome2: "il est... presque fini.",
  endBlaster: "gg. pas mal du tout.",
  endBfuuny: "regardez ça, ce saut je le fais les doigts dans le nez",
  endBlaster2: "à. chaque. fois.",
  endStar: "si ça te plaît : une étoile sur GitHub, une contribution ou le partager sur les réseaux aide plus que tu ne crois.",
  endBfuunyBack: "je suis revenu. j'ai raté quoi ?",
  bfuunyDiedKevin: "a explosé à cause de Kevin. Il voulait un câlin.",
  bfuunyDiedPiglin: "a été tué par un piglin. Il avait oublié le casque.",
  bfuunyDiedWarden: "a été anéanti par un cri chargé d'ondes sonores",
  bfuunyDiedVoid: "est tombé hors du monde. Encore.",
  signBlasterSlow: "trop lent.\n—BlasterDaster",
  signBlasterRods: "Bâtons de blaze : 3/3\nen 40 secondes.\n—BlasterDaster",
  signBfuunyGrave: "R.I.P. Bfuuny\n(il va bien)\n(il revient)",
  signServer48: "Serveur n°48\nBientôt.\n—Ketbome",
  deathRake: "a croisé The Rake. Il ne voulait pas discuter.",
  deathZombie: "a demandé un câlin à un zombie. Ce n'était pas Kevin.",
  deathZombieVillager: "a voulu commercer avec un villageois zombie. Il voulait des cerveaux.",
  deathDrowned: "est allé nager. Les noyés n'étaient pas maîtres-nageurs.",
  deathSpider: "n'a pas regardé au plafond.",
  deathWitch: "a accepté une potion d'une inconnue.",
  deathSlime: "a sous-estimé un petit slime. Puis ils étaient quatre.",
  deathPhantom: "n'a pas dormi. Ketbome non plus, mais Ketbome a l'habitude.",
  deathZombifiedPiglin: "a frappé un piglin zombifié. Un seul.",
  deathHoglin: "a appelé un hoglin « petit cochon ».",
  deathMagmaCube: "a voulu éteindre un cube de magma en sautant dessus.",
  deathWitherSkeleton: "voulait un crâne de wither. Le squelette voulait le garder.",
  deathEndermite: "a lancé tant de perles que quelque chose est sorti de l'une d'elles.",
  subRake: "Quelque chose hurle",
  rakeBfuuny: "quelqu'un d'autre a vu ça ???",
  rakeBlaster: "je t'avais dit. le bouton.",
  thanksTitle: "Merci d'avoir joué",
  thanksBody: "Minepanel est fait par quelques personnes sur leur temps libre, et l'utiliser aide déjà.\nSi tu l'aimes, une étoile sur GitHub, une contribution ou un partage sur les réseaux l'aide à toucher plus de monde.",
  thanksStar: "Étoile sur GitHub",
  thanksClose: "Retour au panneau",
  subBreath: "Quelque chose respire derrière toi",
  hintSleepDay: "Vous ne pouvez dormir que la nuit ou pendant les orages",
  hintSleepMonsters: "Vous ne pouvez pas vous reposer, des monstres sont à proximité",
  ghostSleep: "tu as dormi plus que moi sur tout le serveur #47.",
  advTreasure: "Le vrai trésor",
  advPacifist: "Pacifiste",
  advKevin: "L'ami de Kevin",
  advNotAJoke: "Ce n'était pas une blague",
  advRake: "Toujours là",
  advNoElytra: "Qui a besoin d'ailes ?",
  lineTreasure: "…tu l'as gardée ? personne ne la garde jamais.",
  linePacifist: "pas un seul enderman. respect.",
  lineKevin: "câlin ?",
  lineNotAJoke: "deux fois. DEUX FOIS.",
  lineRake: "tu as survécu ? moi non.",
  lineNoElytra: "ok. même moi, non.",
  thanksServer48: "Visiter le serveur #48",
  signServer48Day1: "Serveur #48. Jour 1.\nJ'ai commencé.\n—Ketbome",
  signServer48Blaster: "Serveur #48 (le mien).\nTerminé.\n—BlasterDaster",
  s48Ketbome: "j'ai commencé.",
  s48Blaster: "le mien est déjà fini.",
  s48Bfuuny: "il est où, le bord de la carte ? ah, là.",
  s48Ketbome2: "demain je mets des barrières.",
  guide3a: "Guide pro de BlasterDaster, partie 3 : le Nether.\nLes ghasts pleurent parce que je gagne.\nLes piglins me font une remise. Sûrement le charisme.",
  guide3b: "La lave n'est pas un jacuzzi.\nBfuuny n'a pas lu cette partie.\nBfuuny ne lit pas.\n— BlasterDaster",
  register3: "Page 41 : invités.\n{player} : {deaths}.\nBfuuny dit que les tiennes ne comptent pas.\nElles comptent.",
  rabbitName: "Pompon",
  signVillage: "Village Minepanel.\nSes habitants ont aidé\nà construire le panel.\nMerci !",
  signTempleBfuuny: "Ne marchez pas\nau milieu.\n(j'ai marché au milieu)\n—Bfuuny",
  signRuinDesert: "Serveur #12 :\nla pyramide.\nJ'ai fait un coin.\n—Ketbome",
  signRuinTaiga: "Serveur #23 :\nl'igloo. Il devait\nêtre en neige. Il est en terre.\n—Ketbome",
  signRuinSwamp: "Serveur #31 :\nferme à slimes.\nSlimes pour l'instant : 0.\n—Ketbome",
  signRuinCoast: "Serveur #40 :\nle port.\nJ'ai fini le panneau.\n—Ketbome",
  signWreckNote: "Trésor enterré :\n3 pas au nord\ndu cactus de la plage.\n—Bfuuny",
  ghostTreasure: "mon diamant ! je l'avais perdu dans le nether. ne demande pas comment il est arrivé ici.",
  advRuins: "Chantiers inachevés",
  ghostRuins: "tu les as toutes vues. maintenant tu sais pourquoi je ne finis jamais rien.",
  deathTnt: "a marché au milieu. Bfuuny avait prévenu.",
  deathCactus: "s'est adossé à un cactus. Trop longtemps.",
  deathGolem: "a frappé le golem de fer du village. Il a rendu le coup.",
  deathRabbit: "a frappé Pompon trois fois. Pompon ne pardonne pas.",
  pelusaBfuuny: "même moi je ne cherche pas Pompon.",
  modeTitle: "Mode",
  modeNormal: "Normal",
  modeSpeedrun: "Speedrun",
  modeHardcore: "Hardcore",
  modeBfuuny: "Mode Bfuuny",
  modeLocked: "Libère l'End une fois pour débloquer les autres modes.",
  records: "Records",
  recordsEmpty: "Personne sur ce panel n'en a encore fini un.",
  recordsBlasterHardcore: "BlasterDaster : « je ne fais pas de hardcore. je fais des speedruns. »",
  recordsYou: "Toi",
  recordsFailed: "Impossible de charger les records.",
  screenshot: "Capture d'écran",
  screenshotSaved: "Capture d'écran enregistrée dans tes téléchargements",
  hardcoreOver: "Game over !",
  hardcoreOverBody: "Hardcore : il n'y avait qu'une vie.",
  hardcoreBlaster: "une vie. comme moi, mais en pire.",
  bfuunyModeDeath: "mort #{bfuuny}. bienvenue dans ma vie.",
  bfuunyModeLaughK: "une de plus pour le registre.",
  bfuunyModeLaughB: "hahaha.",
  raceWin: "ok. revanche.",
  raceLose: "trop lent.",
  advFaster: "Plus rapide que BlasterDaster",
  runTime: "Ton temps :",
  runRank: "Rang #",
  splitNether: "Nether",
  splitStronghold: "Fort",
  splitEnd: "End",
  splitEndcity: "Cité de l'End",
  ghostPhantoms: "deux nuits sans dormir. les choses dans le ciel le remarquent.",
  itemBone: "Os",
  golemAngry: "tu as frappé le golem. je regarde d'ici.",
  wolfTamed: "tu as un chien. j'en avais un aussi. il est parti avec BlasterDaster.",
  wolfDied: "c'est pas moi. cette fois.",
  hintBone: "Tiens un os et utilise-le sur un loup pour l'apprivoiser.",
  pigName: "Lardon",
};

export default fr;
