import type { LoreKey } from './en';

const fr: Record<LoreKey, string> = {
  endTitle: "L'End",
  endSubtitle: "Vous avez dérivé dans l'End. Il n'y avait finalement rien à détruire ici.",
  return: "Retour à l'Overworld",
  advancement: 'Progrès accompli !',
  itemEgg: 'Œuf de dragon',
  intro: 'On vous avait dit de ne pas appuyer.',
  endTagline: 'Ou le commencement ?',
  goalReached: 'Objectif atteint !',
  advEyeSpy: 'Œil espion',
  advEnterEnd: 'La Fin ?',
  advFreeEnd: "Libérer l'End",
  advNextGen: 'La nouvelle génération',
  chatAdvancement: '{player} a accompli le progrès',
  chatGoal: "{player} a atteint l'objectif",
  player: 'Joueur',
  bossName: "Dragon de l'Ender",
  objectives: 'Objectifs',
  objCrystals: "Détruire les cristaux de l'End",
  objDragon: "Vaincre le dragon de l'Ender",
  objEgg: "Attraper l'œuf de dragon",
  objPortal: 'Sauter dans le portail de sortie',
  hintHealing: "Les cristaux le soignent. Brisez-les d'abord.",
  hintPerch: 'Le dragon survole le portail. Frappez maintenant !',
  hintEnderman: 'Ne les regardez pas dans les yeux.',
  hintEgg: "L'œuf s'est téléporté. Réessayez.",
  hintPortal: 'Le portail de sortie est ouvert.',
  subEye: "Œil de l'Ender placé",
  subPortal: "Le portail de l'End s'ouvre",
  subTravel: 'Le portail vrombit',
  subLava: 'La lave bouillonne',
  subGrowl: "Le dragon de l'Ender grogne",
  subHurt: "Le dragon de l'Ender est blessé",
  subDeath: "Le dragon de l'Ender meurt",
  subCrystal: "Un cristal de l'End explose",
  subEnderman: 'Un Enderman se téléporte',
  subEgg: "L'œuf de dragon se téléporte",
  subXp: "Un orbe d'expérience tinte",
  subGateway: "Un portail de l'End apparaît",
  mute: 'Couper le son',
  unmute: 'Activer le son',
  skip: 'Passer',
  poem: "Je vois le joueur dont tu parles.\n{player} ?\nOui. Prends garde. Il a atteint un niveau supérieur. Il peut lire nos pensées.\nPeu importe. Il croit que nous faisons partie du jeu.\nJ'aime ce joueur. Il a bien joué. Il n'a pas abandonné.\nOn lui avait dit de ne pas appuyer sur le bouton.\nIl a appuyé quand même. Ils le font toujours. C'est ainsi qu'ils nous trouvent.\nIl fait tourner des mondes pour les autres. Il lit leurs journaux pendant qu'ils dorment.\nIl redémarre ce qui casse. Il garde ce qui compte. Il n'a jamais demandé de remerciements.\nIl y en a eu un autre avant. Lui aussi a bien joué. Il est resté.\nCelui-ci se réveillera.\nDe quoi ce joueur a-t-il rêvé ?\nCe joueur a rêvé de soleil et d'arbres. De feu et d'eau. Il a rêvé qu'il créait. Et il a rêvé qu'il détruisait. Il a rêvé qu'il chassait, et qu'il était chassé. Il a rêvé d'un abri.\nEt l'univers dit : tu n'es pas seul\nEt l'univers dit : tu n'es pas séparé de toutes les autres choses\nEt l'univers dit : tu es l'univers qui se goûte lui-même, qui se parle à lui-même, qui lit son propre code\nEt l'univers dit : je t'aime parce que tu es amour.\nEt le jeu était terminé et le joueur s'éveilla du rêve. Et le joueur commença un nouveau rêve. Et le joueur rêva encore, rêva mieux. Et le joueur était l'univers. Et le joueur était amour.\nTu es le joueur.\nRéveille-toi.",
  poemCredit: "Poème de l'End de Julian Gough (CC0), abrégé. Six lignes ont été écrites pour Minepanel.",
  poemHint: 'Maintenez Espace ou appuyez longuement pour accélérer',
  itemNote: "Mot",
  itemDiamond: "Diamant",
  itemStick: "Bâton",
  itemPearl: "Perle de l'Ender",
  itemBlaze: "Poudre de Blaze",
  itemBow: "Arc",
  itemApple: "Pomme dorée",
  itemSword: "Épée en diamant",
  itemEye: "Œil de l'Ender",
  chest: "Coffre",
  crafting: "Fabrication",
  inventory: "Inventaire",
  takeAll: "Tout prendre",
  recipeBook: "Livre de recettes",
  craftHelp: "Placez des objets dans la grille et prenez le résultat. Maj + clic sur le résultat fabrique tout ce que la grille permet. Le livre de recettes dispose un lot (Maj : autant que possible).",
  emptySlot: "Emplacement vide",
  close: "Fermer",
  page: "Page {n} sur {total}",
  prevPage: "Page précédente",
  nextPage: "Page suivante",
  diaryTitle: "Journal",
  diaryBy: "par {ghost}",
  sign: "Pancarte",
  note: "À qui viendra ensuite.\nJe savais que tu appuierais. On le fait tous.\nJe t'ai laissé ce qu'il me restait. L'établi est toujours là.\nGarde une perle. Tu comprendras.\n— {ghost}",
  diary1: "J'ai fait tourner ce serveur pendant des années. J'ai redémarré ce qui cassait. Personne n'a jamais su mon nom.\nCe soir, j'ai appuyé sur le bouton.",
  diary2: "Le portail avait déjà trois yeux.\nJe n'étais pas là en premier. Quelqu'un était là avant moi, et encore avant, quelqu'un d'autre.",
  diary3: "On dit que les endermen portent des blocs parce que quelque chose leur manque.\nQu'ils ne supportent pas d'être regardés parce que ça leur rappelle qui ils étaient.",
  diary4: "Je descends.\nSi quelqu'un lit ceci : tue le dragon. Puis choisis.\n— {ghost}",
  tomb: "Ici demeure\n{ghost}.\nCe n'était pas le dragon.",
  ghostArrival: "te voilà.",
  ghostCrystal: "il m'a fallu bien plus longtemps.",
  ghostPerch: "maintenant. pendant qu'il se repose.",
  ghostVictory: "ne pars pas encore.",
  ghostGateway: "la passerelle. viens.",
  ghostNotYet: "pas encore.",
  ghostThanks: "merci d'être là.",
  chatJoined: "{ghost} a rejoint la partie",
  chatLeft: "{ghost} a quitté la partie",
  stayTitle: "Vous avez choisi de rester.",
  staySubtitle: "Quelqu'un finira par appuyer.",
  hintCamp: "Quelqu'un a campé ici. Ouvrez le coffre.",
  hintDig: "Ne creusez jamais tout droit vers le bas.",
  hintLectern: "Quelque chose est écrit sur le pupitre.",
  hintJump: "Sautez dans le portail.",
  hintMeet: "Quelqu'un vous attend.",
  objChest: "Fouiller le coffre",
  objSword: "Fabriquer une épée",
  objEyes: "Fabriquer des yeux de l'Ender",
  objThrow: "Lancer un œil de l'Ender",
  objDig: "Creuser vers le bas",
  objFrame: "Compléter le cadre du portail",
  objJump: "Sauter dans le portail",
  objDiary: "Lire le journal sur le pupitre",
  advStrike: "À l'attaque !",
  advGetaway: "Escapade à distance",
  subChest: "Un coffre s'ouvre",
  subPage: "Une page se tourne",
  subBreak: "Bloc détruit",
  subThrow: "Œil de l'Ender lancé",
  subShatter: "Œil de l'Ender brisé",
  subWhisper: "Quelque chose chuchote",
  controlsTitle: "Contrôles",
  paused: "Jeu en pause",
  play: "Jouer",
  resume: "Reprendre la partie",
  leave: "Retour au panneau",
  ctrlMove: "WASD — se déplacer",
  ctrlJump: "Espace — sauter (en l'air avec des élytres : planer)",
  ctrlSneak: "Shift — s'accroupir",
  ctrlSprint: "Ctrl — courir",
  ctrlAttack: "Clic gauche — frapper / miner",
  ctrlUse: "Clic droit — utiliser (maintenir : bander l'arc, manger)",
  ctrlHotbar: "1-9 / molette — barre d'action",
  ctrlInventory: "E — inventaire",
  ctrlPause: "Esc — pause",
  ctrlTouch: "Pouce gauche : se déplacer. Glisser à droite : regarder. Boutons : frapper, utiliser, sauter, s'accroupir, courir, inventaire et pause.",
  touchAttack: "Frapper",
  touchUse: "Utiliser",
  touchJump: "Sauter",
  touchPause: "Pause",
  touchInventory: "Inventaire",
  touchSneak: "S'accroupir",
  touchSprint: "Courir",
  chestBackups: "Coffre : trésor",
  inventoryHelp: "Clic gauche : prendre ou poser une pile. Clic droit : prendre la moitié ou en poser un. Maj + clic : l'envoyer de l'autre côté. Glissez une pile tenue pour la répartir.",
  librarian: "Bibliothécaire",
  librarianHmm: "hmm. (le bibliothécaire vous regarde comme s'il savait quelque chose)",
  soldOut: "Vendu",
  mapLegend: "■ camp · ▲ village · ◆ portail en ruine · ? grotte",
  mapNoSignal: "La carte tourne sans but. Elle ne fonctionne que dans l'Overworld.",
  deathTitle: "Vous êtes mort(e) !",
  deathScore: "Score :",
  respawn: "Ressusciter",
  noise: "Bruit",
  lastSeen: "Dernière connexion de {ghost} : il y a {days} jours.",
  lastSeenToday: "Dernière connexion de {ghost} : aujourd'hui.",
  villager: "Villageois",
  nitwit: "Idiot",
  craftingTable: "Établi",
  lectern: "Pupitre",
  portalGap: "Un bloc d'obsidienne manquant",
  portalFrame: "Portail en ruine",
  bed: "Lit",
  button: "Bouton en pierre",
  frame: "Cadre de portail de l'End",
  gateway: "Passerelle de l'End",
  itemFrame: "Cadre",
  commandBlock: "Bloc de commande",
  itemRod: "Bâton de Blaze",
  itemArrow: "Flèche",
  itemEmerald: "Émeraude",
  itemMap: "Carte",
  itemRegister: "Registre des admins",
  itemFlint: "Briquet",
  itemObsidian: "Obsidienne",
  itemElytra: "Élytres",
  itemGold: "Pépite d'or",
  itemDirt: "Terre",
  hintSword: "Fabriquez une épée sur l'établi.",
  hintObsidian: "Tenez de l'obsidienne en main pour combler le trou.",
  hintFlint: "Allumez-le avec le briquet.",
  hintNotYet: "Pas encore. Il vous faut des bâtons de Blaze du Nether.",
  hintEyeKnown: "L'œil vous a déjà montré le chemin.",
  hintEyes: "Retour à l'établi : les bâtons en poudre, la poudre en yeux.",
  hintThrowEye: "Utilisez un œil de l'Ender (clic droit).",
  hintCrystalsBow: "Tirez sur les cristaux à l'arc : maintenez le clic droit, puis relâchez.",
  hintNether: "Le Nether. Il fait chaud, ici.",
  hintFortress: "La forteresse est de l'autre côté de la lave. Des blazes la gardent.",
  hintRodsDone: "Trois bâtons. Repassez par le portail.",
  hintQuiet: "Accroupissez-vous (Shift). Ici, en bas, quelque chose écoute.",
  hintGatewayPearl: "Lancez une perle de l'Ender dans la passerelle.",
  hintNoPearl: "Plus de perles. Les endermen en lâchent.",
  hintElytra: "Sautez dans le vide, puis sautez à nouveau en l'air pour planer.",
  hintEndCity: "Une cité de l'End. Monte l'escalier de la tour : l'admin a laissé les élytres sur le navire.",
  hintFramesUse: "Utilisez les yeux de l'Ender sur les cadres vides.",
  hintFollowEye: "L'œil sait où se trouve le portail. Suis-le.",
  objRuined: "Allumer le portail en ruine",
  objMap: "Obtenir la carte du bibliothécaire",
  objCave: "Qu'y a-t-il dans la grotte ?",
  objQuiet: "Ne pas faire de bruit",
  objButton: "Appuyer sur le bouton",
  objRods: "Obtenir des bâtons de Blaze",
  objReturn: "Repasser par le portail",
  objGhast: "Renvoyer la boule de feu du ghast",
  objGatewayPearl: "Ou lancer votre perle dans la passerelle ?",
  objElytra: "Trouver les élytres",
  objIslet: "Planer jusqu'à l'îlot",
  ghostPortal: "je l'avais presque fini. il manquait deux blocs.",
  ghostBack: "maintenant, les yeux. tu sais où est l'établi.",
  ghostBlaze: "les blazes ne pardonnent pas. moi non plus, avec ceux qui réclamaient l'OP.",
  ghostKeepInventory: "keepInventory est activé. de rien.",
  ghostShulker: "les shulkers te font voler gratis. l'atterrissage est en supplément.",
  ghostBed: "je t'avais prévenu.",
  ghostAncient: "alors toi aussi, tu as trouvé la cité.",
  voiceWill: "va-t-il appuyer ?",
  voiceAlways: "ils le font toujours.",
  voiceAgain: "encore.",
  voiceLearning: "laisse-le. il apprend.",
  voiceNo: "non.",
  voiceDone: "…eh bien, voilà, c'est fait.",
  voiceAlmost: "presque.",
  voiceChoose: "maintenant, le plus dur : choisir.",
  creeperDenied: "pourquoi tout le monde s'en va ?",
  villagerHmm: "Villageois : hmm.",
  nitwitHmm: "Idiot : hmm ?",
  farmerHmm: "Fermier : hmm. (il veut 22 bâtons pour une émeraude. vous savez tous les deux que c'est du vol)",
  signIncidents: "Jours sans qu'un\ncreeper m'explose\nla maison :\n0",
  signRestart: "Bientôt ici :\nmon château.",
  signBackups: "TRÉSOR.\nNE PAS TOUCHER.\n—Bfuuny",
  signBorder: "Fin de la carte.\nPlus de budget.\n—{ghost}",
  signToast: "Toast\n(tu nous manques)",
  signCave: "Non.\n(sérieusement)",
  signQuiet: "Silence, merci.\nLe voisin du dessous\nn'a pas d'yeux,\nmais il entend TOUT.",
  signCasi: "presque.\n—{ghost}",
  signBed: "Ne pas dormir ici.\n(appris à mes dépens)",
  signDiamond: "C'est ici que j'ai perdu\nle diamant.\nNe le cherche pas.\nJe l'ai déjà fait.",
  signUptime: "De retour\ndans 5 minutes.\n—{ghost}\n(il y a {days} jours)",
  diary5: "J'ai exploré la cité d'en bas. Son cadre est identique à celui-ci, en plus grand.\nQuelqu'un l'a éteint exprès.",
  register1: "Registre des admins\n\n~~Bfuuny~~ a appuyé sur le bouton. Deux fois.\n~~BlasterDaster~~ a appuyé sur le bouton.\n~~Ketbome~~ a appuyé sur le bouton.",
  registerLoop: "~~{ghost}~~ a appuyé sur le bouton.",
  register2: "Chaque nom rayé est un admin qui a appuyé sur le bouton et n'est jamais revenu.\nQui les raye ? Les villageois.\nhmm.",
  bookAdmin2011: "Carnet",
  bookAdmin2011By: "par BlasterDaster",
  admin2011a: "Si tu as réussi à descendre jusqu'ici, tu fais partie des curieux.\nLe premier bouton n'était sur aucun panneau. Il était ici.",
  admin2011b: "Les portails sont plus anciens que les serveurs. Nous, on ne fait que les allumer.\nNe fais pas de bruit. Il écoute.\n— BlasterDaster",
  bookStop: "Bloc de commande",
  stopBook: "Commande : /stop\n\n(jamais lancée)",
  deathLava: "a pris la lave pour un jacuzzi",
  deathVoid: "est tombé dans le vide. Il tombe encore. Il vous passe le bonjour.",
  deathFall: "a tenté le coup du seau d'eau. Sans seau.",
  deathBed: "s'est couché dans le Nether. Le lit n'était pas d'accord.",
  deathWarden: "a éternué dans la cité antique. Le Warden n'a pas dit « à tes souhaits ».",
  deathEnderman: "a regardé un enderman dans les yeux. L'enderman a soutenu son regard.",
  deathBlaze: "a demandé à un blaze s'il était chaud. Il l'était.",
  deathDragon: "s'est fait tuer par le dragon de l'Ender en faisant un screen pour frimer",
  deathBreath: "a senti l'haleine du dragon. Personne ne mérite ça.",
  deathElytra: "s'est pris un mur à pleine vitesse. Le mur va bien.",
  deathShulker: "a lévité jusqu'au ciel. Puis a cessé de léviter.",
  deathSilverfish: "s'est fait dévorer par un poisson d'argent. Un poisson d'argent.",
  deathGhast: "s'est fait retourner à l'envoyeur",
  advDeeper: "Aller au fond des choses",
  advButton: "À quoi sert ce bouton ?",
  advRods: "Dans le feu de l'action",
  advReturn: "Retour à l'envoyeur",
  advSky: "Vers l'infini et au-delà",
  subExplosion: "Explosion",
  subBow: "Tir d'arc",
  subArrow: "Flèche plantée",
  subEat: "En train de manger",
  subHurtPlayer: "Joueur blessé",
  subVillager: "Marmonnement de villageois",
  subSheep: "Bêlement de mouton",
  subPig: "Grouinement de cochon",
  subHiss: "Sifflement de Creeper",
  subFlint: "Briquet utilisé",
  subFireball: "Boule de feu lancée",
  subBlaze: "Souffle de Blaze",
  subGhast: "Pleurs de Ghast",
  subHeartbeat: "Battement de cœur de Warden",
  subRoar: "Rugissement de Warden",
  subShriek: "Hurlement de hurleur sculk",
  subSculk: "Capteur sculk qui réagit",
  subSqueak: "Sifflement de poisson d'argent",
  subZap: "Projectile de Shulker",
  subLevitate: "Lévitation",
  subNetherPortal: "Portail qui s'ouvre",
  deathCreeper: "a reçu un câlin de Kevin",
  creeperGranted: "je voulais juste un câlin.",
  mobSlain: "a été tué par {player}",
  pigDown: "est en panne. Encore.",
  clickToPlay: "Cliquez pour continuer à jouer",
  noWebgl: "Ton navigateur ne peut pas afficher le jeu en 3D (WebGL2 manquant). Active l'accélération matérielle dans ses paramètres, redémarre-le et réessaie. En attendant, voici la fin.",
  signBfuunyBed: "Super endroit\npour dormir.\nFais-moi confiance.\n—Bfuuny",
  signBfuunyShip: "Les bons élytres\nsont sur\nl'autre navire.\n—Bfuuny",
  signBfuunyExit: "SORTIE\n→\n—Bfuuny",
  bfuunyChest: "mdr. c'est de la terre. tout.",
  bfuunyBed: "mdr. j'avais dit de me faire confiance.",
  ghostWardenHit: "tu le tapes ? le Warden ? courageux.",
  ghostWarden: "…ok. personne n'avait jamais fait ça.",
};

export default fr;
