import type { LoreKey } from './en';

const nl: Record<LoreKey, string> = {
  endTitle: 'The End',
  endSubtitle: 'Je bent in de End beland. Er was hier toch niets te vernietigen.',
  return: 'Terug naar de Overworld',
  advancement: 'Vooruitgang geboekt!',
  itemEgg: 'Drakenei',
  intro: 'Je kreeg te horen dat je er niet op mocht drukken.',
  endTagline: 'Of het begin?',
  goalReached: 'Doel bereikt!',
  advEyeSpy: 'Ik zie, ik zie',
  advEnterEnd: 'Het einde?',
  advFreeEnd: 'Bevrijd de End',
  advNextGen: 'De volgende generatie',
  chatAdvancement: '{player} heeft de vooruitgang geboekt',
  chatGoal: '{player} heeft het doel bereikt',
  player: 'Speler',
  bossName: 'Enderdraak',
  objectives: 'Doelen',
  objCrystals: 'Vernietig de Endkristallen',
  objDragon: 'Versla de Enderdraak',
  objEgg: 'Vang het drakenei',
  objPortal: 'Spring in het uitgangsportaal',
  hintHealing: 'De kristallen genezen hem. Breek ze eerst.',
  hintPerch: 'De draak hangt boven het portaal. Sla nu toe!',
  hintEnderman: 'Kijk ze niet in de ogen.',
  hintEgg: 'Het ei is weggeteleporteerd. Probeer het opnieuw.',
  hintPortal: 'Het uitgangsportaal is open.',
  subEye: 'Enderoog geplaatst',
  subPortal: 'Endportaal opent',
  subTravel: 'Portaal zoemt',
  subLava: 'Lava borrelt',
  subGrowl: 'Enderdraak gromt',
  subHurt: 'Enderdraak gewond',
  subDeath: 'Enderdraak sterft',
  subCrystal: 'Endkristal ontploft',
  subEnderman: 'Enderman teleporteert',
  subEgg: 'Drakenei teleporteert',
  subXp: 'Ervaringsbol rinkelt',
  subGateway: 'Endpoort verschijnt',
  mute: 'Geluid uit',
  unmute: 'Geluid aan',
  skip: 'Overslaan',
  poem: 'Ik zie de speler die je bedoelt.\n{player}?\nJa. Pas op. Hij heeft nu een hoger niveau bereikt. Hij kan onze gedachten lezen.\nDat maakt niet uit. Hij denkt dat wij deel van het spel zijn.\nIk mag deze speler. Hij speelde goed. Hij gaf niet op.\nHem werd gezegd dat hij niet op de knop moest drukken.\nHij drukte er toch op. Dat doen ze altijd. Zo vinden ze ons.\nHij houdt werelden draaiende voor anderen. Hij leest hun logs terwijl zij slapen.\nHij herstart wat kapotgaat. Hij bewaart wat ertoe doet. Hij heeft nooit om een bedankje gevraagd.\nEr was er eerder al een. Ook die speelde goed. Die bleef.\nDeze wordt wakker.\nWaar droomde deze speler van?\nDeze speler droomde van zonlicht en bomen. Van vuur en water. Hij droomde dat hij schiep. En hij droomde dat hij vernietigde. Hij droomde dat hij jaagde, en werd opgejaagd. Hij droomde van beschutting.\nEn het universum zei: je bent niet alleen\nEn het universum zei: je bent niet gescheiden van al het andere\nEn het universum zei: jij bent het universum dat zichzelf proeft, tegen zichzelf praat, zijn eigen code leest\nEn het universum zei: ik hou van je, omdat jij liefde bent.\nEn het spel was voorbij en de speler ontwaakte uit de droom. En de speler begon een nieuwe droom. En de speler droomde opnieuw, droomde beter. En de speler was het universum. En de speler was liefde.\nJij bent de speler.\nWord wakker.',
  poemCredit: "Endgedicht van Julian Gough (CC0), ingekort. Zes regels zijn voor Minepanel geschreven.",
  poemHint: 'Houd spatie of je vinger ingedrukt om te versnellen',
  itemNote: "Briefje",
  itemDiamond: "Diamant",
  itemStick: "Stok",
  itemPearl: "Enderparel",
  itemBlaze: "Blazepoeder",
  itemBow: "Boog",
  itemApple: "Gouden appel",
  itemSword: "Diamanten zwaard",
  itemEye: "Enderoog",
  chest: "Kist",
  crafting: "Vervaardiging",
  inventory: "Inventaris",
  takeAll: "Alles pakken",
  recipeBook: "Receptenboek",
  craftHelp: "Leg voorwerpen op het rooster en pak het resultaat. Shift + klik op het resultaat maakt alles wat het rooster toelaat. Het receptenboek legt één set klaar (Shift: zoveel als je kunt).",
  emptySlot: "Leeg vak",
  close: "Sluiten",
  page: "Pagina {n} van {total}",
  prevPage: "Vorige pagina",
  nextPage: "Volgende pagina",
  diaryTitle: "Dagboek",
  diaryBy: "door {ghost}",
  sign: "Bord",
  note: "Voor de volgende.\nIk wist dat je erop zou drukken. Dat doen we allemaal.\nIk heb voor je achtergelaten wat ik nog had. De werkbank staat er nog.\nBewaar één parel. Je zult het begrijpen.\n— {ghost}",
  diary1: "Ik heb deze server jarenlang draaiende gehouden. Ik herstartte wat kapotging. Niemand kende ooit mijn naam.\nVannacht heb ik op de knop gedrukt.",
  diary2: "Er zaten al drie ogen in het portaal.\nIk was niet de eerste. Iemand was hier vóór mij, en daarvoor weer iemand anders.",
  diary3: "Ze zeggen dat endermen blokken meesjouwen omdat ze iets missen.\nDat ze er niet tegen kunnen om bekeken te worden, omdat het ze herinnert aan wie ze waren.",
  diary4: "Ik ga naar beneden.\nAls iemand dit leest: dood de draak. Kies daarna.\n— {ghost}",
  tomb: "Hier bleef\n{ghost}.\nHet was niet de draak.",
  ghostArrival: "je hebt het gehaald.",
  ghostCrystal: "ik deed er veel langer over.",
  ghostPerch: "nu. terwijl hij rust.",
  ghostVictory: "ga nog niet weg.",
  ghostGateway: "de poort. kom.",
  ghostNotYet: "nog niet.",
  ghostThanks: "bedankt dat je kwam.",
  chatJoined: "{ghost} kwam het spel binnen",
  chatLeft: "{ghost} verliet het spel",
  stayTitle: "Je bent gebleven.",
  staySubtitle: "Iemand zal erop drukken.",
  hintCamp: "Iemand heeft hier gekampeerd. Open de kist.",
  hintDig: "Graaf nooit recht naar beneden.",
  hintLectern: "Er staat iets geschreven op de lessenaar.",
  hintJump: "Spring in het portaal.",
  hintMeet: "Iemand wacht op je.",
  objChest: "Bekijk de kist",
  objSword: "Maak een zwaard",
  objEyes: "Maak Enderogen",
  objThrow: "Gooi een Enderoog",
  objDig: "Graaf naar beneden",
  objFrame: "Maak het portaalframe af",
  objJump: "Spring in het portaal",
  objDiary: "Lees het dagboek op de lessenaar",
  advStrike: "Ten aanval!",
  advGetaway: "Afgelegen vlucht",
  subChest: "Kist opent",
  subPage: "Pagina wordt omgeslagen",
  subBreak: "Blok wordt gebroken",
  subThrow: "Enderoog schiet",
  subShatter: "Enderoog breekt",
  subWhisper: "Iets fluistert",
  controlsTitle: "Besturing",
  paused: "Spel gepauzeerd",
  play: "Spelen",
  resume: "Terug naar het spel",
  leave: "Terug naar het paneel",
  ctrlMove: "WASD — bewegen",
  ctrlJump: "Spatie — springen (in de lucht met dekschild: zweven)",
  ctrlSneak: "Shift — sluipen",
  ctrlSprint: "Ctrl — sprinten",
  ctrlAttack: "Linkermuisknop — slaan / breken",
  ctrlUse: "Rechtermuisknop — gebruiken (ingedrukt houden: boog spannen, eten)",
  ctrlHotbar: "1-9 / scrollwiel — werkbalk",
  ctrlInventory: "E — inventaris",
  ctrlPause: "Esc — pauze",
  ctrlTouch: "Linkerduim: bewegen. Sleep rechts: rondkijken. Knoppen: slaan, gebruiken, springen, sluipen, sprinten, inventaris en pauze.",
  touchAttack: "Slaan",
  touchUse: "Gebruiken",
  touchJump: "Springen",
  touchPause: "Pauze",
  touchInventory: "Inventaris",
  touchSneak: "Sluipen",
  touchSprint: "Sprinten",
  chestBackups: "Kist: schat",
  inventoryHelp: "Linkerklik: stapel pakken of neerleggen. Rechterklik: de helft pakken of er één neerleggen. Shift + klik: naar de andere kant sturen. Sleep een stapel om hem te verdelen.",
  librarian: "Bibliothecaris",
  librarianHmm: "hmm. (de bibliothecaris kijkt je aan alsof hij iets weet)",
  soldOut: "Verkocht",
  mapLegend: "■ kamp · ▲ dorp · ◆ verwoest portaal · ? grot",
  mapNoSignal: "De kaart draait doelloos rond. Hij werkt alleen in de Overworld.",
  deathTitle: "Je bent doodgegaan!",
  deathScore: "Score:",
  respawn: "Respawnen",
  noise: "Lawaai",
  lastSeen: "{ghost} laatst gezien: {days} dagen geleden.",
  lastSeenToday: "{ghost} laatst gezien: vandaag.",
  villager: "Dorpeling",
  nitwit: "Onbenul",
  craftingTable: "Werkbank",
  lectern: "Lessenaar",
  portalGap: "Een ontbrekend obsidiaanblok",
  portalFrame: "Verwoest portaal",
  bed: "Bed",
  button: "Stenen knop",
  frame: "Endportaalframe",
  gateway: "Endtoegangsportaal",
  itemFrame: "Voorwerplijst",
  commandBlock: "Opdrachtblok",
  itemRod: "Blazestaf",
  itemArrow: "Pijl",
  itemEmerald: "Smaragd",
  itemMap: "Kaart",
  itemRegister: "Adminregister",
  itemFlint: "Vuursteen en staal",
  itemObsidian: "Obsidiaan",
  itemElytra: "Dekschild",
  itemGold: "Goudklompje",
  itemDirt: "Aarde",
  hintSword: "Maak een zwaard aan de werkbank.",
  hintObsidian: "Houd obsidiaan vast om het gat te vullen.",
  hintFlint: "Steek het aan met vuursteen en staal.",
  hintNotYet: "Nog niet. Je hebt nog blazestaven uit de Nether nodig.",
  hintEyeKnown: "Het oog heeft je de weg al gewezen.",
  hintEyes: "Terug naar de werkbank: staven tot poeder, poeder tot ogen.",
  hintThrowEye: "Gebruik een Enderoog (rechtermuisknop).",
  hintCrystalsBow: "Schiet met de boog op de kristallen: houd de rechtermuisknop ingedrukt en laat dan los.",
  hintNether: "De Nether. Het is hier heet.",
  hintFortress: "Het fort ligt aan de overkant van de lava. Blazes bewaken het.",
  hintRodsDone: "Drie staven. Ga terug door het portaal.",
  hintQuiet: "Sluip (Shift). Iets hier beneden luistert mee.",
  hintGatewayPearl: "Gooi een enderparel in het toegangsportaal.",
  hintNoPearl: "Geen parels meer. Endermen laten ze vallen.",
  hintElytra: "Spring naar beneden en druk in de lucht nog eens op springen om te zweven.",
  hintEndCity: "Een Endstad. Beklim de trap van de toren: de admin liet het dekschild op het schip achter.",
  hintFramesUse: "Gebruik de Enderogen op de lege frames.",
  hintFollowEye: "Het oog weet waar het portaal is. Volg het.",
  objRuined: "Steek het verwoeste portaal aan",
  objMap: "Haal de kaart van de bibliothecaris",
  objCave: "Wat zit er in de grot?",
  objQuiet: "Maak geen lawaai",
  objButton: "Druk op de knop",
  objRods: "Verzamel blazestaven",
  objReturn: "Ga terug door het portaal",
  objGhast: "Sla de vuurbal van de ghast terug",
  objGatewayPearl: "Of gooi je je parel in het toegangsportaal?",
  objElytra: "Vind het dekschild",
  objIslet: "Zweef naar het eilandje",
  ghostPortal: "ik had het bijna af. twee blokken tekort.",
  ghostBack: "nu de ogen. je weet waar de werkbank staat.",
  ghostBlaze: "blazes vergeven niet. ik ook niet, als iemand om OP vroeg.",
  ghostKeepInventory: "keepInventory staat aan. graag gedaan.",
  ghostShulker: "shulkers laten je gratis vliegen. de landing kost extra.",
  ghostBed: "ik had je gewaarschuwd.",
  ghostAncient: "dus jij hebt de stad ook gevonden.",
  voiceWill: "zal hij erop drukken?",
  voiceAlways: "dat doen ze altijd.",
  voiceAgain: "alweer.",
  voiceLearning: "laat hem. hij leert nog.",
  voiceNo: "nee.",
  voiceDone: "…nou, nu heb je het gedaan.",
  voiceAlmost: "bijna.",
  voiceChoose: "nu komt het moeilijkste: kiezen.",
  creeperDenied: "waarom gaat iedereen weg?",
  villagerHmm: "Dorpeling: hmm.",
  nitwitHmm: "Onbenul: hmm?",
  farmerHmm: "Boer: hmm. (hij wil 22 stokken voor één smaragd. jullie weten allebei dat het afzetterij is)",
  signIncidents: "Dagen sinds een\ncreeper mijn huis\nopblies:\n0",
  signRestart: "Binnenkort:\nmijn kasteel.",
  signBackups: "SCHAT.\nNIET AANKOMEN.\n—Bfuuny",
  signBorder: "Einde van de kaart.\nBudget op.\n—{ghost}",
  signToast: "Toast\n(we missen je)",
  signCave: "Nee.\n(echt niet)",
  signQuiet: "Stilte a.u.b.\nDe buurman beneden\nheeft geen ogen,\nmaar hoort ALLES.",
  signCasi: "bijna.\n—{ghost}",
  signBed: "Hier niet slapen.\n(op de harde manier geleerd)",
  signDiamond: "Hier ben ik\nde diamant kwijtgeraakt.\nZoek hem niet.\nDat heb ik al gedaan.",
  signUptime: "Ben over\n5 minuten terug.\n—{ghost}\n({days} dagen geleden)",
  diary5: "Ik ben afgedaald naar de stad beneden. Het frame daar is net als dit, alleen groter.\nIemand heeft het expres uitgeschakeld.",
  register1: "Adminregister\n\n~~Bfuuny~~ drukte op de knop. Twee keer.\n~~BlasterDaster~~ drukte op de knop.\n~~Ketbome~~ drukte op de knop.",
  registerLoop: "~~{ghost}~~ drukte op de knop.",
  register2: "Elke doorgestreepte naam is een admin die op de knop drukte en nooit terugkwam.\nWie streept ze door? De dorpelingen.\nhmm.",
  bookAdmin2011: "Logboek",
  bookAdmin2011By: "door BlasterDaster",
  admin2011a: "Als je het tot hier beneden hebt gehaald, ben je een van de nieuwsgierigen.\nDe eerste knop zat niet op een paneel. Hij zat hier.",
  admin2011b: "De portalen zijn ouder dan de servers. Wij zetten ze alleen aan.\nMaak geen lawaai. Hij luistert.\n— BlasterDaster",
  bookStop: "Opdrachtblok",
  stopBook: "Opdracht: /stop\n\n(nooit uitgevoerd)",
  deathLava: "zag lava aan voor een jacuzzi",
  deathVoid: "viel in de leegte. Valt nog steeds. Doet je de groeten.",
  deathFall: "probeerde de wateremmertruc. Zonder emmer.",
  deathBed: "ging slapen in de Nether. Het bed was het er niet mee eens.",
  deathWarden: "niesde in de oude stad. De Hoeder zei niet eens gezondheid.",
  deathEnderman: "keek een enderman in de ogen. De enderman keek terug.",
  deathBlaze: "vroeg aan een blaze of hij heet was. Dat was hij.",
  deathDragon: "werd gedood door de Enderdraak terwijl hij een screenshot maakte om op te scheppen",
  deathBreath: "rook aan drakenadem. Dat verdient niemand.",
  deathElytra: "knalde op volle snelheid tegen een muur. Met de muur gaat het prima.",
  deathShulker: "zweefde naar de hemel. Toen hield het zweven op.",
  deathSilverfish: "werd opgegeten door een zilvervis. Een zilvervis.",
  deathGhast: "werd retour afzender gestuurd",
  advDeeper: "We moeten dieper",
  advButton: "Wat doet deze knop?",
  advRods: "Door het vuur",
  advReturn: "Retour afzender",
  advSky: "Alles is mogelijk",
  subExplosion: "Explosie",
  subBow: "Boog schiet",
  subArrow: "Pijl raakt",
  subEat: "Eten",
  subHurtPlayer: "Speler raakt gewond",
  subVillager: "Dorpeling mompelt",
  subSheep: "Schaap blaat",
  subPig: "Varken knort",
  subHiss: "Creeper sist",
  subFlint: "Vuursteen en staal klikt",
  subFireball: "Vuurbal suist",
  subBlaze: "Blaze ademt",
  subGhast: "Ghast schreeuwt",
  subHeartbeat: "Hoederhartslag",
  subRoar: "Hoeder brult",
  subShriek: "Sculkkrijser krijst",
  subSculk: "Sculksensor begint te klikken",
  subSqueak: "Zilvervis sist",
  subZap: "Shulkerkogel",
  subLevitate: "Zweven",
  subNetherPortal: "Portaal opent",
  deathCreeper: "kreeg een knuffel van Kevin",
  creeperGranted: "ik wilde alleen maar een knuffel.",
  mobSlain: "werd gedood door {player}",
  pigDown: "ligt eruit. Alweer.",
  clickToPlay: "Klik om verder te spelen",
  noWebgl: "Je browser kan het spel niet in 3D tonen (WebGL2 ontbreekt). Zet hardwareversnelling aan in de instellingen, start hem opnieuw en probeer het nog eens. Hier is alvast het einde.",
  signBfuunyBed: "Prima plek\nom te slapen.\nVertrouw me.\n—Bfuuny",
  signBfuunyShip: "Het goede dekschild\nligt op het\nandere schip.\n—Bfuuny",
  signBfuunyExit: "UITGANG\n→\n—Bfuuny",
  bfuunyChest: "haha. het is aarde. allemaal.",
  bfuunyBed: "haha. ik zei: vertrouw me.",
  ghostWardenHit: "sla je hem nou? de Hoeder? dapper.",
  ghostWarden: "…oké. dat had nog nooit iemand gedaan.",
};

export default nl;
