import type { LoreKey } from './en';

const nl: Record<LoreKey, string> = {
  endTitle: 'The End',
  endSubtitle: 'Je bent in de End beland. Er was hier toch niets te vernietigen.',
  return: 'Terug naar de Overworld',
  advancement: 'Vooruitgang geboekt!',
  itemEgg: 'Drakenei',
  intro: "Testserver #47 van Ketbome. Status: bijna af.",
  endTagline: 'Of het begin?',
  goalReached: 'Doel bereikt!',
  advEyeSpy: 'Ik zie, ik zie',
  advEnterEnd: 'Het einde?',
  advFreeEnd: 'Bevrijd de End',
  advNextGen: 'De volgende generatie',
  chatAdvancement: '{player} heeft de vooruitgang geboekt',
  chatGoal: '{player} heeft het doel bereikt',
  player: 'Speler',
  bossName: 'Enderdraak',
  objectives: 'Doelen',
  objCrystals: 'Vernietig de Endkristallen',
  objDragon: 'Versla de Enderdraak',
  objEgg: 'Vang het drakenei',
  objPortal: 'Spring in het uitgangsportaal',
  hintHealing: 'De kristallen genezen hem. Breek ze eerst.',
  hintPerch: 'De draak hangt boven het portaal. Sla nu toe!',
  hintTakeoff: 'De draak stijgt op. In de lucht raken pijlen hem wel.',
  hintCharge: 'De draak duikt op je af. Stap opzij!',
  hintArrowsBounce: 'Zolang hij zit, ketsen pijlen af. Pak je zwaard.',
  hintEnraged: 'De draak is woedend!',
  hintEnderman: 'Kijk ze niet in de ogen.',
  hintEgg: 'Het ei is weggeteleporteerd. Probeer het opnieuw.',
  hintPortal: 'Het uitgangsportaal is open.',
  subEye: 'Enderoog geplaatst',
  subPortal: 'Endportaal opent',
  subTravel: 'Portaal zoemt',
  subLava: 'Lava borrelt',
  subGrowl: 'Enderdraak gromt',
  subHurt: 'Enderdraak gewond',
  subDeath: 'Enderdraak sterft',
  subCrystal: 'Endkristal ontploft',
  subEnderman: 'Enderman teleporteert',
  subEgg: 'Drakenei teleporteert',
  subXp: 'Ervaringsbol rinkelt',
  subGateway: 'Endpoort verschijnt',
  mute: 'Geluid uit',
  unmute: 'Geluid aan',
  skip: 'Overslaan',
  poem: "Ik zie de speler die je bedoelt.\n{player}?\nJa. Pas op. Hij heeft nu een hoger niveau bereikt. Hij kan onze gedachten lezen.\nDat maakt niet uit. Hij denkt dat wij deel van het spel zijn.\nIk mag deze speler. Hij speelde goed. Hij gaf niet op.\nHij kwam op een server die nooit af was. Hij speelde hem toch.\nHij houdt werelden draaiende voor anderen. Hij leest hun logs terwijl zij slapen.\nHij herstart wat kapotgaat. Hij bewaart wat ertoe doet. Hij heeft nooit om een bedankje gevraagd.\nEr waren er drie voor hem. Eén bouwde. Eén won. Eén ging steeds weer dood, en lachte elke keer.\nZe zijn er nog. Ze wachtten op hem.\nWaar droomde deze speler van?\nDeze speler droomde van zonlicht en bomen. Van vuur en water. Hij droomde dat hij schiep. En hij droomde dat hij vernietigde. Hij droomde dat hij jaagde, en werd opgejaagd. Hij droomde van beschutting.\nEn het universum zei: je bent niet alleen\nEn het universum zei: je bent niet gescheiden van al het andere\nEn het universum zei: jij bent het universum dat zichzelf proeft, tegen zichzelf praat, zijn eigen code leest\nEn het universum zei: ik hou van je, omdat jij liefde bent.\nEn het spel was voorbij en de speler ontwaakte uit de droom. En de speler begon een nieuwe droom. En de speler droomde opnieuw, droomde beter. En de speler was het universum. En de speler was liefde.\nJij bent de speler.\nWord wakker.",
  poemCredit: "Endgedicht van Julian Gough (CC0), ingekort. Vijf regels zijn voor Minepanel geschreven.",
  poemHint: 'Houd spatie of je vinger ingedrukt om te versnellen',
  itemNote: "Briefje",
  itemDiamond: "Diamant",
  itemStick: "Stok",
  itemPearl: "Enderparel",
  itemBlaze: "Blazepoeder",
  itemBow: "Boog",
  itemApple: "Gouden appel",
  itemSword: "Diamanten zwaard",
  itemEye: "Enderoog",
  chest: "Kist",
  crafting: "Vervaardiging",
  inventory: "Inventaris",
  takeAll: "Alles pakken",
  recipeBook: "Receptenboek",
  craftHelp: "Leg voorwerpen op het rooster en pak het resultaat. Shift + klik op het resultaat maakt alles wat het rooster toelaat. Het receptenboek legt één set klaar (Shift: zoveel als je kunt).",
  emptySlot: "Leeg vak",
  close: "Sluiten",
  page: "Pagina {n} van {total}",
  prevPage: "Vorige pagina",
  nextPage: "Volgende pagina",
  diaryTitle: "Dagboek",
  diaryBy: "door {ghost}",
  sign: "Bord",
  note: "Server #47. Deze maak ik af, beloofd.\nIk heb je achtergelaten wat ik had, in de kist. De werkbank staat er nog.\nVertrouw Bfuuny's kisten niet. Race niet tegen BlasterDaster. Je verliest.\nHoud één parel. Je zult het begrijpen.\n— {ghost}",
  diary1: "Server #47, dag 1. Het kamp staat. Hierna het kasteel.\n(het kasteel kwam nooit)",
  diary2: "Dag 3. Het portaal had al drie ogen.\nBlasterDaster was er natuurlijk eerst. Hij liet een bord achter: \"te langzaam\".",
  diary3: "Endermen blijven mijn blokken stelen. Ik denk dat zij ook iets bouwen.\nWaarschijnlijk beter dan ik.",
  diary4: "Ik ga naar het End om de definitieve server te bouwen.\nVersla de draak en neem daarna de gateway. We wachten.\n— {ghost}",
  tomb: "Hier ligt Bfuuny.\nAlweer.\n(dood #312: hij zwaaide naar de draak)",
  ghostArrival: "je hebt het gehaald.",
  ghostCrystal: "ik deed er veel langer over.",
  ghostPerch: "nu. terwijl hij rust.",
  ghostVictory: "ga nog niet weg.",
  ghostGateway: "de gateway. daar wachten we allemaal. neem een parel mee.",
  ghostNotYet: "die enderman bewaakt bfuuny's graf. iemand moet het doen.",
  ghostThanks: "bedankt dat je Minepanel gebruikt. echt. we zijn met z'n drieën en veel koffie.",
  chatJoined: "{ghost} kwam het spel binnen",
  chatLeft: "{ghost} verliet het spel",
  stayTitle: "GG",
  staySubtitle: "Bfuuny is alweer dood.",
  hintCamp: "Iemand heeft hier gekampeerd. Open de kist.",
  hintDig: "Graaf nooit recht naar beneden.",
  hintLectern: "Er staat iets geschreven op de lessenaar.",
  hintJump: "Spring in het portaal.",
  hintMeet: "Zweef naar het eilandje. Ze wachten op je.",
  objChest: "Bekijk de kist",
  objSword: "Maak een zwaard",
  objEyes: "Maak Enderogen",
  objThrow: "Gooi een Enderoog",
  objDig: "Graaf naar beneden",
  objFrame: "Maak het portaalframe af",
  objJump: "Spring in het portaal",
  objDiary: "Lees het dagboek op de lessenaar",
  advStrike: "Ten aanval!",
  advGetaway: "Afgelegen vlucht",
  subChest: "Kist opent",
  subPage: "Pagina wordt omgeslagen",
  subBreak: "Blok wordt gebroken",
  subThrow: "Enderoog schiet",
  subShatter: "Enderoog breekt",
  subWhisper: "Iets fluistert",
  controlsTitle: "Besturing",
  paused: "Spel gepauzeerd",
  play: "Spelen",
  resume: "Terug naar het spel",
  leave: "Terug naar het paneel",
  ctrlMove: "WASD — bewegen",
  ctrlJump: "Spatie — springen (in de lucht met dekschild: zweven)",
  ctrlSneak: "Shift — sluipen",
  ctrlSprint: "Ctrl — sprinten",
  ctrlAttack: "Linkermuisknop — slaan / breken",
  ctrlUse: "Rechtermuisknop — gebruiken, blok plaatsen (ingedrukt houden: boog spannen, eten)",
  ctrlHotbar: "1-9 / scrollwiel — werkbalk",
  ctrlInventory: "E — inventaris",
  ctrlPause: "Esc — pauze",
  ctrlTouch: "Linkerduim: bewegen. Sleep rechts: rondkijken. Knoppen: slaan, gebruiken, springen, sluipen, sprinten, inventaris en pauze.",
  touchAttack: "Slaan",
  touchUse: "Gebruiken",
  touchJump: "Springen",
  touchPause: "Pauze",
  touchInventory: "Inventaris",
  touchSneak: "Sluipen",
  touchSprint: "Sprinten",
  chestBackups: "Kist: schat",
  inventoryHelp: "Linkerklik: stapel pakken of neerleggen. Rechterklik: de helft pakken of er één neerleggen. Shift + klik: naar de andere kant sturen. Sleep een stapel om hem te verdelen.",
  librarian: "Bibliothecaris",
  librarianHmm: "hmm. (de bibliothecaris kijkt je aan alsof hij iets weet)",
  soldOut: "Verkocht",
  mapLegend: "■ kamp · ▲ dorp · ◆ verwoest portaal · ? grot",
  mapNoSignal: "De kaart draait doelloos rond. Hij werkt alleen in de Overworld.",
  deathTitle: "Je bent doodgegaan!",
  deathScore: "Score:",
  respawn: "Respawnen",
  noise: "Lawaai",
  lastSeen: "{ghost} laatst gezien: {days} dagen geleden.",
  lastSeenToday: "{ghost} laatst gezien: vandaag.",
  villager: "Dorpeling",
  nitwit: "Onbenul",
  craftingTable: "Werkbank",
  lectern: "Lessenaar",
  portalGap: "Een ontbrekend obsidiaanblok",
  portalFrame: "Verwoest portaal",
  bed: "Bed",
  button: "Stenen knop",
  frame: "Endportaalframe",
  gateway: "Endtoegangsportaal",
  itemFrame: "Voorwerplijst",
  commandBlock: "Opdrachtblok",
  itemRod: "Blazestaf",
  itemArrow: "Pijl",
  itemEmerald: "Smaragd",
  itemMap: "Kaart",
  itemRegister: "Bfuuny's doodsregister",
  itemFlint: "Vuursteen en staal",
  itemObsidian: "Obsidiaan",
  itemElytra: "Dekschild",
  itemGold: "Goudstaaf",
  itemDirt: "Aarde",
  hintSword: "Maak een zwaard aan de werkbank.",
  hintObsidian: "Houd obsidiaan vast om het gat te vullen.",
  hintFlint: "Steek het aan met vuursteen en staal.",
  hintNotYet: "Nog niet. Je hebt nog blazestaven uit de Nether nodig.",
  hintEyeKnown: "Het oog heeft je de weg al gewezen.",
  hintEyes: "Terug naar de werkbank: staven tot poeder, poeder tot ogen.",
  hintThrowEye: "Gebruik een Enderoog (rechtermuisknop).",
  hintCrystalsBow: "Schiet met de boog op de kristallen: houd de rechtermuisknop ingedrukt en laat dan los.",
  hintNether: "De Nether. Het is hier heet.",
  hintFortress: "Het fort ligt aan de overkant van de lava. Blazes bewaken het.",
  hintRodsDone: "Drie staven. Ga terug door het portaal.",
  hintQuiet: "Sluip (Shift). Iets hier beneden luistert mee.",
  hintGatewayPearl: "Gooi een enderparel in het toegangsportaal.",
  hintNoPearl: "Geen parels meer. Endermen laten ze vallen.",
  hintElytra: "Spring naar beneden en druk in de lucht nog eens op springen om te zweven.",
  hintEndCity: "Een Endstad. Beklim de trap van de toren: de admin liet het dekschild op het schip achter.",
  hintFramesUse: "Gebruik de Enderogen op de lege frames.",
  hintFollowEye: "Het oog weet waar het portaal is. Volg het.",
  objRuined: "Steek het verwoeste portaal aan",
  objMap: "Haal de kaart van de bibliothecaris",
  objCave: "Wat zit er in de grot?",
  objQuiet: "Maak geen lawaai",
  objButton: "Druk op de knop",
  objRods: "Verzamel blazestaven",
  objReturn: "Ga terug door het portaal",
  objGhast: "Sla de vuurbal van de ghast terug",
  objGatewayPearl: "Of gooi je je parel in het toegangsportaal?",
  objElytra: "Vind het dekschild",
  objIslet: "Zweef naar het eilandje",
  ghostPortal: "ik had het bijna af. twee blokken tekort.",
  ghostBack: "nu de ogen. je weet waar de werkbank staat.",
  ghostBlaze: "blazes vergeven niet. ik ook niet, als iemand om OP vroeg.",
  ghostKeepInventory: "keepInventory staat aan. graag gedaan.",
  ghostShulker: "shulkers laten je gratis vliegen. de landing kost extra.",
  ghostBed: "ik had je gewaarschuwd.",
  ghostAncient: "dus jij hebt de stad ook gevonden.",
  creeperDenied: "waarom gaat iedereen weg?",
  villagerHmm: "Dorpeling: hmm.",
  nitwitHmm: "Onbenul: hmm?",
  farmerHmm: "Boer: hmm. (hij wil 22 stokken voor één smaragd. jullie weten allebei dat het afzetterij is)",
  signIncidents: "Dagen sinds een\ncreeper mijn huis\nopblies:\n0",
  signRestart: "Binnenkort:\nmijn kasteel.",
  signBackups: "SCHAT.\nNIET AANKOMEN.\n—Bfuuny",
  signBorder: "Einde van de kaart.\nBudget op.\n—{ghost}",
  signToast: "Toast\n(we missen je)",
  signCave: "Nee.\n(echt niet)",
  signQuiet: "Stilte a.u.b.\nDe buurman beneden\nheeft geen ogen,\nmaar hoort ALLES.",
  signCasi: "bijna.\n—{ghost}",
  signBed: "Hier niet slapen.\n(op de harde manier geleerd)",
  signDiamond: "Hier ben ik\nde diamant kwijtgeraakt.\nZoek hem niet.\nDat heb ik al gedaan.",
  signUptime: "Ben over\n5 minuten terug.\n—{ghost}\n({days} dagen geleden)",
  diary5: "Ik ben naar de oude stad afgedaald. BlasterDaster zegt dat hij de Warden met een houten zwaard heeft verslagen.\nIk geloof hem niet. Een beetje wel.",
  register1: "Bfuuny's doodsregister\n\n#1 van de spawn gevallen.\n#2 van de spawn gevallen. Alweer.\n#58 in de Nether geslapen. \"het is gezellig\".\n#128 Kevin geknuffeld.\n#311 \"ik kijk alleen hoe heet de lava is\".",
  register2: "Pagina's 3 tot 40: meer van hetzelfde.\nDe dorpelingen houden de telling bij. Ze lijken ervan te genieten.\nhmm.",
  bookAdmin2011: "Pro-gids",
  bookAdmin2011By: "door BlasterDaster",
  admin2011a: "BlasterDasters pro-gids, deel 1:\nSluip. Niet sprinten. Niet springen. Niet hard ademen.\nHoor je een hartslag die niet de jouwe is: skill issue.",
  admin2011b: "Deel 2: schiet een pijl ergens anders heen. Hij gaat altijd kijken.\nTwee keer verslagen. Bfuuny ging vier keer dood terwijl hij keek.\nPS: druk niet op de knop bij het frame. Dit keer geen grap.\n— BlasterDaster",
  bookStop: "Opdrachtblok",
  stopBook: "Opdracht: /stop\n\n(nooit uitgevoerd)",
  deathLava: "zag lava aan voor een jacuzzi",
  deathVoid: "viel in de leegte. Valt nog steeds. Doet je de groeten.",
  deathFall: "probeerde de wateremmertruc. Zonder emmer.",
  deathBed: "ging slapen in de Nether. Het bed was het er niet mee eens.",
  deathWarden: "niesde in de oude stad. De Hoeder zei niet eens gezondheid.",
  deathEnderman: "keek een enderman in de ogen. De enderman keek terug.",
  deathBlaze: "vroeg aan een blaze of hij heet was. Dat was hij.",
  deathDragon: "werd gedood door de Enderdraak terwijl hij een screenshot maakte om op te scheppen",
  deathBreath: "rook aan drakenadem. Dat verdient niemand.",
  deathElytra: "knalde op volle snelheid tegen een muur. Met de muur gaat het prima.",
  deathShulker: "zweefde naar de hemel. Toen hield het zweven op.",
  deathSilverfish: "werd opgegeten door een zilvervis. Een zilvervis.",
  deathGhast: "werd retour afzender gestuurd",
  advDeeper: "We moeten dieper",
  advButton: "Wat doet deze knop?",
  advRods: "Door het vuur",
  advReturn: "Retour afzender",
  advSky: "Alles is mogelijk",
  subExplosion: "Explosie",
  subBow: "Boog schiet",
  subArrow: "Pijl raakt",
  subEat: "Eten",
  subHurtPlayer: "Speler raakt gewond",
  subVillager: "Dorpeling mompelt",
  subSheep: "Schaap blaat",
  subPig: "Varken knort",
  subHiss: "Creeper sist",
  subFlint: "Vuursteen en staal klikt",
  subFireball: "Vuurbal suist",
  subBlaze: "Blaze ademt",
  subGhast: "Ghast schreeuwt",
  subHeartbeat: "Hoederhartslag",
  subRoar: "Hoeder brult",
  subShriek: "Sculkkrijser krijst",
  subSculk: "Sculksensor begint te klikken",
  subSqueak: "Zilvervis sist",
  subZap: "Shulkerkogel",
  subLevitate: "Zweven",
  subNetherPortal: "Portaal opent",
  deathCreeper: "kreeg een knuffel van Kevin",
  creeperGranted: "ik wilde alleen maar een knuffel.",
  mobSlain: "werd gedood door {player}",
  pigDown: "ligt eruit. Alweer.",
  clickToPlay: "Klik om verder te spelen",
  noWebgl: "Je browser kan het spel niet in 3D tonen (WebGL2 ontbreekt). Zet hardwareversnelling aan in de instellingen, start hem opnieuw en probeer het nog eens. Hier is alvast het einde.",
  signBfuunyBed: "Prima plek\nom te slapen.\nVertrouw me.\n—Bfuuny",
  signBfuunyShip: "Het goede dekschild\nligt op het\nandere schip.\n—Bfuuny",
  signBfuunyExit: "UITGANG\n→\n—Bfuuny",
  bfuunyChest: "haha. het is aarde. allemaal.",
  bfuunyBed: "haha. ik zei: vertrouw me.",
  ghostWardenHit: "sla je hem nou? de Hoeder? dapper.",
  ghostWarden: "…oké. dat had nog nooit iemand gedaan.",
  itemLog: "Eikenstam",
  itemPlanks: "Eikenhouten planken",
  itemCobble: "Keien",
  itemNetherrack: "Netherrack",
  itemEndStone: "Endsteen",
  itemPickaxe: "Diamanten houweel",
  itemHelmet: "Gouden helm",
  piglin: "Piglin",
  armor: "Harnas",
  armorSlot: "Helm",
  hintPiglin: "Houd een goudstaaf vast en klik met rechts op een piglin om te ruilen.",
  hintHelmet: "Zet de gouden helm op (rechtsklik ermee). Piglins vertrouwen alleen goud.",
  hintPearlsLeft: "Drie staven. Je mist nog enderparels: de piglins ruilen ze voor goud.",
  objPearls: "Ruil enderparels bij de piglins",
  ghostPiglin: "piglins. geen goud op je hoofd, geen vrienden.",
  ghostDarkness: "de lichten zijn uit. dat is nooit een goed teken.",
  deathSkeleton: "werd neergeschoten door een skelet. Het heeft geen ogen. Het had ze niet nodig.",
  deathPiglin: "kwam zonder goud. De piglins namen het persoonlijk.",
  subEquip: "Uitrusting aangetrokken",
  subPiglin: "Piglin snuift",
  subSkeleton: "Skelet rammelt",
  bfuunyDirt: "zie je? ik zei toch dat het een schat was.",
  introBlaster: "nieuwe speler. 20 dat Kevin hem als eerste pakt.",
  introBfuuny: "deal. ik verloor gisteren 20 aan Kevin.",
  respawnBfuuny: "welkom bij de club. we hebben jassen.",
  respawnBlaster: "skill issue.",
  buttonBfuuny: "eh. wie heeft 'The Rake' uitgenodigd?",
  buttonBlaster: "ik zei niet drukken. hoor je iets ademen achter je, draai je dan NIET om.",
  victoryKetbome: "gg! het uitgangsportaal brengt je naar huis.",
  victoryBlaster: "of gooi een parel in de gateway. daar zijn wij.",
  endKetbome1: "je hebt het gehaald! welkom op de definitieve server.",
  endKetbome2: "hij is... bijna af.",
  endBlaster: "gg. helemaal niet slecht.",
  endBfuuny: "kijk dit, die sprong haal ik makkelijk",
  endBlaster2: "elke. keer. weer.",
  endStar: "vind je het leuk: een ster op GitHub, een bijdrage of het delen op sociale media helpt meer dan je denkt.",
  endBfuunyBack: "ik ben terug. wat heb ik gemist?",
  bfuunyDiedKevin: "werd opgeblazen door Kevin. Hij wilde een knuffel.",
  bfuunyDiedPiglin: "werd gedood door een piglin. Hij was de helm vergeten.",
  bfuunyDiedWarden: "werd uitgewist door een sonisch geladen krijs",
  bfuunyDiedVoid: "viel uit de wereld. Alweer.",
  signBlasterSlow: "te langzaam.\n—BlasterDaster",
  signBlasterRods: "Blazestaven: 3/3\nin 40 seconden.\n—BlasterDaster",
  signBfuunyGrave: "R.I.P. Bfuuny\n(hij is oké)\n(hij komt terug)",
  signServer48: "Server #48\nBinnenkort.\n—Ketbome",
  deathRake: "kwam The Rake tegen. Het wilde niet praten.",
  subRake: "Iets krijst",
  rakeBfuuny: "zag iemand anders dat ook???",
  rakeBlaster: "zei ik toch. de knop.",
  thanksTitle: "Bedankt voor het spelen",
  thanksBody: "Minepanel wordt door een paar mensen in hun vrije tijd gemaakt, en het gebruiken helpt al.\nVind je het leuk, dan helpen een ster op GitHub, een bijdrage of delen op sociale media om meer mensen te bereiken.",
  thanksStar: "Ster op GitHub",
  thanksClose: "Terug naar het paneel",
  subBreath: "Iets ademt achter je",
};

export default nl;
