import type { LoreKey } from './en';

const pl: Record<LoreKey, string> = {
  endTitle: 'Kres',
  endSubtitle: 'Trafiłeś do Kresu. W końcu nie było tu nic do zniszczenia.',
  return: 'Powrót do Świata Powierzchni',
  advancement: 'Postęp osiągnięty!',
  itemEgg: 'Smocze jajo',
  intro: 'Mówiono ci, żebyś tego nie naciskał.',
  endTagline: 'Czy może początek?',
  goalReached: 'Cel osiągnięty!',
  advEyeSpy: 'Szpiegowskie oko',
  advEnterEnd: 'Kres?',
  advFreeEnd: 'Uwolnij Kres',
  advNextGen: 'Następne pokolenie',
  chatAdvancement: '{player} osiągnął postęp',
  chatGoal: '{player} osiągnął cel',
  player: 'Gracz',
  bossName: 'Smok Kresu',
  objectives: 'Cele',
  objCrystals: 'Zniszcz kryształy Kresu',
  objDragon: 'Pokonaj Smoka Kresu',
  objEgg: 'Złap smocze jajo',
  objPortal: 'Wskocz do portalu powrotnego',
  hintHealing: 'Kryształy go leczą. Najpierw je rozbij.',
  hintPerch: 'Smok unosi się nad portalem. Uderzaj teraz!',
  hintEnderman: 'Nie patrz im w oczy.',
  hintEgg: 'Jajo się teleportowało. Spróbuj ponownie.',
  hintPortal: 'Portal powrotny jest otwarty.',
  subEye: 'Oko Kresu umieszczone',
  subPortal: 'Portal Kresu się otwiera',
  subTravel: 'Portal szumi',
  subLava: 'Lawa bulgocze',
  subGrowl: 'Smok Kresu warczy',
  subHurt: 'Smok Kresu zraniony',
  subDeath: 'Smok Kresu umiera',
  subCrystal: 'Kryształ Kresu wybucha',
  subEnderman: 'Enderman się teleportuje',
  subEgg: 'Smocze jajo się teleportuje',
  subXp: 'Kula doświadczenia dzwoni',
  subGateway: 'Pojawia się brama Kresu',
  mute: 'Wycisz dźwięk',
  unmute: 'Włącz dźwięk',
  skip: 'Pomiń',
  poem: 'Widzę gracza, o którym mówisz.\n{player}?\nTak. Uważaj. Osiągnął teraz wyższy poziom. Potrafi czytać nasze myśli.\nTo nie ma znaczenia. Myśli, że jesteśmy częścią gry.\nLubię tego gracza. Grał dobrze. Nie poddał się.\nPowiedziano mu, żeby nie naciskał przycisku.\nI tak go nacisnął. Zawsze to robią. Tak nas znajdują.\nUtrzymuje światy innych przy życiu. Czyta ich logi, kiedy śpią.\nUruchamia ponownie to, co się psuje. Chroni to, co ważne. Nigdy nie prosił o podziękowania.\nBył już jeden przed nim. On też grał dobrze. Został.\nTen się obudzi.\nO czym śnił ten gracz?\nTen gracz śnił o słońcu i drzewach. O ogniu i wodzie. Śnił, że tworzy. I śnił, że niszczy. Śnił, że poluje i że na niego polują. Śnił o schronieniu.\nA wszechświat powiedział: nie jesteś sam\nA wszechświat powiedział: nie jesteś oddzielony od wszystkiego innego\nA wszechświat powiedział: jesteś wszechświatem, który sam siebie smakuje, sam do siebie mówi, czyta własny kod\nA wszechświat powiedział: kocham cię, bo jesteś miłością.\nI gra się skończyła, a gracz obudził się ze snu. I gracz zaczął nowy sen. I gracz znów śnił, śnił lepiej. I gracz był wszechświatem. I gracz był miłością.\nTy jesteś graczem.\nObudź się.',
  poemCredit: "Poemat Kresu autorstwa Juliana Gougha (CC0), skrócony. Sześć wersów napisano dla Minepanel.",
  poemHint: 'Przytrzymaj spację lub palec, aby przyspieszyć',
  itemNote: "Liścik",
  itemDiamond: "Diament",
  itemStick: "Patyk",
  itemPearl: "Enderperła",
  itemBlaze: "Płomienny proszek",
  itemBow: "Łuk",
  itemApple: "Złote jabłko",
  itemSword: "Diamentowy miecz",
  itemEye: "Oko Endera",
  chest: "Skrzynia",
  crafting: "Wytwarzanie",
  inventory: "Ekwipunek",
  takeAll: "Weź wszystko",
  recipeBook: "Księga receptur",
  craftHelp: "Połóż przedmioty na siatce i weź wynik. Shift + klik na wyniku tworzy wszystko, na co pozwala siatka. Księga receptur układa jeden zestaw (Shift: tyle, ile się da).",
  emptySlot: "Pusty slot",
  close: "Zamknij",
  page: "Strona {n} z {total}",
  prevPage: "Poprzednia strona",
  nextPage: "Następna strona",
  diaryTitle: "Dziennik",
  diaryBy: "autorstwa {ghost}",
  sign: "Tabliczka",
  note: "Dla tego, kto przyjdzie po mnie.\nWiadomo było, że go naciśniesz. Wszyscy to robimy.\nZostawiam ci to, co mi zostało. Stół wciąż tam jest.\nZachowaj jedną perłę. Zrozumiesz.\n— {ghost}",
  diary1: "Od lat utrzymuję ten serwer przy życiu. Uruchamiam ponownie to, co się psuje. Nikt nigdy nie poznał mojego imienia.\nDziś w nocy naciskam przycisk.",
  diary2: "W portalu tkwiły już trzy oczy.\nNie zaczęło się ode mnie. Ktoś był tu przede mną, a jeszcze wcześniej ktoś inny.",
  diary3: "Mówią, że endermany noszą bloki, bo za czymś tęsknią.\nŻe nie znoszą, gdy ktoś na nie patrzy, bo przypomina im to, kim były.",
  diary4: "Schodzę na dół.\nJeśli ktoś to czyta: zabij smoka. Potem wybierz.\n— {ghost}",
  tomb: "Tu pozostaje\n{ghost}.\nTo nie był smok.",
  ghostArrival: "udało ci się.",
  ghostCrystal: "mnie zajęło to dużo dłużej.",
  ghostPerch: "teraz. póki odpoczywa.",
  ghostVictory: "nie odchodź jeszcze.",
  ghostGateway: "brama. chodź.",
  ghostNotYet: "jeszcze nie.",
  ghostThanks: "dziękuję, że tu jesteś.",
  chatJoined: "Gracz {ghost} dołączył do gry",
  chatLeft: "Gracz {ghost} opuścił grę",
  stayTitle: "Zostajesz.",
  staySubtitle: "Ktoś go naciśnie.",
  hintCamp: "Ktoś tu obozował. Otwórz skrzynię.",
  hintDig: "Nigdy nie kop prosto w dół.",
  hintLectern: "Na pulpicie coś napisano.",
  hintJump: "Wskocz do portalu.",
  hintMeet: "Ktoś na ciebie czeka.",
  objChest: "Sprawdź skrzynię",
  objSword: "Wytwórz miecz",
  objEyes: "Wytwórz oczy Endera",
  objThrow: "Rzuć okiem Endera",
  objDig: "Kop w dół",
  objFrame: "Uzupełnij ramę portalu",
  objJump: "Wskocz do portalu",
  objDiary: "Przeczytaj dziennik na pulpicie",
  advStrike: "Do ataku!",
  advGetaway: "Ucieczka z wyspy",
  subChest: "Skrzynia się otwiera",
  subPage: "Kartka się przewraca",
  subBreak: "Zniszczono blok",
  subThrow: "Rzut okiem Endera",
  subShatter: "Oko Endera pęka",
  subWhisper: "Coś szepcze",
  controlsTitle: "Sterowanie",
  paused: "Gra wstrzymana",
  play: "Graj",
  resume: "Powrót do gry",
  leave: "Wyjdź do panelu",
  ctrlMove: "WASD — ruch",
  ctrlJump: "Spacja — skok (w powietrzu z elytrami: szybowanie)",
  ctrlSneak: "Shift — skradanie się",
  ctrlSprint: "Ctrl — bieg",
  ctrlAttack: "LPM — uderzenie / kopanie",
  ctrlUse: "PPM — użycie (przytrzymaj: napięcie łuku, jedzenie)",
  ctrlHotbar: "1-9 / kółko myszy — pasek szybkiego wyboru",
  ctrlInventory: "E — ekwipunek",
  ctrlPause: "Esc — pauza",
  ctrlTouch: "Lewy kciuk: ruch. Przeciągnij po prawej: rozglądanie się. Przyciski: uderzenie, użycie, skok, skradanie się, bieg, ekwipunek i pauza.",
  touchAttack: "Uderz",
  touchUse: "Użyj",
  touchJump: "Skok",
  touchPause: "Pauza",
  touchInventory: "Ekwipunek",
  touchSneak: "Skradanie",
  touchSprint: "Bieg",
  chestBackups: "Skrzynia: skarb",
  inventoryHelp: "LPM: weź lub odłóż stos. PPM: weź połowę lub odłóż jeden. Shift + klik: przenieś na drugą stronę. Przeciągnij trzymany stos, aby go rozdzielić.",
  librarian: "Bibliotekarz",
  librarianHmm: "hmm. (bibliotekarz patrzy na ciebie, jakby coś wiedział)",
  soldOut: "Sprzedane",
  mapLegend: "■ obóz · ▲ wioska · ◆ zrujnowany portal · ? jaskinia",
  mapNoSignal: "Mapa kręci się bez celu. Działa tylko w Świecie Powierzchni.",
  deathTitle: "Nie żyjesz!",
  deathScore: "Wynik:",
  respawn: "Odrodzenie",
  noise: "Hałas",
  lastSeen: "Dni od ostatniego logowania {ghost}: {days}.",
  lastSeenToday: "Ostatnie logowanie {ghost}: dzisiaj.",
  villager: "Osadnik",
  nitwit: "Głupiec",
  craftingTable: "Stół rzemieślniczy",
  lectern: "Pulpit",
  portalGap: "Brakujący blok obsydianu",
  portalFrame: "Zrujnowany portal",
  bed: "Łóżko",
  button: "Kamienny przycisk",
  frame: "Rama portalu Kresu",
  gateway: "Brama Kresu",
  itemFrame: "Ramka na przedmiot",
  commandBlock: "Blok poleceń",
  itemRod: "Płomienna różdżka",
  itemArrow: "Strzała",
  itemEmerald: "Szmaragd",
  itemMap: "Mapa",
  itemRegister: "Rejestr adminów",
  itemFlint: "Krzesiwo",
  itemObsidian: "Obsydian",
  itemElytra: "Elytry",
  itemGold: "Bryłka złota",
  itemDirt: "Ziemia",
  hintSword: "Wytwórz miecz na stole rzemieślniczym.",
  hintObsidian: "Weź obsydian do ręki, aby wypełnić lukę.",
  hintFlint: "Podpal go krzesiwem.",
  hintNotYet: "Jeszcze nie. Brakuje ci płomiennych różdżek z Netheru.",
  hintEyeKnown: "Oko już wskazało ci drogę.",
  hintEyes: "Wróć do stołu: różdżki w proszek, proszek w oczy.",
  hintThrowEye: "Użyj oka Endera (PPM).",
  hintCrystalsBow: "Strzelaj z łuku do kryształów: przytrzymaj PPM, potem puść.",
  hintNether: "Nether. Gorąco tu.",
  hintFortress: "Forteca jest po drugiej stronie lawy. Pilnują jej płomyki.",
  hintRodsDone: "Trzy różdżki. Wracaj przez portal.",
  hintQuiet: "Skradaj się (Shift). Coś tu na dole nasłuchuje.",
  hintGatewayPearl: "Rzuć enderperłę w bramę.",
  hintNoPearl: "Nie masz już pereł. Endermany je upuszczają.",
  hintElytra: "Skocz w dół i w powietrzu naciśnij skok jeszcze raz, aby szybować.",
  hintEndCity: "Miasto Kresu. Wejdź po schodach wieży: admin zostawił elytry na statku.",
  hintFramesUse: "Użyj oczu Endera na pustych ramach.",
  hintFollowEye: "Oko wie, gdzie jest portal. Idź za nim.",
  objRuined: "Zapal zrujnowany portal",
  objMap: "Zdobądź mapę bibliotekarza",
  objCave: "Co jest w jaskini?",
  objQuiet: "Nie hałasuj",
  objButton: "Naciśnij przycisk",
  objRods: "Zdobądź płomienne różdżki",
  objReturn: "Wróć przez portal",
  objGhast: "Odbij kulę ognia ghasta",
  objGatewayPearl: "A może rzucić perłę w bramę?",
  objElytra: "Znajdź elytry",
  objIslet: "Doszybuj do wysepki",
  ghostPortal: "prawie się udało. zabrakło dwóch bloków.",
  ghostBack: "teraz oczy. wiesz, gdzie jest stół.",
  ghostBlaze: "płomyki nie wybaczają. ja też nie, gdy ktoś prosił o OP.",
  ghostKeepInventory: "keepInventory włączone. nie ma za co.",
  ghostShulker: "shulkery dają darmowy lot. za lądowanie płaci się osobno.",
  ghostBed: "przecież było napisane.",
  ghostAncient: "czyli miasto też już znasz.",
  voiceWill: "czy go naciśnie?",
  voiceAlways: "zawsze to robią.",
  voiceAgain: "znowu.",
  voiceLearning: "zostaw go. on się uczy.",
  voiceNo: "nie.",
  voiceDone: "…no i stało się.",
  voiceAlmost: "już prawie.",
  voiceChoose: "teraz najtrudniejsze: wybór.",
  creeperDenied: "czemu wszyscy uciekają?",
  villagerHmm: "Osadnik: hmm.",
  nitwitHmm: "Głupiec: hmm?",
  farmerHmm: "Rolnik: hmm. (chce 22 patyki za jeden szmaragd. dobrze wiecie, że to rozbój w biały dzień)",
  signIncidents: "Dni od ostatniego\nwysadzenia domu\nprzez creepera:\n0",
  signRestart: "Wkrótce:\nmój zamek.",
  signBackups: "SKARB.\nNIE RUSZAĆ.\n—Bfuuny",
  signBorder: "Koniec mapy.\nBudżet się skończył.\n—{ghost}",
  signToast: "Toast\n(tęsknimy)",
  signCave: "Nie.\n(serio)",
  signQuiet: "Cisza, proszę.\nSąsiad z dołu\nnie ma oczu,\nale słyszy WSZYSTKO.",
  signCasi: "prawie.\n—{ghost}",
  signBed: "Nie spać tutaj.\n(sprawdzone na sobie)",
  signDiamond: "Tu przepadł\ndiament.\nNie szukaj go.\nWszystko już przekopane.",
  signUptime: "Wracam za\n5 minut.\n—{ghost}\n({days} dni temu)",
  diary5: "Jestem w mieście na dole. Jego rama jest taka sama jak ta, tylko większa.\nKtoś celowo ją wyłączył.",
  register1: "Rejestr adminów\n\n~~Bfuuny~~: przycisk naciśnięty. Dwa razy.\n~~BlasterDaster~~: przycisk naciśnięty.\n~~Ketbome~~: przycisk naciśnięty.",
  registerLoop: "~~{ghost}~~: przycisk naciśnięty.",
  register2: "Każde skreślone imię to admin, który nacisnął przycisk i nigdy nie wrócił.\nKto je skreśla? Osadnicy.\nhmm.",
  bookAdmin2011: "Notatki",
  bookAdmin2011By: "autorstwa BlasterDaster",
  admin2011a: "Skoro tu jesteś, należysz do ciekawskich.\nPierwszy przycisk nie był na żadnym panelu. Był tutaj.",
  admin2011b: "Portale są starsze niż serwery. My je tylko włączamy.\nNie hałasuj. On słucha.\n— BlasterDaster",
  bookStop: "Blok poleceń",
  stopBook: "Polecenie: /stop\n\n(nigdy nie wykonane)",
  deathLava: "pomylił lawę z jacuzzi",
  deathVoid: "wpadł w pustkę. Nadal spada. Pozdrawia.",
  deathFall: "próbował sztuczki z wiadrem wody. Bez wiadra.",
  deathBed: "położył się spać w Netherze. Łóżko miało inne zdanie.",
  deathWarden: "kichnął w starożytnym mieście. Nadzorca nie powiedział „na zdrowie”.",
  deathEnderman: "spojrzał endermanowi w oczy. Enderman odwzajemnił spojrzenie.",
  deathBlaze: "zapytał płomyka, czy parzy. Parzył.",
  deathDragon: "został zabity przez Smoka Kresu, gdy robił screena, żeby się pochwalić",
  deathBreath: "powąchał smoczy oddech. Nikt na to nie zasługuje.",
  deathElytra: "wbił się w ścianę z pełną prędkością. Ścianie nic nie jest.",
  deathShulker: "lewitował aż do nieba. Potem przestał lewitować.",
  deathSilverfish: "został zjedzony przez rybika cukrowego. Rybika cukrowego.",
  deathGhast: "został zwrócony do nadawcy",
  advDeeper: "Musimy zejść głębiej",
  advButton: "Co robi ten przycisk?",
  advRods: "Prosto w ogień",
  advReturn: "Zwrot do nadawcy",
  advSky: "Rozwiń skrzydła",
  subExplosion: "Wybuch",
  subBow: "Strzał z łuku",
  subArrow: "Uderzenie strzały",
  subEat: "Jedzenie",
  subHurtPlayer: "Gracz cierpi",
  subVillager: "Osadnik mamrocze",
  subSheep: "Owca beczy",
  subPig: "Świnia chrumka",
  subHiss: "Creeper syczy",
  subFlint: "Zgrzyt krzesiwa",
  subFireball: "Kula ognia świszczy",
  subBlaze: "Płomyk dyszy",
  subGhast: "Ghast pojękuje",
  subHeartbeat: "Serce nadzorcy bije",
  subRoar: "Nadzorca ryczy",
  subShriek: "Sculkowe wrzeszczydło wrzeszczy",
  subSculk: "Sculkowy czujnik drga",
  subSqueak: "Rybik syczy",
  subZap: "Pocisk shulkera",
  subLevitate: "Lewitowanie",
  subNetherPortal: "Portal się otwiera",
  deathCreeper: "dostał przytulasa od Kevina",
  creeperGranted: "chciałem się tylko przytulić.",
  mobSlain: "został zabity przez {player}",
  pigDown: "leży. Znowu.",
  clickToPlay: "Kliknij, aby grać dalej",
  noWebgl: "Twoja przeglądarka nie może wyświetlić gry w 3D (brak WebGL2). Włącz akcelerację sprzętową w ustawieniach, uruchom ją ponownie i spróbuj jeszcze raz. Tymczasem oto zakończenie.",
  signBfuunyBed: "Świetne miejsce\ndo spania.\nZaufaj mi.\n—Bfuuny",
  signBfuunyShip: "Dobre elytry\nsą na\ndrugim statku.\n—Bfuuny",
  signBfuunyExit: "WYJŚCIE\n→\n—Bfuuny",
  bfuunyChest: "haha. to ziemia. cała.",
  bfuunyBed: "haha. mówiłem, zaufaj mi.",
  ghostWardenHit: "ty go bijesz? nadzorcę? odważnie.",
  ghostWarden: "…ok. tego jeszcze nikt nie zrobił.",
};

export default pl;
