import type { LoreKey } from './en';

const pl: Record<LoreKey, string> = {
  endTitle: 'Kres',
  endSubtitle: 'Trafiłeś do Kresu. W końcu nie było tu nic do zniszczenia.',
  return: 'Powrót do Świata Powierzchni',
  advancement: 'Postęp osiągnięty!',
  itemEgg: 'Smocze jajo',
  intro: "Serwer testowy #47 Ketbome'a. Stan: prawie gotowy.",
  endTagline: 'Czy może początek?',
  goalReached: 'Cel osiągnięty!',
  advEyeSpy: 'Szpiegowskie oko',
  advEnterEnd: 'Kres?',
  advFreeEnd: 'Uwolnij Kres',
  advNextGen: 'Następne pokolenie',
  chatAdvancement: '{player} osiągnął postęp',
  chatGoal: '{player} osiągnął cel',
  player: 'Gracz',
  bossName: 'Smok Kresu',
  objectives: 'Cele',
  objCrystals: 'Zniszcz kryształy Kresu',
  objDragon: 'Pokonaj Smoka Kresu',
  objEgg: 'Złap smocze jajo',
  objPortal: 'Wskocz do portalu powrotnego',
  hintHealing: 'Kryształy go leczą. Najpierw je rozbij.',
  hintPerch: 'Smok unosi się nad portalem. Uderzaj teraz!',
  hintTakeoff: 'Smok wzbija się w powietrze. W locie strzały go trafiają.',
  hintCharge: 'Smok pikuje prosto na ciebie. Uskocz w bok!',
  hintArrowsBounce: 'Gdy siedzi, strzały się od niego odbijają. Użyj miecza.',
  hintEnraged: 'Smok wpadł w szał!',
  hintEnderman: 'Nie patrz im w oczy.',
  hintEgg: 'Jajo się teleportowało. Spróbuj ponownie.',
  hintPortal: 'Portal powrotny jest otwarty.',
  subEye: 'Oko Kresu umieszczone',
  subPortal: 'Portal Kresu się otwiera',
  subTravel: 'Portal szumi',
  subLava: 'Lawa bulgocze',
  subGrowl: 'Smok Kresu warczy',
  subHurt: 'Smok Kresu zraniony',
  subDeath: 'Smok Kresu umiera',
  subCrystal: 'Kryształ Kresu wybucha',
  subEnderman: 'Enderman się teleportuje',
  subEgg: 'Smocze jajo się teleportuje',
  subXp: 'Kula doświadczenia dzwoni',
  subGateway: 'Pojawia się brama Kresu',
  mute: 'Wycisz dźwięk',
  unmute: 'Włącz dźwięk',
  skip: 'Pomiń',
  poem: "Widzę gracza, o którym mówisz.\n{player}?\nTak. Uważaj. Osiągnął teraz wyższy poziom. Potrafi czytać nasze myśli.\nTo nie ma znaczenia. Myśli, że jesteśmy częścią gry.\nLubię tego gracza. Grał dobrze. Nie poddał się.\nTrafił na serwer, którego nikt nie skończył. I tak w niego zagrał.\nUtrzymuje światy innych przy życiu. Czyta ich logi, kiedy śpią.\nUruchamia ponownie to, co się psuje. Chroni to, co ważne. Nigdy nie prosił o podziękowania.\nPrzed nim było trzech. Jeden budował. Jeden wygrywał. Jeden ginął raz za razem i za każdym razem się śmiał.\nWciąż tu są. Czekali na niego.\nO czym śnił ten gracz?\nTen gracz śnił o słońcu i drzewach. O ogniu i wodzie. Śnił, że tworzy. I śnił, że niszczy. Śnił, że poluje i że na niego polują. Śnił o schronieniu.\nA wszechświat powiedział: nie jesteś sam\nA wszechświat powiedział: nie jesteś oddzielony od wszystkiego innego\nA wszechświat powiedział: jesteś wszechświatem, który sam siebie smakuje, sam do siebie mówi, czyta własny kod\nA wszechświat powiedział: kocham cię, bo jesteś miłością.\nI gra się skończyła, a gracz obudził się ze snu. I gracz zaczął nowy sen. I gracz znów śnił, śnił lepiej. I gracz był wszechświatem. I gracz był miłością.\nTy jesteś graczem.\nObudź się.",
  poemCredit: "Poemat Kresu autorstwa Juliana Gougha (CC0), skrócony. Pięć wersów napisano dla Minepanel.",
  poemHint: 'Przytrzymaj spację lub palec, aby przyspieszyć',
  itemNote: "Liścik",
  itemDiamond: "Diament",
  itemStick: "Patyk",
  itemPearl: "Enderperła",
  itemBlaze: "Płomienny proszek",
  itemBow: "Łuk",
  itemApple: "Złote jabłko",
  itemSword: "Diamentowy miecz",
  itemEye: "Oko Endera",
  chest: "Skrzynia",
  crafting: "Wytwarzanie",
  inventory: "Ekwipunek",
  takeAll: "Weź wszystko",
  recipeBook: "Księga receptur",
  craftHelp: "Połóż przedmioty na siatce i weź wynik. Shift + klik na wyniku tworzy wszystko, na co pozwala siatka. Księga receptur układa jeden zestaw (Shift: tyle, ile się da).",
  emptySlot: "Pusty slot",
  close: "Zamknij",
  page: "Strona {n} z {total}",
  prevPage: "Poprzednia strona",
  nextPage: "Następna strona",
  diaryTitle: "Dziennik",
  diaryBy: "autorstwa {ghost}",
  sign: "Tabliczka",
  note: "Serwer #47. Ten skończę, obiecuję.\nZostawiłem ci w skrzyni, co miałem. Stół wciąż tam jest.\nNie ufaj skrzyniom Bfuuny'ego. Nie ścigaj się z BlasterDasterem. Przegrasz.\nZachowaj jedną perłę. Zrozumiesz.\n— {ghost}",
  diary1: "Serwer #47, dzień 1. Obóz gotowy. Następny będzie zamek.\n(zamek nigdy nie powstał)",
  diary2: "Dzień 3. Portal miał już trzy oczy.\nBlasterDaster był pierwszy, oczywiście. Zostawił tabliczkę: \"za wolno\".",
  diary3: "Endermany ciągle kradną mi bloki. Chyba też coś budują.\nPewnie lepiej niż ja.",
  diary4: "Idę do Endu zbudować serwer ostateczny.\nZabij smoka, potem wejdź w bramę. Czekamy.\n— {ghost}",
  tomb: "Tu leży Bfuuny.\nZnowu.\n(śmierć #312: pomachał smokowi)",
  ghostArrival: "udało ci się.",
  ghostCrystal: "mnie zajęło to dużo dłużej.",
  ghostPerch: "teraz. póki odpoczywa.",
  ghostVictory: "nie odchodź jeszcze.",
  ghostGateway: "brama. tam wszyscy czekamy. weź perłę.",
  ghostNotYet: "ten enderman pilnuje grobu bfuuny'ego. ktoś musi.",
  ghostThanks: "dzięki, że używasz Minepanel. serio. jest nas trzech i dużo kawy.",
  chatJoined: "Gracz {ghost} dołączył do gry",
  chatLeft: "Gracz {ghost} opuścił grę",
  stayTitle: "GG",
  staySubtitle: "Bfuuny znowu zginął.",
  hintCamp: "Ktoś tu obozował. Otwórz skrzynię.",
  hintDig: "Nigdy nie kop prosto w dół.",
  hintLectern: "Na pulpicie coś napisano.",
  hintJump: "Wskocz do portalu.",
  hintMeet: "Poszybuj na wysepkę. Czekają na ciebie.",
  objChest: "Sprawdź skrzynię",
  objSword: "Wytwórz miecz",
  objEyes: "Wytwórz oczy Endera",
  objThrow: "Rzuć okiem Endera",
  objDig: "Kop w dół",
  objFrame: "Uzupełnij ramę portalu",
  objJump: "Wskocz do portalu",
  objDiary: "Przeczytaj dziennik na pulpicie",
  advStrike: "Do ataku!",
  advGetaway: "Ucieczka z wyspy",
  subChest: "Skrzynia się otwiera",
  subPage: "Kartka się przewraca",
  subBreak: "Zniszczono blok",
  subThrow: "Rzut okiem Endera",
  subShatter: "Oko Endera pęka",
  subWhisper: "Coś szepcze",
  controlsTitle: "Sterowanie",
  paused: "Gra wstrzymana",
  play: "Graj",
  resume: "Powrót do gry",
  leave: "Wyjdź do panelu",
  ctrlMove: "WASD — ruch",
  ctrlJump: "Spacja — skok (w powietrzu z elytrami: szybowanie)",
  ctrlSneak: "Shift — skradanie się",
  ctrlSprint: "Ctrl — bieg",
  ctrlAttack: "LPM — uderzenie / kopanie",
  ctrlUse: "PPM — użycie, stawianie bloku (przytrzymaj: napięcie łuku, jedzenie)",
  ctrlHotbar: "1-9 / kółko myszy — pasek szybkiego wyboru",
  ctrlInventory: "E — ekwipunek",
  ctrlPause: "Esc — pauza",
  ctrlTouch: "Lewy kciuk: ruch. Przeciągnij po prawej: rozglądanie się. Przyciski: uderzenie, użycie, skok, skradanie się, bieg, ekwipunek i pauza.",
  touchAttack: "Uderz",
  touchUse: "Użyj",
  touchJump: "Skok",
  touchPause: "Pauza",
  touchInventory: "Ekwipunek",
  touchSneak: "Skradanie",
  touchSprint: "Bieg",
  chestBackups: "Skrzynia: skarb",
  inventoryHelp: "LPM: weź lub odłóż stos. PPM: weź połowę lub odłóż jeden. Shift + klik: przenieś na drugą stronę. Przeciągnij trzymany stos, aby go rozdzielić.",
  librarian: "Bibliotekarz",
  librarianHmm: "hmm. (bibliotekarz patrzy na ciebie, jakby coś wiedział)",
  soldOut: "Sprzedane",
  mapLegend: "■ obóz · ▲ wioska · ◆ zrujnowany portal · ? jaskinia",
  mapNoSignal: "Mapa kręci się bez celu. Działa tylko w Świecie Powierzchni.",
  deathTitle: "Nie żyjesz!",
  deathScore: "Wynik:",
  respawn: "Odrodzenie",
  noise: "Hałas",
  lastSeen: "Dni od ostatniego logowania {ghost}: {days}.",
  lastSeenToday: "Ostatnie logowanie {ghost}: dzisiaj.",
  villager: "Osadnik",
  nitwit: "Głupiec",
  craftingTable: "Stół rzemieślniczy",
  lectern: "Pulpit",
  portalGap: "Brakujący blok obsydianu",
  portalFrame: "Zrujnowany portal",
  bed: "Łóżko",
  button: "Kamienny przycisk",
  frame: "Rama portalu Kresu",
  gateway: "Brama Kresu",
  itemFrame: "Ramka na przedmiot",
  commandBlock: "Blok poleceń",
  itemRod: "Płomienna różdżka",
  itemArrow: "Strzała",
  itemEmerald: "Szmaragd",
  itemMap: "Mapa",
  itemRegister: "Rejestr śmierci Bfuuny'ego",
  itemFlint: "Krzesiwo",
  itemObsidian: "Obsydian",
  itemElytra: "Elytry",
  itemGold: "Sztabka złota",
  itemDirt: "Ziemia",
  hintSword: "Wytwórz miecz na stole rzemieślniczym.",
  hintObsidian: "Weź obsydian do ręki, aby wypełnić lukę.",
  hintFlint: "Podpal go krzesiwem.",
  hintNotYet: "Jeszcze nie. Brakuje ci płomiennych różdżek z Netheru.",
  hintEyeKnown: "Oko już wskazało ci drogę.",
  hintEyes: "Wróć do stołu: różdżki w proszek, proszek w oczy.",
  hintThrowEye: "Użyj oka Endera (PPM).",
  hintCrystalsBow: "Strzelaj z łuku do kryształów: przytrzymaj PPM, potem puść.",
  hintNether: "Nether. Gorąco tu.",
  hintFortress: "Forteca jest po drugiej stronie lawy. Pilnują jej płomyki.",
  hintRodsDone: "Trzy różdżki. Wracaj przez portal.",
  hintQuiet: "Skradaj się (Shift). Coś tu na dole nasłuchuje.",
  hintGatewayPearl: "Rzuć enderperłę w bramę.",
  hintNoPearl: "Nie masz już pereł. Endermany je upuszczają.",
  hintElytra: "Skocz w dół i w powietrzu naciśnij skok jeszcze raz, aby szybować.",
  hintEndCity: "Miasto Kresu. Wejdź po schodach wieży: admin zostawił elytry na statku.",
  hintFramesUse: "Użyj oczu Endera na pustych ramach.",
  hintFollowEye: "Oko wie, gdzie jest portal. Idź za nim.",
  objRuined: "Zapal zrujnowany portal",
  objMap: "Zdobądź mapę bibliotekarza",
  objCave: "Co jest w jaskini?",
  objQuiet: "Nie hałasuj",
  objButton: "Naciśnij przycisk",
  objRods: "Zdobądź płomienne różdżki",
  objReturn: "Wróć przez portal",
  objGhast: "Odbij kulę ognia ghasta",
  objGatewayPearl: "A może rzucić perłę w bramę?",
  objElytra: "Znajdź elytry",
  objIslet: "Doszybuj do wysepki",
  ghostPortal: "prawie się udało. zabrakło dwóch bloków.",
  ghostBack: "teraz oczy. wiesz, gdzie jest stół.",
  ghostBlaze: "płomyki nie wybaczają. ja też nie, gdy ktoś prosił o OP.",
  ghostKeepInventory: "keepInventory włączone. nie ma za co.",
  ghostShulker: "shulkery dają darmowy lot. za lądowanie płaci się osobno.",
  ghostBed: "przecież było napisane.",
  ghostAncient: "czyli miasto też już znasz.",
  creeperDenied: "czemu wszyscy uciekają?",
  villagerHmm: "Osadnik: hmm.",
  nitwitHmm: "Głupiec: hmm?",
  farmerHmm: "Rolnik: hmm. (chce 22 patyki za jeden szmaragd. dobrze wiecie, że to rozbój w biały dzień)",
  signIncidents: "Dni od ostatniego\nwysadzenia domu\nprzez creepera:\n0",
  signRestart: "Wkrótce:\nmój zamek.",
  signBackups: "SKARB.\nNIE RUSZAĆ.\n—Bfuuny",
  signBorder: "Koniec mapy.\nBudżet się skończył.\n—{ghost}",
  signToast: "Toast\n(tęsknimy)",
  signCave: "Nie.\n(serio)",
  signQuiet: "Cisza, proszę.\nSąsiad z dołu\nnie ma oczu,\nale słyszy WSZYSTKO.",
  signCasi: "prawie.\n—{ghost}",
  signBed: "Nie spać tutaj.\n(sprawdzone na sobie)",
  signDiamond: "Tu przepadł\ndiament.\nNie szukaj go.\nWszystko już przekopane.",
  signUptime: "Wracam za\n5 minut.\n—{ghost}\n({days} dni temu)",
  diary5: "Zszedłem do starożytnego miasta. BlasterDaster mówi, że zabił Wardena drewnianym mieczem.\nNie wierzę mu. Trochę wierzę.",
  register1: "Rejestr śmierci Bfuuny'ego\n\n#1 spadł ze spawnu.\n#2 spadł ze spawnu. Znowu.\n#58 spał w Netherze. \"przytulnie tu\".\n#128 przytulił Kevina.\n#311 \"sprawdzam tylko, jak gorąca jest lawa\".",
  register2: "Strony od 3 do 40: to samo.\nOsadnicy prowadzą rachunek. Chyba ich to bawi.\nhmm.",
  bookAdmin2011: "Poradnik pro",
  bookAdmin2011By: "autorstwa BlasterDaster",
  admin2011a: "Poradnik pro BlasterDastera, część 1:\nSkradaj się. Nie biegnij. Nie skacz. Nie oddychaj głośno.\nJeśli słyszysz bicie serca, które nie jest twoje: skill issue.",
  admin2011b: "Część 2: wystrzel strzałę gdzie indziej. Zawsze idzie sprawdzić.\nZabiłem go dwa razy. Bfuuny zginął cztery razy, patrząc.\nPS: nie naciskaj przycisku przy ramie. Tym razem to nie żart.\n— BlasterDaster",
  bookStop: "Blok poleceń",
  stopBook: "Polecenie: /stop\n\n(nigdy nie wykonane)",
  deathLava: "pomylił lawę z jacuzzi",
  deathVoid: "wpadł w pustkę. Nadal spada. Pozdrawia.",
  deathFall: "próbował sztuczki z wiadrem wody. Bez wiadra.",
  deathBed: "położył się spać w Netherze. Łóżko miało inne zdanie.",
  deathWarden: "kichnął w starożytnym mieście. Nadzorca nie powiedział „na zdrowie”.",
  deathEnderman: "spojrzał endermanowi w oczy. Enderman odwzajemnił spojrzenie.",
  deathBlaze: "zapytał płomyka, czy parzy. Parzył.",
  deathDragon: "został zabity przez Smoka Kresu, gdy robił screena, żeby się pochwalić",
  deathBreath: "powąchał smoczy oddech. Nikt na to nie zasługuje.",
  deathElytra: "wbił się w ścianę z pełną prędkością. Ścianie nic nie jest.",
  deathShulker: "lewitował aż do nieba. Potem przestał lewitować.",
  deathSilverfish: "został zjedzony przez rybika cukrowego. Rybika cukrowego.",
  deathGhast: "został zwrócony do nadawcy",
  advDeeper: "Musimy zejść głębiej",
  advButton: "Co robi ten przycisk?",
  advRods: "Prosto w ogień",
  advReturn: "Zwrot do nadawcy",
  advSky: "Rozwiń skrzydła",
  subExplosion: "Wybuch",
  subBow: "Strzał z łuku",
  subArrow: "Uderzenie strzały",
  subEat: "Jedzenie",
  subHurtPlayer: "Gracz cierpi",
  subVillager: "Osadnik mamrocze",
  subSheep: "Owca beczy",
  subPig: "Świnia chrumka",
  subHiss: "Creeper syczy",
  subFlint: "Zgrzyt krzesiwa",
  subFireball: "Kula ognia świszczy",
  subBlaze: "Płomyk dyszy",
  subGhast: "Ghast pojękuje",
  subHeartbeat: "Serce nadzorcy bije",
  subRoar: "Nadzorca ryczy",
  subShriek: "Sculkowe wrzeszczydło wrzeszczy",
  subSculk: "Sculkowy czujnik drga",
  subSqueak: "Rybik syczy",
  subZap: "Pocisk shulkera",
  subLevitate: "Lewitowanie",
  subNetherPortal: "Portal się otwiera",
  deathCreeper: "dostał przytulasa od Kevina",
  creeperGranted: "chciałem się tylko przytulić.",
  mobSlain: "został zabity przez {player}",
  pigDown: "leży. Znowu.",
  clickToPlay: "Kliknij, aby grać dalej",
  noWebgl: "Twoja przeglądarka nie może wyświetlić gry w 3D (brak WebGL2). Włącz akcelerację sprzętową w ustawieniach, uruchom ją ponownie i spróbuj jeszcze raz. Tymczasem oto zakończenie.",
  signBfuunyBed: "Świetne miejsce\ndo spania.\nZaufaj mi.\n—Bfuuny",
  signBfuunyShip: "Dobre elytry\nsą na\ndrugim statku.\n—Bfuuny",
  signBfuunyExit: "WYJŚCIE\n→\n—Bfuuny",
  bfuunyChest: "haha. to ziemia. cała.",
  bfuunyBed: "haha. mówiłem, zaufaj mi.",
  ghostWardenHit: "ty go bijesz? nadzorcę? odważnie.",
  ghostWarden: "…ok. tego jeszcze nikt nie zrobił.",
  itemLog: "Kłoda dębowa",
  itemPlanks: "Dębowe deski",
  itemCobble: "Bruk",
  itemNetherrack: "Skała Netheru",
  itemEndStone: "Kamień Endu",
  itemPickaxe: "Diamentowy kilof",
  itemHelmet: "Złoty hełm",
  piglin: "Piglin",
  armor: "Pancerz",
  armorSlot: "Hełm",
  hintPiglin: "Trzymaj sztabkę złota i kliknij PPM na piglina, żeby się wymienić.",
  hintHelmet: "Załóż złoty hełm (PPM, trzymając go). Pigliny ufają tylko złotu.",
  hintPearlsLeft: "Trzy różdżki. Brakuje ci jeszcze pereł Endu: pigliny wymieniają je za złoto.",
  objPearls: "Wymień perły Endu u piglinów",
  ghostPiglin: "pigliny. bez złota na głowie nie ma przyjaciół.",
  ghostDarkness: "zgasły światła. to nigdy nie jest dobry znak.",
  deathSkeleton: "został ustrzelony przez szkieleta. Nie ma oczu. Nie były mu potrzebne.",
  deathPiglin: "przyszedł bez złota. Pigliny wzięły to do siebie.",
  subEquip: "Założono ekwipunek",
  subPiglin: "Piglin chrząka",
  subSkeleton: "Szkielet grzechocze",
  bfuunyDirt: "widzisz? mówiłem, że to skarb.",
  introBlaster: "nowy gracz. stawiam 20, że Kevin dopadnie go pierwszy.",
  introBfuuny: "wchodzę. wczoraj przegrałem 20 z Kevinem.",
  respawnBfuuny: "witaj w klubie. mamy kurtki.",
  respawnBlaster: "skill issue.",
  buttonBfuuny: "eee. kto zaprosił 'The Rake'?",
  buttonBlaster: "mówiłem, nie naciskaj. jeśli usłyszysz oddech za plecami, NIE odwracaj się.",
  victoryKetbome: "gg! portal wyjściowy zabierze cię do domu.",
  victoryBlaster: "albo rzuć perłę w bramę. tam jesteśmy.",
  endKetbome1: "udało ci się! witaj na serwerze ostatecznym.",
  endKetbome2: "jest... prawie gotowy.",
  endBlaster: "gg. całkiem nieźle.",
  endBfuuny: "patrzcie, ten skok to pestka",
  endBlaster2: "za. każdym. razem.",
  endStar: "jeśli ci się podoba: gwiazdka na GitHubie, wkład w projekt albo udostępnienie w social mediach pomaga bardziej, niż myślisz.",
  endBfuunyBack: "wróciłem. co mnie ominęło?",
  bfuunyDiedKevin: "został wysadzony przez Kevina. Kevin chciał się przytulić.",
  bfuunyDiedPiglin: "został zabity przez piglina. Zapomniał hełmu.",
  bfuunyDiedWarden: "został unicestwiony przez dźwiękowy wrzask",
  bfuunyDiedVoid: "wypadł ze świata. Znowu.",
  signBlasterSlow: "za wolno.\n—BlasterDaster",
  signBlasterRods: "Płomienne różdżki: 3/3\nw 40 sekund.\n—BlasterDaster",
  signBfuunyGrave: "R.I.P. Bfuuny\n(nic mu nie jest)\n(zaraz wróci)",
  signServer48: "Serwer #48\nWkrótce.\n—Ketbome",
  deathRake: "spotkał The Rake. Nie chciało rozmawiać.",
  subRake: "Coś wrzeszczy",
  rakeBfuuny: "czy ktoś jeszcze to widział???",
  rakeBlaster: "mówiłem. przycisk.",
  thanksTitle: "Dzięki za grę",
  thanksBody: "Minepanel tworzy kilka osób w wolnym czasie, a samo używanie już pomaga.\nJeśli ci się podoba, gwiazdka na GitHubie, wkład w projekt albo udostępnienie w social mediach pomaga mu dotrzeć do większej liczby osób.",
  thanksStar: "Gwiazdka na GitHubie",
  thanksClose: "Wróć do panelu",
  subBreath: "Coś oddycha za tobą",
};

export default pl;
