import type { LoreKey } from './en';

const pt: Record<LoreKey, string> = {
  endTitle: 'O End',
  endSubtitle: 'Você chegou ao End. Afinal, não havia nada aqui para destruir.',
  return: 'Voltar ao Overworld',
  advancement: 'Progresso conquistado!',
  itemEgg: 'Ovo de dragão',
  intro: "Servidor de testes #47 do Ketbome. Status: quase pronto.",
  endTagline: 'Ou o começo?',
  goalReached: 'Meta alcançada!',
  advEyeSpy: 'Olho vivo',
  advEnterEnd: 'O Fim?',
  advFreeEnd: 'Liberte o End',
  advNextGen: 'A próxima geração',
  chatAdvancement: '{player} conquistou o progresso',
  chatGoal: '{player} alcançou a meta',
  player: 'Jogador',
  bossName: 'Dragão do Ender',
  objectives: 'Objetivos',
  objCrystals: 'Destrua os cristais do End',
  objDragon: 'Derrote o Dragão do Ender',
  objEgg: 'Pegue o ovo de dragão',
  objPortal: 'Pule no portal de saída',
  hintHealing: 'Os cristais estão curando ele. Quebre-os primeiro.',
  hintPerch: 'O dragão está sobre o portal. Ataque agora!',
  hintTakeoff: 'O dragão levanta voo. No ar, as flechas o atingem.',
  hintCharge: 'O dragão está mergulhando em você. Desvie para o lado!',
  hintArrowsBounce: 'Pousado, as flechas ricocheteiam. Use a espada.',
  hintEnraged: 'O dragão ficou furioso!',
  hintEnderman: 'Não olhe nos olhos deles.',
  hintEgg: 'O ovo se teletransportou. Tente de novo.',
  hintPortal: 'O portal de saída está aberto.',
  subEye: 'Olho do Ender encaixado',
  subPortal: 'Portal do End se abre',
  subTravel: 'Portal zune',
  subLava: 'Lava borbulha',
  subGrowl: 'Dragão do Ender rosna',
  subHurt: 'Dragão do Ender ferido',
  subDeath: 'Dragão do Ender morre',
  subCrystal: 'Cristal do End explode',
  subEnderman: 'Enderman se teletransporta',
  subEgg: 'Ovo de dragão se teletransporta',
  subXp: 'Orbe de experiência tilinta',
  subGateway: 'Portal de passagem do End surge',
  mute: 'Silenciar som',
  unmute: 'Ativar som',
  skip: 'Pular',
  poem: "Eu vejo o jogador a quem você se refere.\n{player}?\nSim. Cuidado. Ele alcançou um nível mais alto agora. Ele consegue ler nossos pensamentos.\nIsso não importa. Ele acha que somos parte do jogo.\nEu gosto deste jogador. Ele jogou bem. Ele não desistiu.\nChegou a um servidor que nunca foi terminado. Jogou mesmo assim.\nEle cria mundos para os amigos jogarem. Deixa-os abertos enquanto eles dormem.\nEle conserta o que quebra. Guarda o que importa. Nunca pediu agradecimento.\nHouve três antes dele. Um construía. Um vencia. Um morria sem parar, e ria toda vez.\nEles ainda estão aqui. Estavam esperando por ele.\nCom o que este jogador sonhou?\nEste jogador sonhou com a luz do sol e com árvores. Com fogo e água. Sonhou que criava. E sonhou que destruía. Sonhou que caçava e que era caçado. Sonhou com abrigo.\nE o universo disse: você não está sozinho\nE o universo disse: você não está separado de todas as outras coisas\nE o universo disse: você é o universo provando a si mesmo, falando consigo mesmo, lendo o próprio código\nE o universo disse: eu te amo porque você é amor.\nE o jogo acabou e o jogador acordou do sonho. E o jogador começou um novo sonho. E o jogador sonhou de novo, sonhou melhor. E o jogador era o universo. E o jogador era amor.\nVocê é o jogador.\nAcorde.",
  poemCredit: "Poema do End de Julian Gough (CC0), resumido. Cinco linhas foram escritas para o Minepanel.",
  poemHint: 'Segure Espaço ou mantenha pressionado para acelerar',
  itemNote: "Bilhete",
  itemDiamond: "Diamante",
  itemStick: "Graveto",
  itemPearl: "Pérola de Ender",
  itemBlaze: "Pó de Blaze",
  itemBow: "Arco",
  itemApple: "Maçã Dourada",
  itemSword: "Espada de Diamante",
  itemEye: "Olho de Ender",
  chest: "Baú",
  crafting: "Fabricação",
  inventory: "Inventário",
  takeAll: "Pegar tudo",
  recipeBook: "Livro de receitas",
  craftHelp: "Coloque itens na grade e pegue o resultado. Shift + clique no resultado fabrica tudo o que a grade permite. O livro de receitas monta um conjunto (Shift: quantos der).",
  emptySlot: "Espaço vazio",
  close: "Fechar",
  page: "Página {n} de {total}",
  prevPage: "Página anterior",
  nextPage: "Próxima página",
  diaryTitle: "Diário",
  diaryBy: "por {ghost}",
  sign: "Placa",
  note: "Servidor #47. Esse eu termino, prometo.\nDeixei no baú o que eu tinha. A mesa continua lá.\nNão confie nos baús do Bfuuny. Não aposte corrida com o BlasterDaster. Você vai perder.\nGuarde uma pérola. Você vai entender.\n— {ghost}",
  diary1: "Servidor #47, dia 1. O acampamento está pronto. Depois vem o castelo.\n(o castelo nunca veio)",
  diary2: "Dia 3. O portal já tinha três olhos.\nO BlasterDaster chegou primeiro, claro. Deixou uma placa: \"muito lento\".",
  diary3: "Os endermen vivem roubando meus blocos. Acho que eles também estão construindo algo.\nProvavelmente melhor que eu.",
  diary4: "Vou para o End construir o servidor definitivo.\nMate o dragão e depois pegue o portal do End. Estaremos esperando.\n— {ghost}",
  tomb: "Aqui jaz Bfuuny.\nDe novo.\n(morte #312: acenou para o dragão)",
  ghostArrival: "você chegou.",
  ghostCrystal: "eu demorei muito mais.",
  ghostPerch: "agora. enquanto ele descansa.",
  ghostVictory: "não vá embora ainda.",
  ghostGateway: "o portal do End. estamos todos lá. traga uma pérola.",
  ghostNotYet: "aquele enderman guarda o túmulo do bfuuny. alguém tem que fazer isso.",
  ghostThanks: "obrigado por usar o Minepanel. de verdade. somos três e muito café.",
  chatJoined: "{ghost} entrou no jogo",
  chatLeft: "{ghost} saiu do jogo",
  stayTitle: "GG",
  staySubtitle: "Bfuuny morreu de novo.",
  hintCamp: "Alguém acampou aqui. Abra o baú.",
  hintDig: "Nunca cave reto para baixo.",
  hintLectern: "Há algo escrito no atril.",
  hintJump: "Pule no portal.",
  hintMeet: "Plane até a ilhota. Eles estão te esperando.",
  objChest: "Confira o baú",
  objSword: "Fabrique uma espada",
  objEyes: "Fabrique olhos de Ender",
  objThrow: "Lance um olho de Ender",
  objDig: "Cave para baixo",
  objFrame: "Complete a moldura do portal",
  objJump: "Pule no portal",
  objDiary: "Leia o diário no atril",
  advStrike: "Hora de Atacar!",
  advGetaway: "O começo do fim",
  subChest: "Baú se abre",
  subPage: "Página vira",
  subBreak: "Bloco quebrado",
  subThrow: "Olho de Ender lançado",
  subShatter: "Olho de Ender se quebra",
  subWhisper: "Algo sussurra",
  controlsTitle: "Controles",
  paused: "Jogo pausado",
  play: "Jogar",
  resume: "Voltar ao jogo",
  leave: "Sair para o painel",
  ctrlMove: "WASD — mover",
  ctrlJump: "Espaço — pular (no ar com élitros: planar)",
  ctrlSneak: "Shift — agachar",
  ctrlSprint: "Ctrl — correr",
  ctrlAttack: "Clique esquerdo — golpear / minerar",
  ctrlUse: "Clique direito — usar, colocar um bloco (segurar: puxar o arco, comer)",
  ctrlHotbar: "1-9 / roda — barra rápida",
  ctrlInventory: "E — inventário",
  ctrlPause: "Esc — pausa",
  ctrlTouch: "Polegar esquerdo: mover. Arraste à direita: olhar. Botões: golpear, usar, pular, agachar, correr, inventário e pausa.",
  touchAttack: "Golpear",
  touchUse: "Usar",
  touchJump: "Pular",
  touchPause: "Pausa",
  touchInventory: "Inventário",
  touchSneak: "Agachar",
  touchSprint: "Correr",
  chestBackups: "Baú: tesouro",
  inventoryHelp: "Clique esquerdo: pegar ou soltar uma pilha. Clique direito: pegar metade ou soltar um. Shift + clique: mandar para o outro lado. Arraste uma pilha para distribuí-la.",
  librarian: "Bibliotecário",
  librarianHmm: "hmm. (o bibliotecário olha para você como se soubesse de algo)",
  soldOut: "Vendido",
  mapLegend: "■ acampamento · ▲ vila · ◆ portal em ruínas · ? caverna",
  mapNoSignal: "O mapa gira sem rumo. Ele só funciona no Overworld.",
  deathTitle: "Você morreu!",
  deathScore: "Pontuação:",
  respawn: "Renascer",
  noise: "Barulho",
  lastSeen: "Última conexão de {ghost}: há {days} dias.",
  lastSeenToday: "Última conexão de {ghost}: hoje.",
  villager: "Aldeão",
  nitwit: "Palerma",
  craftingTable: "Bancada de Trabalho",
  lectern: "Atril",
  portalGap: "Falta um bloco de obsidiana",
  portalFrame: "Portal em ruínas",
  bed: "Cama",
  button: "Botão de Pedra",
  frame: "Moldura do Portal do End",
  gateway: "Passagem do End",
  itemFrame: "Moldura de Item",
  commandBlock: "Bloco de Comando",
  itemRod: "Vara de Blaze",
  itemArrow: "Flecha",
  itemEmerald: "Esmeralda",
  itemMap: "Mapa",
  itemRegister: "Registro de mortes do Bfuuny",
  itemFlint: "Pederneira",
  itemObsidian: "Obsidiana",
  itemElytra: "Élitros",
  itemGold: "Barra de Ouro",
  itemDirt: "Terra",
  hintSword: "Fabrique uma espada na bancada.",
  hintObsidian: "Segure obsidiana para preencher o buraco.",
  hintFlint: "Acenda-o com a pederneira.",
  hintNotYet: "Ainda não. Você ainda precisa de varas de blaze do Nether.",
  hintEyeKnown: "O olho já mostrou o caminho para você.",
  hintEyes: "De volta à bancada: varas viram pó, pó vira olhos.",
  hintThrowEye: "Use um olho de Ender (clique direito).",
  hintCrystalsBow: "Atire nos cristais com o arco: segure o clique direito e solte.",
  hintNether: "O Nether. Está quente aqui.",
  hintFortress: "A fortaleza fica do outro lado da lava. Blazes a protegem.",
  hintRodsDone: "Três varas. Volte pelo portal.",
  hintQuiet: "Agache-se (Shift). Tem algo aqui embaixo escutando.",
  hintGatewayPearl: "Jogue uma pérola de Ender na passagem.",
  hintNoPearl: "Acabaram as pérolas. Os endermen as deixam cair.",
  hintElytra: "Pule no vazio e pule de novo no ar para planar.",
  hintEndCity: "Uma cidade do End. Suba a escada da torre: o admin deixou os élitros no navio.",
  hintFramesUse: "Use os olhos de Ender nas molduras vazias.",
  hintFollowEye: "O olho sabe onde fica o portal. Siga-o.",
  objRuined: "Acenda o portal em ruínas",
  objMap: "Consiga o mapa do bibliotecário",
  objCave: "O que tem na caverna?",
  objQuiet: "Não faça barulho",
  objButton: "Aperte o botão",
  objRods: "Consiga varas de blaze",
  objReturn: "Volte pelo portal",
  objGhast: "Devolva a bola de fogo do ghast",
  objGatewayPearl: "Ou jogar sua pérola na passagem?",
  objElytra: "Encontre os élitros",
  objIslet: "Plane até a ilhota",
  ghostPortal: "quase terminei. faltaram dois blocos.",
  ghostBack: "agora os olhos. você sabe onde fica a bancada.",
  ghostBlaze: "os blazes não perdoam. eu também não perdoava quem pedia pra ser admin.",
  ghostKeepInventory: "aqui morrer não te faz perder suas coisas. de nada.",
  ghostShulker: "shulkers te dão um voo grátis. o pouso é cobrado à parte.",
  ghostBed: "eu avisei.",
  ghostAncient: "então você também encontrou a cidade.",
  creeperDenied: "por que todo mundo vai embora?",
  villagerHmm: "Aldeão: hmm.",
  nitwitHmm: "Palerma: hmm?",
  farmerHmm: "Fazendeiro: hmm. (te oferece uma cenoura por uma esmeralda. diz que é preço de amigo)",
  signIncidents: "Dias sem um\ncreeper explodir\na minha casa:\n0",
  signRestart: "Em breve:\nmeu castelo.",
  signBackups: "TESOURO.\nNÃO MEXA.\n—Bfuuny",
  signBorder: "Fim do mapa.\nAcabou o orçamento.\n—{ghost}",
  signToast: "Mascote do servidor:\no coelho.\nMais útil que o Bfuuny.",
  signCave: "Não.\n(sério)",
  signQuiet: "Silêncio, por favor.\nO vizinho de baixo\nnão tem olhos,\nmas ouve TUDO.",
  signCasi: "quase.\n—{ghost}",
  signBed: "Não durma aqui.\n(aprendi do jeito difícil)",
  signDiamond: "Foi aqui que eu perdi\no diamante.\nNão procure.\nEu já procurei.",
  signUptime: "Volto em\n5 minutos.\n—{ghost}\n(há {days} dias)",
  diary5: "Desci até a cidade ancestral. O BlasterDaster diz que matou o Warden com uma espada de madeira.\nNão acredito. Acredito um pouquinho.",
  register1: "Registro de mortes do Bfuuny\n\n#1 caiu do spawn.\n#2 caiu do spawn. De novo.\n#58 dormiu no Nether. \"é aconchegante\".\n#128 abraçou o Kevin.\n#311 \"só estou vendo se a lava está quente\".",
  register2: "Páginas 3 a 40: mais do mesmo.\nOs aldeões mantêm a contagem. Parecem gostar.\nhmm.",
  bookAdmin2011: "Guia pro",
  bookAdmin2011By: "por BlasterDaster",
  admin2011a: "Guia pro do BlasterDaster, parte 1:\nAgache. Não corra. Não pule. Não respire alto.\nSe ouvir um coração que não é o seu: corra. Não, espera. Não corra.",
  admin2011b: "Parte 2: atire uma flecha em outro lugar. Ele sempre vai conferir.\nMatei duas vezes. O Bfuuny morreu quatro vezes assistindo.\nPS: não aperte o botão perto da moldura. Dessa vez não é piada.\n— BlasterDaster",
  bookStop: "Bloco de Comando",
  stopBook: "Comando: /give @p diamond 64\n\n(o Bfuuny pediu. não.)",
  deathLava: "confundiu lava com jacuzzi",
  deathVoid: "caiu no vazio. Ainda está caindo. Manda um abraço.",
  deathFall: "tentou o truque do balde de água. Sem balde.",
  deathBed: "foi dormir no Nether. A cama discordou.",
  deathWarden: "espirrou na cidade antiga. O Defensor não disse saúde.",
  deathEnderman: "olhou um enderman nos olhos. O enderman olhou de volta.",
  deathBlaze: "perguntou a um blaze se ele queimava. Queimava.",
  deathDragon: "foi morto pelo Dragão do Ender enquanto tirava um print pra se exibir",
  deathBreath: "cheirou o bafo do dragão. Ninguém merece.",
  deathElytra: "bateu numa parede a toda velocidade. A parede está bem.",
  deathShulker: "levitou até o céu. Depois parou de levitar.",
  deathSilverfish: "foi devorado por uma traça. Uma traça.",
  deathGhast: "teve uma recepção calorosa",
  advDeeper: "O buraco é mais embaixo",
  advButton: "O que esse botão faz?",
  advRods: "Brincando com fogo",
  advReturn: "Recepção calorosa",
  advSky: "Ao infinito e além!",
  subExplosion: "Explosão",
  subBow: "Arco dispara",
  subArrow: "Flecha atinge",
  subEat: "Comendo",
  subHurtPlayer: "Jogador ferido",
  subVillager: "Aldeão murmura",
  subSheep: "Ovelha bale",
  subPig: "Porco grunhe",
  subHiss: "Creeper sibila",
  subFlint: "Pederneira acende",
  subFireball: "Bola de fogo sibila",
  subBlaze: "Blaze respira",
  subGhast: "Ghast chora",
  subHeartbeat: "Coração do Defensor bate",
  subRoar: "Defensor ruge",
  subShriek: "Emissor de Sculk guincha",
  subSculk: "Sensor de Sculk estala",
  subSqueak: "Traça sibila",
  subZap: "Projétil de Shulker",
  subLevitate: "Levitando",
  subNetherPortal: "Portal se abre",
  deathCreeper: "ganhou um abraço do Kevin",
  creeperGranted: "eu só queria um abraço.",
  mobSlain: "foi morto por {player}",
  pigDown: "já esperava por isso.",
  clickToPlay: "Clique para continuar jogando",
  noWebgl: "Seu navegador não consegue desenhar o jogo em 3D (falta WebGL2). Ative a aceleração de hardware nas configurações, reinicie-o e tente de novo. Enquanto isso, aqui está o final.",
  signBfuunyBed: "Ótimo lugar\npara dormir.\nConfia.\n—Bfuuny",
  signBfuunyShip: "Os élitros bons\nestão no\noutro navio.\n—Bfuuny",
  signBfuunyExit: "SAÍDA\n→\n—Bfuuny",
  bfuunyChest: "kkkkk. é terra. tudo.",
  bfuunyBed: "kkkkk. eu disse pra confiar.",
  ghostWardenHit: "tá batendo nele? no Defensor? que coragem.",
  ghostWarden: "…ok. ninguém nunca tinha feito isso.",
  itemLog: "Tronco de Carvalho",
  itemPlanks: "Tábuas de Carvalho",
  itemCobble: "Pedregulho",
  itemNetherrack: "Netherrack",
  itemEndStone: "Pedra do End",
  itemPickaxe: "Picareta de Diamante",
  itemHelmet: "Capacete de Ouro",
  piglin: "Piglin",
  armor: "Armadura",
  armorSlot: "Capacete",
  hintPiglin: "Segure uma barra de ouro e clique com o botão direito num piglin para negociar.",
  hintHelmet: "Use o capacete de ouro (clique direito com ele). Piglins só confiam no ouro.",
  hintPearlsLeft: "Três varas. Ainda faltam pérolas do Ender: os piglins trocam por ouro.",
  objPearls: "Troque pérolas do Ender com os piglins",
  ghostPiglin: "piglins. sem ouro na cabeça, sem amigos.",
  ghostDarkness: "as luzes se apagaram. isso nunca é bom sinal.",
  deathSkeleton: "foi alvejado por um esqueleto. Ele não tem olhos. Não precisou deles.",
  deathPiglin: "apareceu sem ouro. Os piglins levaram para o lado pessoal.",
  subEquip: "Equipamento colocado",
  subPiglin: "Piglin bufa",
  subSkeleton: "Esqueleto chacoalha",
  bfuunyDirt: "viu? eu disse que era um tesouro.",
  introBlaster: "jogador novo. aposto 20 que o Kevin pega ele primeiro.",
  introBfuuny: "fechado. ontem perdi 20 pro Kevin.",
  respawnBfuuny: "bem-vindo ao clube. eu sou o presidente.",
  respawnBlaster: "treina mais.",
  buttonBfuuny: "hã. quem convidou 'The Rake'?",
  buttonBlaster: "eu disse pra não apertar. se ouvir algo respirando atrás de você, NÃO se vire.",
  victoryKetbome: "gg! o portal de saída te leva pra casa.",
  victoryBlaster: "ou jogue uma pérola no portal do End. é lá que a gente está.",
  endKetbome1: "você conseguiu! bem-vindo ao servidor definitivo.",
  endKetbome2: "está... quase pronto.",
  endBlaster: "gg. nada mal.",
  endBfuuny: "olha isso, esse pulo eu faço fácil",
  endBlaster2: "toda. santa. vez.",
  endStar: "se você curtiu: uma estrela no GitHub, uma contribuição ou compartilhar nas redes ajuda mais do que você imagina.",
  endBfuunyBack: "voltei. o que eu perdi?",
  bfuunyDiedKevin: "foi explodido pelo Kevin. Ele queria um abraço.",
  bfuunyDiedPiglin: "foi morto por um piglin. Esqueceu o capacete.",
  bfuunyDiedWarden: "foi obliterado por um grito sonicamente carregado",
  bfuunyDiedVoid: "caiu do mundo. De novo.",
  signBlasterSlow: "muito lento.\n—BlasterDaster",
  signBlasterRods: "Varas de blaze: 3/3\nem 40 segundos.\n—BlasterDaster",
  signBfuunyGrave: "R.I.P. Bfuuny\n(ele está bem)\n(já volta)",
  signServer48: "Servidor #48\nEm breve.\n—Ketbome",
  deathRake: "encontrou The Rake. Ele não queria conversar.",
  deathZombie: "pediu um abraço a um zumbi. Não era o Kevin.",
  deathZombieVillager: "tentou negociar com um aldeão zumbi. Ele queria cérebros.",
  deathDrowned: "foi nadar. Os afogados não eram salva-vidas.",
  deathSpider: "não olhou para o teto.",
  deathWitch: "aceitou uma poção de uma estranha.",
  deathSlime: "subestimou um slime pequenininho. Depois eram quatro.",
  deathPhantom: "não dormiu. O Ketbome também não, mas já está acostumado.",
  deathZombifiedPiglin: "bateu num piglin zumbificado. Só num.",
  deathHoglin: "chamou um hoglin de porquinho.",
  deathMagmaCube: "tentou apagar um cubo de magma pulando em cima.",
  deathWitherSkeleton: "queria um crânio de wither. O esqueleto queria ficar com ele.",
  deathEndermite: "jogou tantas pérolas que algo saiu de uma delas.",
  subRake: "Algo guincha",
  rakeBfuuny: "mais alguém viu isso???",
  rakeBlaster: "eu avisei. o botão.",
  thanksTitle: "Obrigado por jogar",
  thanksBody: "O Minepanel é feito por poucas pessoas no tempo livre, e usá-lo já ajuda.\nSe você curtiu, uma estrela no GitHub, uma contribuição ou compartilhar nas redes ajuda a chegar em mais gente.",
  thanksStar: "Estrela no GitHub",
  thanksClose: "Voltar ao painel",
  subBreath: "Algo respira atrás de você",
  hintSleepDay: "Você só pode dormir à noite ou durante tempestades",
  hintSleepMonsters: "Você não pode descansar agora; há monstros por perto",
  ghostSleep: "você dormiu mais do que eu no servidor #47 inteiro.",
  advTreasure: "Tesouro verdadeiro",
  advPacifist: "Pacifista",
  advKevin: "Amigo do Kevin",
  advNotAJoke: "Não era piada",
  advRake: "Ainda respirando",
  advNoElytra: "Quem precisa de asas",
  lineTreasure: "…você guardou? ninguém nunca guarda.",
  linePacifist: "nem um enderman. respeito.",
  lineKevin: "abraço?",
  lineNotAJoke: "duas vezes. DUAS VEZES.",
  lineRake: "você sobreviveu? eu não sobrevivi.",
  lineNoElytra: "ok. nem eu fiz isso.",
  thanksServer48: "Visitar o servidor #48",
  signServer48Day1: "Servidor #48. Dia 1.\nComecei.\n—Ketbome",
  signServer48Blaster: "Servidor #48 (o meu).\nPronto.\n—BlasterDaster",
  s48Ketbome: "comecei.",
  s48Blaster: "o meu já está pronto.",
  s48Bfuuny: "cadê a borda do mapa? ah, ali.",
  s48Ketbome2: "amanhã eu coloco um parapeito.",
  guide3a: "Guia pro do BlasterDaster, parte 3: o Nether.\nOs ghasts choram porque eu ganho.\nOs piglins me dão desconto. Deve ser o carisma.",
  guide3b: "Lava não é banheira de hidromassagem.\nO Bfuuny não leu esta parte.\nO Bfuuny não lê.\n— BlasterDaster",
  register3: "Página 41: convidados.\n{player}: {deaths}.\nO Bfuuny diz que as suas não contam.\nContam.",
  rabbitName: "Fofinho",
  signVillage: "Vila Minepanel.\nSeus moradores ajudaram\na construir o painel.\nObrigado!",
  signTempleBfuuny: "Não pise\nno meio.\n(eu pisei no meio)\n—Bfuuny",
  signRuinDesert: "Servidor #12:\na pirâmide.\nFiz uma quina.\n—Ketbome",
  signRuinTaiga: "Servidor #23:\no iglu. Ia ser\nde neve. É de terra.\n—Ketbome",
  signRuinSwamp: "Servidor #31:\nfazenda de slimes.\nSlimes até agora: 0.\n—Ketbome",
  signRuinCoast: "Servidor #40:\no porto.\nTerminei a placa.\n—Ketbome",
  signWreckNote: "Tesouro enterrado:\n3 passos ao norte\ndo cacto da praia.\n—Bfuuny",
  ghostTreasure: "meu diamante! perdi no nether. não pergunta como veio parar aqui.",
  advRuins: "Obras inacabadas",
  ghostRuins: "você viu todas. agora sabe por que eu nunca termino nada.",
  deathTnt: "pisou no meio. O Bfuuny avisou.",
  deathCactus: "se encostou num cacto. Por tempo demais.",
  deathGolem: "bateu no golem de ferro da vila. Ele revidou.",
  deathRabbit: "bateu no Fofinho três vezes. O Fofinho não perdoa.",
  pelusaBfuuny: "nem eu mexo com o Fofinho.",
  ghostPhantoms: "duas noites sem dormir. as coisas no céu percebem.",
  itemBone: "Osso",
  golemAngry: "você bateu no golem. eu assisto daqui.",
  wolfTamed: "você tem um cachorro. eu também tive. ele foi embora com o BlasterDaster.",
  wolfDied: "não fui eu. dessa vez.",
  hintBone: "Segure um osso e use num lobo para domesticá-lo.",
  pigName: "Bacon",
};

export default pt;
