import type { LoreKey } from './en';

const pt: Record<LoreKey, string> = {
  endTitle: 'O End',
  endSubtitle: 'Você chegou ao End. Afinal, não havia nada aqui para destruir.',
  return: 'Voltar ao Overworld',
  advancement: 'Progresso conquistado!',
  itemEgg: 'Ovo de dragão',
  intro: 'Disseram para você não apertar.',
  endTagline: 'Ou o começo?',
  goalReached: 'Meta alcançada!',
  advEyeSpy: 'Olho vivo',
  advEnterEnd: 'O Fim?',
  advFreeEnd: 'Liberte o End',
  advNextGen: 'A próxima geração',
  chatAdvancement: '{player} conquistou o progresso',
  chatGoal: '{player} alcançou a meta',
  player: 'Jogador',
  bossName: 'Dragão do Ender',
  objectives: 'Objetivos',
  objCrystals: 'Destrua os cristais do End',
  objDragon: 'Derrote o Dragão do Ender',
  objEgg: 'Pegue o ovo de dragão',
  objPortal: 'Pule no portal de saída',
  hintHealing: 'Os cristais estão curando ele. Quebre-os primeiro.',
  hintPerch: 'O dragão está sobre o portal. Ataque agora!',
  hintEnderman: 'Não olhe nos olhos deles.',
  hintEgg: 'O ovo se teletransportou. Tente de novo.',
  hintPortal: 'O portal de saída está aberto.',
  subEye: 'Olho do Ender encaixado',
  subPortal: 'Portal do End se abre',
  subTravel: 'Portal zune',
  subLava: 'Lava borbulha',
  subGrowl: 'Dragão do Ender rosna',
  subHurt: 'Dragão do Ender ferido',
  subDeath: 'Dragão do Ender morre',
  subCrystal: 'Cristal do End explode',
  subEnderman: 'Enderman se teletransporta',
  subEgg: 'Ovo de dragão se teletransporta',
  subXp: 'Orbe de experiência tilinta',
  subGateway: 'Portal de passagem do End surge',
  mute: 'Silenciar som',
  unmute: 'Ativar som',
  skip: 'Pular',
  poem: 'Eu vejo o jogador a quem você se refere.\n{player}?\nSim. Cuidado. Ele alcançou um nível mais alto agora. Ele consegue ler nossos pensamentos.\nIsso não importa. Ele acha que somos parte do jogo.\nEu gosto deste jogador. Ele jogou bem. Ele não desistiu.\nDisseram a ele para não apertar o botão.\nEle apertou mesmo assim. Eles sempre apertam. É assim que nos encontram.\nEle mantém mundos funcionando para os outros. Lê os logs deles enquanto dormem.\nEle reinicia o que quebra. Guarda o que importa. Nunca pediu agradecimento.\nHouve outro antes. Ele também jogou bem. Ele ficou.\nEste vai acordar.\nCom o que este jogador sonhou?\nEste jogador sonhou com a luz do sol e com árvores. Com fogo e água. Sonhou que criava. E sonhou que destruía. Sonhou que caçava e que era caçado. Sonhou com abrigo.\nE o universo disse: você não está sozinho\nE o universo disse: você não está separado de todas as outras coisas\nE o universo disse: você é o universo provando a si mesmo, falando consigo mesmo, lendo o próprio código\nE o universo disse: eu te amo porque você é amor.\nE o jogo acabou e o jogador acordou do sonho. E o jogador começou um novo sonho. E o jogador sonhou de novo, sonhou melhor. E o jogador era o universo. E o jogador era amor.\nVocê é o jogador.\nAcorde.',
  poemCredit: "Poema do End de Julian Gough (CC0), resumido. Seis linhas foram escritas para o Minepanel.",
  poemHint: 'Segure Espaço ou mantenha pressionado para acelerar',
  itemNote: "Bilhete",
  itemDiamond: "Diamante",
  itemStick: "Graveto",
  itemPearl: "Pérola de Ender",
  itemBlaze: "Pó de Blaze",
  itemBow: "Arco",
  itemApple: "Maçã Dourada",
  itemSword: "Espada de Diamante",
  itemEye: "Olho de Ender",
  chest: "Baú",
  crafting: "Fabricação",
  inventory: "Inventário",
  takeAll: "Pegar tudo",
  recipeBook: "Livro de receitas",
  craftHelp: "Coloque itens na grade e pegue o resultado. Shift + clique no resultado fabrica tudo o que a grade permite. O livro de receitas monta um conjunto (Shift: quantos der).",
  emptySlot: "Espaço vazio",
  close: "Fechar",
  page: "Página {n} de {total}",
  prevPage: "Página anterior",
  nextPage: "Próxima página",
  diaryTitle: "Diário",
  diaryBy: "por {ghost}",
  sign: "Placa",
  note: "Para quem vier depois.\nEu sabia que você ia apertar. Todo mundo aperta.\nDeixei para você o que me restou. A bancada ainda está lá.\nGuarde uma pérola. Você vai entender.\n— {ghost}",
  diary1: "Mantive este servidor funcionando por anos. Reiniciei o que quebrava. Ninguém nunca soube meu nome.\nHoje à noite eu apertei o botão.",
  diary2: "O portal já tinha três olhos.\nNão começou comigo. Alguém esteve aqui antes de mim, e antes dessa pessoa, mais alguém.",
  diary3: "Dizem que os endermen carregam blocos porque sentem falta de alguma coisa.\nQue não suportam ser olhados porque isso os lembra de quem eram.",
  diary4: "Vou descer.\nSe alguém ler isto: mate o dragão. Depois escolha.\n— {ghost}",
  tomb: "Aqui ficou\n{ghost}.\nNão foi o dragão.",
  ghostArrival: "você chegou.",
  ghostCrystal: "eu demorei muito mais.",
  ghostPerch: "agora. enquanto ele descansa.",
  ghostVictory: "não vá embora ainda.",
  ghostGateway: "a passagem. vem.",
  ghostNotYet: "ainda não.",
  ghostThanks: "que bom que você veio.",
  chatJoined: "{ghost} entrou no jogo",
  chatLeft: "{ghost} saiu do jogo",
  stayTitle: "Você ficou.",
  staySubtitle: "Alguém vai apertar.",
  hintCamp: "Alguém acampou aqui. Abra o baú.",
  hintDig: "Nunca cave reto para baixo.",
  hintLectern: "Há algo escrito no atril.",
  hintJump: "Pule no portal.",
  hintMeet: "Alguém está esperando por você.",
  objChest: "Confira o baú",
  objSword: "Fabrique uma espada",
  objEyes: "Fabrique olhos de Ender",
  objThrow: "Lance um olho de Ender",
  objDig: "Cave para baixo",
  objFrame: "Complete a moldura do portal",
  objJump: "Pule no portal",
  objDiary: "Leia o diário no atril",
  advStrike: "Hora de Atacar!",
  advGetaway: "O começo do fim",
  subChest: "Baú se abre",
  subPage: "Página vira",
  subBreak: "Bloco quebrado",
  subThrow: "Olho de Ender lançado",
  subShatter: "Olho de Ender se quebra",
  subWhisper: "Algo sussurra",
  controlsTitle: "Controles",
  paused: "Jogo pausado",
  play: "Jogar",
  resume: "Voltar ao jogo",
  leave: "Sair para o painel",
  ctrlMove: "WASD — mover",
  ctrlJump: "Espaço — pular (no ar com élitros: planar)",
  ctrlSneak: "Shift — agachar",
  ctrlSprint: "Ctrl — correr",
  ctrlAttack: "Clique esquerdo — golpear / minerar",
  ctrlUse: "Clique direito — usar (segurar: puxar o arco, comer)",
  ctrlHotbar: "1-9 / roda — barra rápida",
  ctrlInventory: "E — inventário",
  ctrlPause: "Esc — pausa",
  ctrlTouch: "Polegar esquerdo: mover. Arraste à direita: olhar. Botões: golpear, usar, pular, agachar, correr, inventário e pausa.",
  touchAttack: "Golpear",
  touchUse: "Usar",
  touchJump: "Pular",
  touchPause: "Pausa",
  touchInventory: "Inventário",
  touchSneak: "Agachar",
  touchSprint: "Correr",
  chestBackups: "Baú: tesouro",
  inventoryHelp: "Clique esquerdo: pegar ou soltar uma pilha. Clique direito: pegar metade ou soltar um. Shift + clique: mandar para o outro lado. Arraste uma pilha para distribuí-la.",
  librarian: "Bibliotecário",
  librarianHmm: "hmm. (o bibliotecário olha para você como se soubesse de algo)",
  soldOut: "Vendido",
  mapLegend: "■ acampamento · ▲ vila · ◆ portal em ruínas · ? caverna",
  mapNoSignal: "O mapa gira sem rumo. Ele só funciona no Overworld.",
  deathTitle: "Você morreu!",
  deathScore: "Pontuação:",
  respawn: "Renascer",
  noise: "Barulho",
  lastSeen: "Última conexão de {ghost}: há {days} dias.",
  lastSeenToday: "Última conexão de {ghost}: hoje.",
  villager: "Aldeão",
  nitwit: "Palerma",
  craftingTable: "Bancada de Trabalho",
  lectern: "Atril",
  portalGap: "Falta um bloco de obsidiana",
  portalFrame: "Portal em ruínas",
  bed: "Cama",
  button: "Botão de Pedra",
  frame: "Moldura do Portal do End",
  gateway: "Passagem do End",
  itemFrame: "Moldura de Item",
  commandBlock: "Bloco de Comando",
  itemRod: "Vara de Blaze",
  itemArrow: "Flecha",
  itemEmerald: "Esmeralda",
  itemMap: "Mapa",
  itemRegister: "Registro de admins",
  itemFlint: "Pederneira",
  itemObsidian: "Obsidiana",
  itemElytra: "Élitros",
  itemGold: "Pepita de Ouro",
  itemDirt: "Terra",
  hintSword: "Fabrique uma espada na bancada.",
  hintObsidian: "Segure obsidiana para preencher o buraco.",
  hintFlint: "Acenda-o com a pederneira.",
  hintNotYet: "Ainda não. Você ainda precisa de varas de blaze do Nether.",
  hintEyeKnown: "O olho já mostrou o caminho para você.",
  hintEyes: "De volta à bancada: varas viram pó, pó vira olhos.",
  hintThrowEye: "Use um olho de Ender (clique direito).",
  hintCrystalsBow: "Atire nos cristais com o arco: segure o clique direito e solte.",
  hintNether: "O Nether. Está quente aqui.",
  hintFortress: "A fortaleza fica do outro lado da lava. Blazes a protegem.",
  hintRodsDone: "Três varas. Volte pelo portal.",
  hintQuiet: "Agache-se (Shift). Tem algo aqui embaixo escutando.",
  hintGatewayPearl: "Jogue uma pérola de Ender na passagem.",
  hintNoPearl: "Acabaram as pérolas. Os endermen as deixam cair.",
  hintElytra: "Pule no vazio e pule de novo no ar para planar.",
  hintEndCity: "Uma cidade do End. Suba a escada da torre: o admin deixou os élitros no navio.",
  hintFramesUse: "Use os olhos de Ender nas molduras vazias.",
  hintFollowEye: "O olho sabe onde fica o portal. Siga-o.",
  objRuined: "Acenda o portal em ruínas",
  objMap: "Consiga o mapa do bibliotecário",
  objCave: "O que tem na caverna?",
  objQuiet: "Não faça barulho",
  objButton: "Aperte o botão",
  objRods: "Consiga varas de blaze",
  objReturn: "Volte pelo portal",
  objGhast: "Devolva a bola de fogo do ghast",
  objGatewayPearl: "Ou jogar sua pérola na passagem?",
  objElytra: "Encontre os élitros",
  objIslet: "Plane até a ilhota",
  ghostPortal: "quase terminei. faltaram dois blocos.",
  ghostBack: "agora os olhos. você sabe onde fica a bancada.",
  ghostBlaze: "blazes não perdoam. eu também não perdoava quem pedia OP.",
  ghostKeepInventory: "keepInventory ativado. de nada.",
  ghostShulker: "shulkers te dão um voo grátis. o pouso é cobrado à parte.",
  ghostBed: "eu avisei.",
  ghostAncient: "então você também encontrou a cidade.",
  voiceWill: "será que ele vai apertar?",
  voiceAlways: "eles sempre apertam.",
  voiceAgain: "de novo.",
  voiceLearning: "deixa. ele está aprendendo.",
  voiceNo: "não.",
  voiceDone: "…bom, agora já foi.",
  voiceAlmost: "quase lá.",
  voiceChoose: "agora vem a parte difícil: escolher.",
  creeperDenied: "por que todo mundo vai embora?",
  villagerHmm: "Aldeão: hmm.",
  nitwitHmm: "Palerma: hmm?",
  farmerHmm: "Agricultor: hmm. (ele quer 22 gravetos por uma esmeralda. vocês dois sabem que isso é um assalto)",
  signIncidents: "Dias sem um\ncreeper explodir\na minha casa:\n0",
  signRestart: "Em breve:\nmeu castelo.",
  signBackups: "TESOURO.\nNÃO MEXA.\n—Bfuuny",
  signBorder: "Fim do mapa.\nAcabou o orçamento.\n—{ghost}",
  signToast: "Toast\n(saudades)",
  signCave: "Não.\n(sério)",
  signQuiet: "Silêncio, por favor.\nO vizinho de baixo\nnão tem olhos,\nmas ouve TUDO.",
  signCasi: "quase.\n—{ghost}",
  signBed: "Não durma aqui.\n(aprendi do jeito difícil)",
  signDiamond: "Foi aqui que eu perdi\no diamante.\nNão procure.\nEu já procurei.",
  signUptime: "Volto em\n5 minutos.\n—{ghost}\n(há {days} dias)",
  diary5: "Desci até a cidade lá embaixo. A moldura de lá é igual a esta, só que maior.\nAlguém a desligou de propósito.",
  register1: "Registro de admins\n\n~~Bfuuny~~ apertou o botão. Duas vezes.\n~~BlasterDaster~~ apertou o botão.\n~~Ketbome~~ apertou o botão.",
  registerLoop: "~~{ghost}~~ apertou o botão.",
  register2: "Cada nome riscado é um admin que apertou o botão e nunca voltou.\nQuem risca? Os aldeões.\nhmm.",
  bookAdmin2011: "Caderno",
  bookAdmin2011By: "por BlasterDaster",
  admin2011a: "Se você chegou até aqui embaixo, é um dos curiosos.\nO primeiro botão não estava em nenhum painel. Estava aqui.",
  admin2011b: "Os portais são mais antigos que os servidores. A gente só os liga.\nNão faça barulho. Ele escuta.\n— BlasterDaster",
  bookStop: "Bloco de Comando",
  stopBook: "Comando: /stop\n\n(nunca executei)",
  deathLava: "confundiu lava com jacuzzi",
  deathVoid: "caiu no vazio. Ainda está caindo. Manda um abraço.",
  deathFall: "tentou o truque do balde de água. Sem balde.",
  deathBed: "foi dormir no Nether. A cama discordou.",
  deathWarden: "espirrou na cidade antiga. O Defensor não disse saúde.",
  deathEnderman: "olhou um enderman nos olhos. O enderman olhou de volta.",
  deathBlaze: "perguntou a um blaze se ele queimava. Queimava.",
  deathDragon: "foi morto pelo Dragão do Ender enquanto tirava um print pra se exibir",
  deathBreath: "cheirou o bafo do dragão. Ninguém merece.",
  deathElytra: "bateu numa parede a toda velocidade. A parede está bem.",
  deathShulker: "levitou até o céu. Depois parou de levitar.",
  deathSilverfish: "foi devorado por uma traça. Uma traça.",
  deathGhast: "teve uma recepção calorosa",
  advDeeper: "O buraco é mais embaixo",
  advButton: "O que esse botão faz?",
  advRods: "Brincando com fogo",
  advReturn: "Recepção calorosa",
  advSky: "Ao infinito e além!",
  subExplosion: "Explosão",
  subBow: "Arco dispara",
  subArrow: "Flecha atinge",
  subEat: "Comendo",
  subHurtPlayer: "Jogador ferido",
  subVillager: "Aldeão murmura",
  subSheep: "Ovelha bale",
  subPig: "Porco grunhe",
  subHiss: "Creeper sibila",
  subFlint: "Pederneira acende",
  subFireball: "Bola de fogo sibila",
  subBlaze: "Blaze respira",
  subGhast: "Ghast chora",
  subHeartbeat: "Coração do Defensor bate",
  subRoar: "Defensor ruge",
  subShriek: "Emissor de Sculk guincha",
  subSculk: "Sensor de Sculk estala",
  subSqueak: "Traça sibila",
  subZap: "Projétil de Shulker",
  subLevitate: "Levitando",
  subNetherPortal: "Portal se abre",
  deathCreeper: "ganhou um abraço do Kevin",
  creeperGranted: "eu só queria um abraço.",
  mobSlain: "foi morto por {player}",
  pigDown: "caiu. De novo.",
  clickToPlay: "Clique para continuar jogando",
  noWebgl: "Seu navegador não consegue desenhar o jogo em 3D (falta WebGL2). Ative a aceleração de hardware nas configurações, reinicie-o e tente de novo. Enquanto isso, aqui está o final.",
  signBfuunyBed: "Ótimo lugar\npara dormir.\nConfia.\n—Bfuuny",
  signBfuunyShip: "Os élitros bons\nestão no\noutro navio.\n—Bfuuny",
  signBfuunyExit: "SAÍDA\n→\n—Bfuuny",
  bfuunyChest: "kkkkk. é terra. tudo.",
  bfuunyBed: "kkkkk. eu disse pra confiar.",
  ghostWardenHit: "tá batendo nele? no Defensor? que coragem.",
  ghostWarden: "…ok. ninguém nunca tinha feito isso.",
};

export default pt;
