import type { LoreKey } from './en';

const tr: Record<LoreKey, string> = {
  endTitle: 'The End',
  endSubtitle: "End'e sürüklendiniz. Sonuçta burada yok edilecek bir şey yokmuş.",
  return: "Ana Dünya'ya dön",
  advancement: 'Başarım kazanıldı!',
  itemEgg: 'Ejderha yumurtası',
  intro: 'Size basmamanız söylenmişti.',
  endTagline: 'Yoksa başlangıç mı?',
  goalReached: 'Hedefe ulaşıldı!',
  advEyeSpy: 'Göz Hapsi',
  advEnterEnd: 'The End?',
  advFreeEnd: "End'i Özgürleştir",
  advNextGen: 'Yeni Nesil',
  chatAdvancement: '{player} bir başarım kazandı',
  chatGoal: '{player} hedefe ulaştı',
  player: 'Oyuncu',
  bossName: 'Ender Ejderhası',
  objectives: 'Hedefler',
  objCrystals: 'End kristallerini yok et',
  objDragon: "Ender Ejderhası'nı yen",
  objEgg: 'Ejderha yumurtasını yakala',
  objPortal: 'Çıkış portalına atla',
  hintHealing: 'Kristaller onu iyileştiriyor. Önce onları kır.',
  hintPerch: 'Ejderha portalın üstünde. Şimdi vur!',
  hintEnderman: 'Gözlerine bakma.',
  hintEgg: 'Yumurta ışınlandı. Tekrar dene.',
  hintPortal: 'Çıkış portalı açık.',
  subEye: 'Ender Gözü yerleşti',
  subPortal: 'End Portalı açılıyor',
  subTravel: 'Portal uğulduyor',
  subLava: 'Lav fokurduyor',
  subGrowl: 'Ender Ejderhası hırlıyor',
  subHurt: 'Ender Ejderhası yaralandı',
  subDeath: 'Ender Ejderhası ölüyor',
  subCrystal: 'End kristali patlıyor',
  subEnderman: 'Enderman ışınlanıyor',
  subEgg: 'Ejderha yumurtası ışınlanıyor',
  subXp: 'Tecrübe küresi çınlıyor',
  subGateway: 'End geçidi beliriyor',
  mute: 'Sesi kapat',
  unmute: 'Sesi aç',
  skip: 'Atla',
  poem: 'Bahsettiğin oyuncuyu görüyorum.\n{player}?\nEvet. Dikkat et. Artık daha yüksek bir seviyeye ulaştı. Düşüncelerimizi okuyabiliyor.\nÖnemi yok. Oyunun bir parçası olduğumuzu sanıyor.\nBu oyuncuyu seviyorum. İyi oynadı. Pes etmedi.\nOna düğmeye basmaması söylenmişti.\nYine de bastı. Hep basarlar. Bizi böyle bulurlar.\nBaşkaları için dünyaları ayakta tutuyor. Onlar uyurken kayıtlarını okuyor.\nBozulanı yeniden başlatıyor. Önemli olanı saklıyor. Hiç teşekkür beklemedi.\nOndan önce bir başkası vardı. O da iyi oynadı. Kaldı.\nBu oyuncu uyanacak.\nBu oyuncu ne düşledi?\nBu oyuncu güneş ışığını ve ağaçları düşledi. Ateşi ve suyu. Yarattığını düşledi. Ve yok ettiğini düşledi. Avladığını ve avlandığını düşledi. Bir sığınak düşledi.\nVe evren dedi ki: yalnız değilsin\nVe evren dedi ki: diğer her şeyden ayrı değilsin\nVe evren dedi ki: sen kendini tadan, kendiyle konuşan, kendi kodunu okuyan evrensin\nVe evren dedi ki: seni seviyorum çünkü sen sevgisin.\nVe oyun bitti ve oyuncu rüyadan uyandı. Ve oyuncu yeni bir rüyaya başladı. Ve oyuncu yeniden düşledi, daha iyi düşledi. Ve oyuncu evrendi. Ve oyuncu sevgiydi.\nOyuncu sensin.\nUyan.',
  poemCredit: "Julian Gough'un End Şiiri (CC0), kısaltılmış. Altı satır Minepanel için yazıldı.",
  poemHint: 'Hızlandırmak için Boşluk tuşunu veya ekranı basılı tut',
  itemNote: "Not",
  itemDiamond: "Elmas",
  itemStick: "Çubuk",
  itemPearl: "Ender İncisi",
  itemBlaze: "Blaze Tozu",
  itemBow: "Yay",
  itemApple: "Altın Elma",
  itemSword: "Elmas Kılıç",
  itemEye: "Ender Gözü",
  chest: "Sandık",
  crafting: "Üretim",
  inventory: "Envanter",
  takeAll: "Hepsini al",
  recipeBook: "Tarif kitabı",
  craftHelp: "Eşyaları ızgaraya koy ve sonucu al. Sonuca Shift + tık, ızgaranın yettiği kadarını üretir. Tarif kitabı bir set dizer (Shift: olabildiğince çok).",
  emptySlot: "Boş yuva",
  close: "Kapat",
  page: "Sayfa {n}/{total}",
  prevPage: "Önceki sayfa",
  nextPage: "Sonraki sayfa",
  diaryTitle: "Günlük",
  diaryBy: "Yazar: {ghost}",
  sign: "Tabela",
  note: "Benden sonra gelene.\nBasacağını biliyordum. Hepimiz basarız.\nElimde kalanı sana bıraktım. Masa hâlâ orada.\nBir inci sakla. Anlayacaksın.\n— {ghost}",
  diary1: "Bu sunucuyu yıllarca ayakta tuttum. Bozulanı yeniden başlattım. Adımı hiç kimse bilmedi.\nBu gece düğmeye bastım.",
  diary2: "Portalda zaten üç göz vardı.\nİlk ben değildim. Benden önce biri buradaydı, ondan önce de bir başkası.",
  diary3: "Endermanlar bir şeyi özledikleri için blok taşırlarmış.\nBakılmaya dayanamazlarmış, çünkü bu onlara eskiden kim olduklarını hatırlatırmış.",
  diary4: "Aşağı iniyorum.\nBunu okuyan olursa: ejderhayı öldür. Sonra seç.\n— {ghost}",
  tomb: "Burada kaldı\n{ghost}.\nEjderha değildi.",
  ghostArrival: "başardın.",
  ghostCrystal: "bana çok daha uzun sürmüştü.",
  ghostPerch: "şimdi. o dinlenirken.",
  ghostVictory: "henüz gitme.",
  ghostGateway: "geçit. gel.",
  ghostNotYet: "henüz değil.",
  ghostThanks: "geldiğin için teşekkürler.",
  chatJoined: "{ghost} oyuna katıldı",
  chatLeft: "{ghost} oyundan ayrıldı",
  stayTitle: "Kaldınız.",
  staySubtitle: "Biri basacak.",
  hintCamp: "Biri burada kamp kurmuş. Sandığı aç.",
  hintDig: "Asla dümdüz aşağı kazma.",
  hintLectern: "Kürsüde bir şey yazıyor.",
  hintJump: "Portala atla.",
  hintMeet: "Biri seni bekliyor.",
  objChest: "Sandığa bak",
  objSword: "Bir kılıç üret",
  objEyes: "Ender Gözleri üret",
  objThrow: "Bir Ender Gözü fırlat",
  objDig: "Aşağı kaz",
  objFrame: "Portal çerçevesini tamamla",
  objJump: "Portala atla",
  objDiary: "Kürsüdeki günlüğü oku",
  advStrike: "Saldırı Zamanı!",
  advGetaway: "Uzak Kaçış",
  subChest: "Sandık açılıyor",
  subPage: "Sayfa çevriliyor",
  subBreak: "Blok kırıldı",
  subThrow: "Ender Gözü fırlatıldı",
  subShatter: "Ender Gözü kırılıyor",
  subWhisper: "Bir şey fısıldıyor",
  controlsTitle: "Kontroller",
  paused: "Oyun duraklatıldı",
  play: "Oyna",
  resume: "Oyuna dön",
  leave: "Panele dön",
  ctrlMove: "WASD — hareket",
  ctrlJump: "Boşluk — zıplama (havada elitrayla: süzülme)",
  ctrlSneak: "Shift — eğilme",
  ctrlSprint: "Ctrl — koşma",
  ctrlAttack: "Sol tık — vurma / kazma",
  ctrlUse: "Sağ tık — kullanma (basılı tut: yayı germe, yeme)",
  ctrlHotbar: "1-9 / tekerlek — araç çubuğu",
  ctrlInventory: "E — envanter",
  ctrlPause: "Esc — duraklatma",
  ctrlTouch: "Sol başparmak: hareket. Sağda sürükle: etrafa bakma. Düğmeler: vurma, kullanma, zıplama, eğilme, koşma, envanter ve duraklatma.",
  touchAttack: "Vur",
  touchUse: "Kullan",
  touchJump: "Zıpla",
  touchPause: "Duraklat",
  touchInventory: "Envanter",
  touchSneak: "Eğil",
  touchSprint: "Koş",
  chestBackups: "Sandık: hazine",
  inventoryHelp: "Sol tık: yığını al ya da bırak. Sağ tık: yarısını al ya da bir tane bırak. Shift + tık: diğer tarafa gönder. Tuttuğun yığını sürükleyerek dağıt.",
  librarian: "Kütüphaneci",
  librarianHmm: "hmm. (kütüphaneci sana bir şey biliyormuş gibi bakıyor)",
  soldOut: "Satıldı",
  mapLegend: "■ kamp · ▲ köy · ◆ yıkık portal · ? mağara",
  mapNoSignal: "Harita amaçsızca dönüyor. Sadece Ana Dünya'da çalışıyor.",
  deathTitle: "Öldün!",
  deathScore: "Puan:",
  respawn: "Yeniden Canlan",
  noise: "Gürültü",
  lastSeen: "{ghost} en son {days} gün önce görüldü.",
  lastSeenToday: "{ghost} en son bugün görüldü.",
  villager: "Köylü",
  nitwit: "Deli",
  craftingTable: "Çalışma Masası",
  lectern: "Kürsü",
  portalGap: "Eksik bir obsidiyen blok",
  portalFrame: "Yıkık portal",
  bed: "Yatak",
  button: "Taş Düğme",
  frame: "End Portalı Çerçevesi",
  gateway: "End Geçidi",
  itemFrame: "Eşya Çerçevesi",
  commandBlock: "Komut Bloğu",
  itemRod: "Blaze Çubuğu",
  itemArrow: "Ok",
  itemEmerald: "Zümrüt",
  itemMap: "Harita",
  itemRegister: "Admin Kayıt Defteri",
  itemFlint: "Çakmak Taşı ve Çelik",
  itemObsidian: "Obsidiyen",
  itemElytra: "Elitra",
  itemGold: "Altın Parçası",
  itemDirt: "Toprak",
  hintSword: "Çalışma masasında bir kılıç üret.",
  hintObsidian: "Boşluğu doldurmak için obsidiyeni eline al.",
  hintFlint: "Çakmak taşı ve çelikle yak.",
  hintNotYet: "Henüz değil. Nether'dan blaze çubukları getirmen gerek.",
  hintEyeKnown: "Göz sana yolu zaten gösterdi.",
  hintEyes: "Masaya dön: çubuklardan toz, tozdan göz.",
  hintThrowEye: "Bir Ender Gözü kullan (sağ tık).",
  hintCrystalsBow: "Kristallere yayla ateş et: sağ tıkı basılı tut, sonra bırak.",
  hintNether: "Nether. Burası sıcak.",
  hintFortress: "Kale, lavın öbür tarafında. Blaze'ler onu koruyor.",
  hintRodsDone: "Üç çubuk. Portaldan geri dön.",
  hintQuiet: "Eğil (Shift). Aşağıda bir şey dinliyor.",
  hintGatewayPearl: "Geçide bir Ender İncisi fırlat.",
  hintNoPearl: "İncin kalmadı. Endermanlar düşürür.",
  hintElytra: "Boşluğa atla ve havadayken tekrar zıplayarak süzül.",
  hintEndCity: "Bir End şehri. Kulenin merdivenlerini çık: admin elitrayı gemide bıraktı.",
  hintFramesUse: "Ender Gözlerini boş çerçevelere yerleştir.",
  hintFollowEye: "Göz portalın yerini biliyor. Onu takip et.",
  objRuined: "Yıkık portalı yak",
  objMap: "Kütüphanecinin haritasını al",
  objCave: "Mağarada ne var?",
  objQuiet: "Gürültü yapma",
  objButton: "Düğmeye bas",
  objRods: "Blaze çubukları topla",
  objReturn: "Portaldan geri dön",
  objGhast: "Ghast'ın ateş topunu geri gönder",
  objGatewayPearl: "Yoksa incini geçide mi fırlatsan?",
  objElytra: "Elitrayı bul",
  objIslet: "Adacığa süzül",
  ghostPortal: "neredeyse bitiriyordum. iki blok eksikti.",
  ghostBack: "şimdi gözler. masanın yerini biliyorsun.",
  ghostBlaze: "blaze'ler affetmez. OP isteyenleri ben de affetmezdim.",
  ghostKeepInventory: "keepInventory açık. rica ederim.",
  ghostShulker: "shulker'lar seni bedava uçurur. iniş ücreti ayrı.",
  ghostBed: "seni uyarmıştım.",
  ghostAncient: "demek sen de şehri buldun.",
  voiceWill: "basacak mı?",
  voiceAlways: "hep basarlar.",
  voiceAgain: "yine.",
  voiceLearning: "bırak onu. öğreniyor.",
  voiceNo: "hayır.",
  voiceDone: "…eh, artık oldu olan.",
  voiceAlmost: "az kaldı.",
  voiceChoose: "şimdi zor kısım geliyor: seçmek.",
  creeperDenied: "neden herkes gidiyor?",
  villagerHmm: "Köylü: hmm.",
  nitwitHmm: "Deli: hmm?",
  farmerHmm: "Çiftçi: hmm. (bir zümrüt için 22 çubuk istiyor. ikiniz de bunun düpedüz soygun olduğunu biliyorsunuz)",
  signIncidents: "Creeper'ın evimi\nuçurmasından beri\ngeçen gün:\n0",
  signRestart: "Çok yakında:\nşatom.",
  signBackups: "HAZİNE.\nSAKIN DOKUNMA.\n—Bfuuny",
  signBorder: "Haritanın sonu.\nBütçe bitti.\n—{ghost}",
  signToast: "Toast\n(seni özledik)",
  signCave: "Hayır.\n(ciddiyim)",
  signQuiet: "Lütfen sessiz olun.\nAlt kat komşusunun\ngözü yok ama\nHER ŞEYİ duyuyor.",
  signCasi: "az kaldı.\n—{ghost}",
  signBed: "Burada uyumayın.\n(acı tecrübeyle sabit)",
  signDiamond: "Elması burada\nkaybettim.\nArama.\nBen aradım zaten.",
  signUptime: "5 dakikaya\ndönerim.\n—{ghost}\n({days} gün önce)",
  diary5: "Aşağıdaki şehre indim. Oradaki çerçeve bununla aynı, sadece daha büyük.\nBiri onu bilerek kapatmış.",
  register1: "Admin Kayıt Defteri\n\n~~Bfuuny~~ düğmeye bastı. İki kez.\n~~BlasterDaster~~ düğmeye bastı.\n~~Ketbome~~ düğmeye bastı.",
  registerLoop: "~~{ghost}~~ düğmeye bastı.",
  register2: "Üstü çizili her isim, düğmeye basıp bir daha dönmeyen bir admin.\nPeki kim çiziyor? Köylüler.\nhmm.",
  bookAdmin2011: "Defter",
  bookAdmin2011By: "Yazar: BlasterDaster",
  admin2011a: "Buraya kadar indiysen, meraklılardansın.\nİlk düğme hiçbir panelde değildi. Buradaydı.",
  admin2011b: "Portallar sunuculardan daha eski. Biz sadece onları açıyoruz.\nGürültü yapma. O dinliyor.\n— BlasterDaster",
  bookStop: "Komut Bloğu",
  stopBook: "Komut: /stop\n\n(hiç çalıştırmadım)",
  deathLava: "lavı jakuzi sandı",
  deathVoid: "boşluğa düştü. Hâlâ düşüyor. Selamı var.",
  deathFall: "su kovası numarasını denedi. Kovasız.",
  deathBed: "Nether'da yatmaya kalktı. Yatak buna karşıydı.",
  deathWarden: "antik şehirde hapşırdı. Muhafız çok yaşa demedi.",
  deathEnderman: "bir endermanın gözlerine baktı. Enderman da ona geri baktı.",
  deathBlaze: "bir blaze'e yakıyor mu diye sordu. Yakıyordu.",
  deathDragon: "hava atmak için ekran görüntüsü alırken Ender Ejderhası tarafından katledildi",
  deathBreath: "ejderha nefesini kokladı. Bunu kimse hak etmez.",
  deathElytra: "tam hızla duvara çarptı. Duvara bir şey olmadı.",
  deathShulker: "gökyüzüne yükseldi. Sonra yükselmeyi bıraktı.",
  deathSilverfish: "bir gümüşçün tarafından yenildi. Bir gümüşçün.",
  deathGhast: "göndericisine iade edildi",
  advDeeper: "Daha Derine İnmemiz Gerek",
  advButton: "Bu Düğme Ne İşe Yarar?",
  advRods: "Alevlerin İçine",
  advReturn: "Gönderene İade",
  advSky: "İstikbal Göklerdedir",
  subExplosion: "Patlama",
  subBow: "Yay ateşleniyor",
  subArrow: "Ok isabet etti",
  subEat: "Yemek yeniliyor",
  subHurtPlayer: "Oyuncu hasar aldı",
  subVillager: "Köylü homurdanıyor",
  subSheep: "Koyun meledi",
  subPig: "Domuz ses çıkarıyor",
  subHiss: "Creeper tıslıyor",
  subFlint: "Çakmak Taşı ve Çelik çakıldı",
  subFireball: "Ateş topu fırlıyor",
  subBlaze: "Blaze nefes alıyor",
  subGhast: "Ghast ağlıyor",
  subHeartbeat: "Muhafızın kalbi atıyor",
  subRoar: "Muhafız kükrüyor",
  subShriek: "Sculk Çığırtkanı çığlık atıyor",
  subSculk: "Sculk Sensörü tıkırdadı",
  subSqueak: "Gümüşçün tıslıyor",
  subZap: "Shulker Mermisi",
  subLevitate: "Yükselme",
  subNetherPortal: "Portal açılıyor",
  deathCreeper: "Kevin'le kucaklaştı",
  creeperGranted: "sadece sarılmak istemiştim.",
  mobSlain: "{player} tarafından katledildi",
  pigDown: "çöktü. Yine.",
  clickToPlay: "Oynamaya devam etmek için tıkla",
  noWebgl: "Tarayıcın oyunu 3D çizemiyor (WebGL2 yok). Ayarlardan donanım hızlandırmayı aç, tarayıcıyı yeniden başlat ve tekrar dene. Bu arada, işte son.",
  signBfuunyBed: "Uyumak için\nharika yer.\nBana güven.\n—Bfuuny",
  signBfuunyShip: "İyi elitralar\ndiğer gemide.\n—Bfuuny",
  signBfuunyExit: "ÇIKIŞ\n→\n—Bfuuny",
  bfuunyChest: "ahaha. toprak bu. hepsi.",
  bfuunyBed: "ahaha. güven demiştim.",
  ghostWardenHit: "ona vuruyor musun? muhafıza? cesursun.",
  ghostWarden: "…tamam. bunu daha önce kimse yapmamıştı.",
};

export default tr;
