import type { LoreKey } from './en';

const tr: Record<LoreKey, string> = {
  endTitle: 'The End',
  endSubtitle: "End'e sürüklendiniz. Sonuçta burada yok edilecek bir şey yokmuş.",
  return: "Ana Dünya'ya dön",
  advancement: 'Başarım kazanıldı!',
  itemEgg: 'Ejderha yumurtası',
  intro: "Ketbome'un 47 numaralı test sunucusu. Durum: neredeyse bitti.",
  endTagline: 'Yoksa başlangıç mı?',
  goalReached: 'Hedefe ulaşıldı!',
  advEyeSpy: 'Göz Hapsi',
  advEnterEnd: 'The End?',
  advFreeEnd: "End'i Özgürleştir",
  advNextGen: 'Yeni Nesil',
  chatAdvancement: '{player} bir başarım kazandı',
  chatGoal: '{player} hedefe ulaştı',
  player: 'Oyuncu',
  bossName: 'Ender Ejderhası',
  objectives: 'Hedefler',
  objCrystals: 'End kristallerini yok et',
  objDragon: "Ender Ejderhası'nı yen",
  objEgg: 'Ejderha yumurtasını yakala',
  objPortal: 'Çıkış portalına atla',
  hintHealing: 'Kristaller onu iyileştiriyor. Önce onları kır.',
  hintPerch: 'Ejderha portalın üstünde. Şimdi vur!',
  hintTakeoff: 'Ejderha havalanıyor. Havadayken oklar ona işler.',
  hintCharge: 'Ejderha üstüne dalıyor. Yana kaç!',
  hintArrowsBounce: 'Otururken oklar ondan seker. Kılıcı kullan.',
  hintEnraged: 'Ejderha öfkelendi!',
  hintEnderman: 'Gözlerine bakma.',
  hintEgg: 'Yumurta ışınlandı. Tekrar dene.',
  hintPortal: 'Çıkış portalı açık.',
  subEye: 'Ender Gözü yerleşti',
  subPortal: 'End Portalı açılıyor',
  subTravel: 'Portal uğulduyor',
  subLava: 'Lav fokurduyor',
  subGrowl: 'Ender Ejderhası hırlıyor',
  subHurt: 'Ender Ejderhası yaralandı',
  subDeath: 'Ender Ejderhası ölüyor',
  subCrystal: 'End kristali patlıyor',
  subEnderman: 'Enderman ışınlanıyor',
  subEgg: 'Ejderha yumurtası ışınlanıyor',
  subXp: 'Tecrübe küresi çınlıyor',
  subGateway: 'End geçidi beliriyor',
  mute: 'Sesi kapat',
  unmute: 'Sesi aç',
  skip: 'Atla',
  poem: "Bahsettiğin oyuncuyu görüyorum.\n{player}?\nEvet. Dikkat et. Artık daha yüksek bir seviyeye ulaştı. Düşüncelerimizi okuyabiliyor.\nÖnemi yok. Oyunun bir parçası olduğumuzu sanıyor.\nBu oyuncuyu seviyorum. İyi oynadı. Pes etmedi.\nHiç bitmemiş bir sunucuya geldi. Yine de oynadı.\nArkadaşları oynasın diye dünyalar kuruyor. Onlar uyurken açık tutuyor.\nBozulanı onarıyor. Önemli olanı saklıyor. Hiç teşekkür beklemedi.\nOndan önce üç kişi vardı. Biri inşa etti. Biri kazandı. Biri tekrar tekrar öldü ve her seferinde güldü.\nHâlâ buradalar. Onu bekliyorlardı.\nBu oyuncu ne düşledi?\nBu oyuncu güneş ışığını ve ağaçları düşledi. Ateşi ve suyu. Yarattığını düşledi. Ve yok ettiğini düşledi. Avladığını ve avlandığını düşledi. Bir sığınak düşledi.\nVe evren dedi ki: yalnız değilsin\nVe evren dedi ki: diğer her şeyden ayrı değilsin\nVe evren dedi ki: sen kendini tadan, kendiyle konuşan, kendi kodunu okuyan evrensin\nVe evren dedi ki: seni seviyorum çünkü sen sevgisin.\nVe oyun bitti ve oyuncu rüyadan uyandı. Ve oyuncu yeni bir rüyaya başladı. Ve oyuncu yeniden düşledi, daha iyi düşledi. Ve oyuncu evrendi. Ve oyuncu sevgiydi.\nOyuncu sensin.\nUyan.",
  poemCredit: "Julian Gough'un End Şiiri (CC0), kısaltılmış. Beş satır Minepanel için yazıldı.",
  poemHint: 'Hızlandırmak için Boşluk tuşunu veya ekranı basılı tut',
  itemNote: "Not",
  itemDiamond: "Elmas",
  itemStick: "Çubuk",
  itemPearl: "Ender İncisi",
  itemBlaze: "Blaze Tozu",
  itemBow: "Yay",
  itemApple: "Altın Elma",
  itemSword: "Elmas Kılıç",
  itemEye: "Ender Gözü",
  chest: "Sandık",
  crafting: "Üretim",
  inventory: "Envanter",
  takeAll: "Hepsini al",
  recipeBook: "Tarif kitabı",
  craftHelp: "Eşyaları ızgaraya koy ve sonucu al. Sonuca Shift + tık, ızgaranın yettiği kadarını üretir. Tarif kitabı bir set dizer (Shift: olabildiğince çok).",
  emptySlot: "Boş yuva",
  close: "Kapat",
  page: "Sayfa {n}/{total}",
  prevPage: "Önceki sayfa",
  nextPage: "Sonraki sayfa",
  diaryTitle: "Günlük",
  diaryBy: "Yazar: {ghost}",
  sign: "Tabela",
  note: "Sunucu #47. Bunu bitireceğim, söz.\nElimdekini sandığa bıraktım. Masa hâlâ orada.\nBfuuny'nin sandıklarına güvenme. BlasterDaster'la yarışma. Kaybedersin.\nBir inci sakla. Anlayacaksın.\n— {ghost}",
  diary1: "Sunucu #47, 1. gün. Kamp hazır. Sırada kale var.\n(kale hiç gelmedi)",
  diary2: "3. gün. Portalda zaten üç göz vardı.\nBlasterDaster tabii ki önce gelmiş. Bir tabela bırakmış: \"çok yavaş\".",
  diary3: "Endermanlar bloklarımı çalıp duruyor. Sanırım onlar da bir şey inşa ediyor.\nMuhtemelen benden iyi.",
  diary4: "Kesin sunucuyu inşa etmek için End'e gidiyorum.\nEjderhayı öldür, sonra geçide gir. Bekliyoruz.\n— {ghost}",
  tomb: "Burada Bfuuny yatıyor.\nYine.\n(ölüm #312: ejderhaya el salladı)",
  ghostArrival: "başardın.",
  ghostCrystal: "bana çok daha uzun sürmüştü.",
  ghostPerch: "şimdi. o dinlenirken.",
  ghostVictory: "henüz gitme.",
  ghostGateway: "geçit. hepimiz orada bekliyoruz. bir inci getir.",
  ghostNotYet: "o enderman bfuuny'nin mezarını bekliyor. birinin beklemesi lazım.",
  ghostThanks: "Minepanel'i kullandığın için teşekkürler. cidden. üç kişiyiz ve bol kahve.",
  chatJoined: "{ghost} oyuna katıldı",
  chatLeft: "{ghost} oyundan ayrıldı",
  stayTitle: "GG",
  staySubtitle: "Bfuuny yine öldü.",
  hintCamp: "Biri burada kamp kurmuş. Sandığı aç.",
  hintDig: "Asla dümdüz aşağı kazma.",
  hintLectern: "Kürsüde bir şey yazıyor.",
  hintJump: "Portala atla.",
  hintMeet: "Adacığa süzül. Seni bekliyorlar.",
  objChest: "Sandığa bak",
  objSword: "Bir kılıç üret",
  objEyes: "Ender Gözleri üret",
  objThrow: "Bir Ender Gözü fırlat",
  objDig: "Aşağı kaz",
  objFrame: "Portal çerçevesini tamamla",
  objJump: "Portala atla",
  objDiary: "Kürsüdeki günlüğü oku",
  advStrike: "Saldırı Zamanı!",
  advGetaway: "Uzak Kaçış",
  subChest: "Sandık açılıyor",
  subPage: "Sayfa çevriliyor",
  subBreak: "Blok kırıldı",
  subThrow: "Ender Gözü fırlatıldı",
  subShatter: "Ender Gözü kırılıyor",
  subWhisper: "Bir şey fısıldıyor",
  controlsTitle: "Kontroller",
  paused: "Oyun duraklatıldı",
  play: "Oyna",
  resume: "Oyuna dön",
  leave: "Panele dön",
  ctrlMove: "WASD — hareket",
  ctrlJump: "Boşluk — zıplama (havada elitrayla: süzülme)",
  ctrlSneak: "Shift — eğilme",
  ctrlSprint: "Ctrl — koşma",
  ctrlAttack: "Sol tık — vurma / kazma",
  ctrlUse: "Sağ tık — kullanma, blok koyma (basılı tut: yayı germe, yeme)",
  ctrlHotbar: "1-9 / tekerlek — araç çubuğu",
  ctrlInventory: "E — envanter",
  ctrlPause: "Esc — duraklatma",
  menuSubtitle: "End macerası",
  menuSplash: "Neredeyse bitti!",
  menuBack: "Geri",
  ctrlScreenshot: "F2 — ekran görüntüsü",
  ctrlMute: "M — sesi aç/kapat",
  ctrlTouch: "Sol başparmak: hareket. Sağda sürükle: etrafa bakma. Düğmeler: vurma, kullanma, zıplama, eğilme, koşma, envanter ve duraklatma.",
  touchAttack: "Vur",
  touchUse: "Kullan",
  touchJump: "Zıpla",
  touchPause: "Duraklat",
  touchInventory: "Envanter",
  touchSneak: "Eğil",
  touchSprint: "Koş",
  chestBackups: "Sandık: hazine",
  inventoryHelp: "Sol tık: yığını al ya da bırak. Sağ tık: yarısını al ya da bir tane bırak. Shift + tık: diğer tarafa gönder. Tuttuğun yığını sürükleyerek dağıt.",
  librarian: "Kütüphaneci",
  librarianHmm: "hmm. (kütüphaneci sana bir şey biliyormuş gibi bakıyor)",
  soldOut: "Satıldı",
  mapLegend: "■ kamp · ▲ köy · ◆ yıkık portal · ? mağara",
  mapNoSignal: "Harita amaçsızca dönüyor. Sadece Ana Dünya'da çalışıyor.",
  deathTitle: "Öldün!",
  deathScore: "Puan:",
  respawn: "Yeniden Canlan",
  noise: "Gürültü",
  lastSeen: "{ghost} en son {days} gün önce görüldü.",
  lastSeenToday: "{ghost} en son bugün görüldü.",
  villager: "Köylü",
  nitwit: "Deli",
  craftingTable: "Çalışma Masası",
  lectern: "Kürsü",
  portalGap: "Eksik bir obsidiyen blok",
  portalFrame: "Yıkık portal",
  bed: "Yatak",
  button: "Taş Düğme",
  frame: "End Portalı Çerçevesi",
  gateway: "End Geçidi",
  itemFrame: "Eşya Çerçevesi",
  commandBlock: "Komut Bloğu",
  itemRod: "Blaze Çubuğu",
  itemArrow: "Ok",
  itemEmerald: "Zümrüt",
  itemMap: "Harita",
  itemRegister: "Bfuuny'nin Ölüm Kaydı",
  itemFlint: "Çakmak Taşı ve Çelik",
  itemObsidian: "Obsidiyen",
  itemElytra: "Elitra",
  itemGold: "Altın Külçe",
  itemDirt: "Toprak",
  hintSword: "Çalışma masasında bir kılıç üret.",
  hintObsidian: "Boşluğu doldurmak için obsidiyeni eline al.",
  hintFlint: "Çakmak taşı ve çelikle yak.",
  hintNotYet: "Henüz değil. Nether'dan blaze çubukları getirmen gerek.",
  hintEyeKnown: "Göz sana yolu zaten gösterdi.",
  hintEyes: "Masaya dön: çubuklardan toz, tozdan göz.",
  hintThrowEye: "Bir Ender Gözü kullan (sağ tık).",
  hintCrystalsBow: "Kristallere yayla ateş et: sağ tıkı basılı tut, sonra bırak.",
  hintNether: "Nether. Burası sıcak.",
  hintFortress: "Kale, lavın öbür tarafında. Blaze'ler onu koruyor.",
  hintRodsDone: "Üç çubuk. Portaldan geri dön.",
  hintQuiet: "Eğil (Shift). Aşağıda bir şey dinliyor.",
  hintGatewayPearl: "Geçide bir Ender İncisi fırlat.",
  hintNoPearl: "İncin kalmadı. Endermanlar düşürür.",
  hintElytra: "Boşluğa atla ve havadayken tekrar zıplayarak süzül.",
  hintEndCity: "Bir End şehri. Kulenin merdivenlerini çık: admin elitrayı gemide bıraktı.",
  hintFramesUse: "Ender Gözlerini boş çerçevelere yerleştir.",
  hintFollowEye: "Göz portalın yerini biliyor. Onu takip et.",
  objRuined: "Yıkık portalı yak",
  objMap: "Kütüphanecinin haritasını al",
  objCave: "Mağarada ne var?",
  objQuiet: "Gürültü yapma",
  objButton: "Düğmeye bas",
  objRods: "Blaze çubukları topla",
  objReturn: "Portaldan geri dön",
  objGhast: "Ghast'ın ateş topunu geri gönder",
  objGatewayPearl: "Yoksa incini geçide mi fırlatsan?",
  objElytra: "Elitrayı bul",
  objIslet: "Adacığa süzül",
  ghostPortal: "neredeyse bitiriyordum. iki blok eksikti.",
  ghostBack: "şimdi gözler. masanın yerini biliyorsun.",
  ghostBlaze: "blaze'ler affetmez. ben de admin olmak isteyenleri affetmezdim.",
  ghostKeepInventory: "burada ölünce eşyalarını kaybetmiyorsun. rica ederim.",
  ghostShulker: "shulker'lar seni bedava uçurur. iniş ücreti ayrı.",
  ghostBed: "seni uyarmıştım.",
  ghostAncient: "demek sen de şehri buldun.",
  creeperDenied: "neden herkes gidiyor?",
  villagerHmm: "Köylü: hmm.",
  nitwitHmm: "Deli: hmm?",
  farmerHmm: "Çiftçi: hmm. (bir zümrüde bir havuç teklif ediyor. dost fiyatı diyor)",
  signIncidents: "Creeper'ın evimi\nuçurmasından beri\ngeçen gün:\n0",
  signRestart: "Çok yakında:\nşatom.",
  signBackups: "HAZİNE.\nSAKIN DOKUNMA.\n—Bfuuny",
  signBorder: "Haritanın sonu.\nBütçe bitti.\n—{ghost}",
  signToast: "Sunucunun maskotu:\ntavşan.\nBfuuny'den daha faydalı.",
  signCave: "Hayır.\n(ciddiyim)",
  signQuiet: "Lütfen sessiz olun.\nAlt kat komşusunun\ngözü yok ama\nHER ŞEYİ duyuyor.",
  signCasi: "az kaldı.\n—{ghost}",
  signBed: "Burada uyumayın.\n(acı tecrübeyle sabit)",
  signDiamond: "Elması burada\nkaybettim.\nArama.\nBen aradım zaten.",
  signUptime: "5 dakikaya\ndönerim.\n—{ghost}\n({days} gün önce)",
  diary5: "Kadim şehre indim. BlasterDaster, Warden'ı tahta kılıçla öldürdüğünü söylüyor.\nİnanmıyorum. Birazcık inanıyorum.",
  register1: "Bfuuny'nin Ölüm Kaydı\n\n#1 spawn'dan düştü.\n#2 spawn'dan düştü. Yine.\n#58 Nether'da uyudu. \"çok rahat\".\n#128 Kevin'e sarıldı.\n#311 \"sadece lav ne kadar sıcak diye bakıyorum\".",
  register2: "3. sayfadan 40. sayfaya: hep aynı şey.\nSayıyı köylüler tutuyor. Hoşlarına gidiyor gibi.\nhmm.",
  bookAdmin2011: "Pro Rehber",
  bookAdmin2011By: "Yazar: BlasterDaster",
  admin2011a: "BlasterDaster'ın Pro Rehberi, bölüm 1:\nEğil. Koşma. Zıplama. Yüksek sesle nefes alma.\nSenin olmayan bir kalp atışı duyarsan: koş. Hayır, dur. Koşma.",
  admin2011b: "Bölüm 2: başka bir yere ok at. Hep bakmaya gider.\nOnu iki kez öldürdüm. Bfuuny izlerken dört kez öldü.\nNot: çerçevenin yanındaki düğmeye basma. Bu sefer şaka değil.\n— BlasterDaster",
  bookStop: "Komut Bloğu",
  stopBook: "Komut: /give @p diamond 64\n\n(Bfuuny istedi. hayır.)",
  deathLava: "lavı jakuzi sandı",
  deathVoid: "boşluğa düştü. Hâlâ düşüyor. Selamı var.",
  deathFall: "su kovası numarasını denedi. Kovasız.",
  deathBed: "Nether'da yatmaya kalktı. Yatak buna karşıydı.",
  deathWarden: "antik şehirde hapşırdı. Muhafız çok yaşa demedi.",
  deathEnderman: "bir endermanın gözlerine baktı. Enderman da ona geri baktı.",
  deathBlaze: "bir blaze'e yakıyor mu diye sordu. Yakıyordu.",
  deathDragon: "hava atmak için ekran görüntüsü alırken Ender Ejderhası tarafından katledildi",
  deathBreath: "ejderha nefesini kokladı. Bunu kimse hak etmez.",
  deathElytra: "tam hızla duvara çarptı. Duvara bir şey olmadı.",
  deathShulker: "gökyüzüne yükseldi. Sonra yükselmeyi bıraktı.",
  deathSilverfish: "bir gümüşçün tarafından yenildi. Bir gümüşçün.",
  deathGhast: "göndericisine iade edildi",
  advDeeper: "Daha Derine İnmemiz Gerek",
  advButton: "Bu Düğme Ne İşe Yarar?",
  advRods: "Alevlerin İçine",
  advReturn: "Gönderene İade",
  advSky: "İstikbal Göklerdedir",
  subExplosion: "Patlama",
  subBow: "Yay ateşleniyor",
  subArrow: "Ok isabet etti",
  subEat: "Yemek yeniliyor",
  subHurtPlayer: "Oyuncu hasar aldı",
  subVillager: "Köylü homurdanıyor",
  subSheep: "Koyun meledi",
  subPig: "Domuz ses çıkarıyor",
  subHiss: "Creeper tıslıyor",
  subFlint: "Çakmak Taşı ve Çelik çakıldı",
  subFireball: "Ateş topu fırlıyor",
  subBlaze: "Blaze nefes alıyor",
  subGhast: "Ghast ağlıyor",
  subHeartbeat: "Muhafızın kalbi atıyor",
  subRoar: "Muhafız kükrüyor",
  subShriek: "Sculk Çığırtkanı çığlık atıyor",
  subSculk: "Sculk Sensörü tıkırdadı",
  subSqueak: "Gümüşçün tıslıyor",
  subZap: "Shulker Mermisi",
  subLevitate: "Yükselme",
  subNetherPortal: "Portal açılıyor",
  deathCreeper: "Kevin'le kucaklaştı",
  creeperGranted: "sadece sarılmak istemiştim.",
  mobSlain: "{player} tarafından katledildi",
  pigDown: "bunu bekliyordu.",
  clickToPlay: "Oynamaya devam etmek için tıkla",
  noWebgl: "Tarayıcın oyunu 3D çizemiyor (WebGL2 yok). Ayarlardan donanım hızlandırmayı aç, tarayıcıyı yeniden başlat ve tekrar dene. Bu arada, işte son.",
  signBfuunyBed: "Uyumak için\nharika yer.\nBana güven.\n—Bfuuny",
  signBfuunyShip: "İyi elitralar\ndiğer gemide.\n—Bfuuny",
  signBfuunyExit: "ÇIKIŞ\n→\n—Bfuuny",
  bfuunyChest: "ahaha. toprak bu. hepsi.",
  bfuunyBed: "ahaha. güven demiştim.",
  ghostWardenHit: "ona vuruyor musun? muhafıza? cesursun.",
  ghostWarden: "…tamam. bunu daha önce kimse yapmamıştı.",
  itemLog: "Meşe Kütüğü",
  itemPlanks: "Meşe Kalası",
  itemCobble: "Kırıktaş",
  itemNetherrack: "Nether Taşı",
  itemEndStone: "End Taşı",
  itemPickaxe: "Elmas Kazma",
  itemHelmet: "Altın Miğfer",
  piglin: "Piglin",
  armor: "Zırh",
  armorSlot: "Miğfer",
  hintPiglin: "Takas için elinde altın külçe tutup bir piglin'e sağ tıkla.",
  hintHelmet: "Altın miğferi giy (elindeyken sağ tık). Piglinler sadece altına güvenir.",
  hintPearlsLeft: "Üç çubuk. Hâlâ ender incisi lazım: piglinler onları altınla takas ediyor.",
  objPearls: "Piglinlerden ender incisi takas et",
  ghostPiglin: "piglinler. kafanda altın yoksa dost da yok.",
  ghostDarkness: "ışıklar söndü. bu hiçbir zaman iyiye işaret değil.",
  deathSkeleton: "bir iskelet tarafından vuruldu. Gözleri yok. Gerek de duymadı.",
  deathPiglin: "altınsız geldi. Piglinler bunu kişisel algıladı.",
  subEquip: "Teçhizat giyildi",
  subPiglin: "Piglin hırlıyor",
  subSkeleton: "İskelet takırdıyor",
  bfuunyDirt: "gördün mü? hazine olduğunu söylemiştim.",
  introBlaster: "yeni oyuncu. 20'sine bahse girerim önce Kevin yakalar.",
  introBfuuny: "tamam. dün Kevin'e 20 kaybettim.",
  respawnBfuuny: "kulübe hoş geldin. başkan benim.",
  respawnBlaster: "biraz daha pratik yap.",
  buttonBfuuny: "ıı. 'The Rake'i kim davet etti?",
  buttonBlaster: "basma demiştim. arkanda nefes sesi duyarsan, SAKIN dönme.",
  victoryKetbome: "gg! çıkış portalı seni eve götürür.",
  victoryBlaster: "ya da geçide bir inci at. biz oradayız.",
  endKetbome1: "başardın! kesin sunucuya hoş geldin.",
  endKetbome2: "o... neredeyse bitti.",
  endBlaster: "gg. hiç fena değil.",
  endBfuuny: "izleyin, bu atlayışı rahat yaparım",
  endBlaster2: "her. seferinde.",
  endStar: "beğendiysen: GitHub'da bir yıldız, bir katkı ya da sosyal medyada paylaşmak sandığından çok yardımcı olur.",
  endBfuunyBack: "geri geldim. ne kaçırdım?",
  bfuunyDiedKevin: "Kevin tarafından havaya uçuruldu. Sarılmak istiyordu.",
  bfuunyDiedPiglin: "bir piglin tarafından öldürüldü. Miğferi unutmuştu.",
  bfuunyDiedWarden: "sonik yüklü bir çığlıkla yok edildi",
  bfuunyDiedVoid: "dünyadan düştü. Yine.",
  signBlasterSlow: "çok yavaş.\n—BlasterDaster",
  signBlasterRods: "Blaze çubukları: 3/3\n40 saniyede.\n—BlasterDaster",
  signBfuunyGrave: "R.I.P. Bfuuny\n(o iyi)\n(geri gelecek)",
  signServer48: "Sunucu #48\nÇok yakında.\n—Ketbome",
  deathRake: "The Rake ile karşılaştı. Konuşmak istemedi.",
  deathZombie: "bir zombiden sarılmasını istedi. Kevin değildi.",
  deathZombieVillager: "zombi köylüyle takas yapmaya çalıştı. Beyin istedi.",
  deathDrowned: "yüzmeye gitti. Boğulmuşlar cankurtaran değildi.",
  deathSpider: "tavana bakmadı.",
  deathWitch: "bir yabancıdan iksir kabul etti.",
  deathSlime: "minik bir balçığı hafife aldı. Sonra dört tane oldular.",
  deathPhantom: "uyumadı. Ketbome da uyumuyor ama o buna alışkın.",
  deathZombifiedPiglin: "bir zombileşmiş piglin'e vurdu. Sadece birine.",
  deathHoglin: "bir hoglin'e domuzcuk dedi.",
  deathMagmaCube: "üstüne zıplayarak bir magma küpünü söndürmeye çalıştı.",
  deathWitherSkeleton: "bir wither kafatası istedi. İskelet onu saklamak istedi.",
  deathEndermite: "o kadar çok inci attı ki birinden bir şey çıktı.",
  subRake: "Bir şey çığlık atıyor",
  rakeBfuuny: "bunu başka gören oldu mu???",
  rakeBlaster: "söylemiştim. düğme.",
  thanksTitle: "Oynadığın için teşekkürler",
  thanksBody: "Minepanel'i birkaç kişi boş zamanlarında yapıyor ve onu kullanman bile yardımcı oluyor.\nBeğendiysen GitHub'da bir yıldız, bir katkı ya da sosyal medyada paylaşmak daha çok kişiye ulaşmasını sağlar.",
  thanksStar: "GitHub'da yıldız ver",
  thanksClose: "Panele dön",
  subBreath: "Arkanda bir şey nefes alıyor",
  hintSleepDay: "Sadece gece veya fırtına sırasında uyuyabilirsin",
  hintSleepMonsters: "Şimdi dinlenemezsin; yakınlarda canavarlar var",
  ghostSleep: "tüm #47 sunucusu boyunca benden fazla uyudun.",
  advTreasure: "Gerçek hazine",
  advPacifist: "Barışsever",
  advKevin: "Kevin'in arkadaşı",
  advNotAJoke: "Şaka değildi",
  advRake: "Hâlâ nefes alıyorum",
  advNoElytra: "Kanatlara kimin ihtiyacı var",
  lineTreasure: "…sakladın mı? kimse saklamaz.",
  linePacifist: "tek bir enderman bile yok. saygı.",
  lineKevin: "sarılalım mı?",
  lineNotAJoke: "iki kez. İKİ KEZ.",
  lineRake: "hayatta mı kaldın? ben kalamadım.",
  lineNoElytra: "tamam. ben bile yapamadım.",
  thanksServer48: "Sunucu #48'i ziyaret et",
  signServer48Day1: "Sunucu #48. 1. gün.\nBaşladım.\n—Ketbome",
  signServer48Blaster: "Sunucu #48 (benimki).\nBitti.\n—BlasterDaster",
  s48Ketbome: "başladım.",
  s48Blaster: "benimki çoktan bitti.",
  s48Bfuuny: "haritanın kenarı nerede? ha, işte orada.",
  s48Ketbome2: "yarın korkuluk yaparım.",
  guide3a: "BlasterDaster'ın pro rehberi, bölüm 3: Nether.\nGhast'lar kazandığım için ağlıyor.\nPiglin'ler bana indirim yapıyor. Karizmadandır.",
  guide3b: "Lav jakuzi değildir.\nBfuuny bu kısmı okumadı.\nBfuuny okumaz.\n— BlasterDaster",
  register3: "Sayfa 41: misafirler.\n{player}: {deaths}.\nBfuuny seninkilerin sayılmadığını söylüyor.\nSayılıyor.",
  rabbitName: "Pamuk",
  signVillage: "Minepanel Köyü.\nSakinleri paneli\ninşa etmeye yardım etti.\nTeşekkürler!",
  signTempleBfuuny: "Ortaya\nbasmayın.\n(ben bastım)\n—Bfuuny",
  signRuinDesert: "Sunucu #12:\npiramit.\nBir köşe yaptım.\n—Ketbome",
  signRuinTaiga: "Sunucu #23:\nigloo. Kardan olacaktı.\nTopraktan oldu.\n—Ketbome",
  signRuinSwamp: "Sunucu #31:\nbalçık çiftliği.\nŞimdiye kadar balçık: 0.\n—Ketbome",
  signRuinCoast: "Sunucu #40:\nliman.\nTabelayı bitirdim.\n—Ketbome",
  signWreckNote: "Gömülü hazine:\nplajdaki kaktüsün\n3 adım kuzeyi.\n—Bfuuny",
  ghostTreasure: "elmasım! nether'da kaybetmiştim. buraya nasıl geldiğini sorma.",
  advRuins: "Yarım kalan işler",
  ghostRuins: "hepsini gördün. artık neden hiçbir şeyi bitirmediğimi biliyorsun.",
  deathTnt: "ortaya bastı. Bfuuny uyarmıştı.",
  deathCactus: "bir kaktüse yaslandı. Fazla uzun süre.",
  deathGolem: "köyün demir golem'ine vurdu. Golem karşılık verdi.",
  deathRabbit: "Pamuk'a üç kez vurdu. Pamuk affetmez.",
  pelusaBfuuny: "ben bile Pamuk'a bulaşmam.",
  modeTitle: "Mod",
  modeNormal: "Normal",
  modeSpeedrun: "Speedrun",
  modeHardcore: "Hardcore",
  modeBfuuny: "Bfuuny modu",
  modeLocked: "Diğer modları açmak için End'i bir kez kurtar.",
  records: "Rekorlar",
  recordsEmpty: "Bu panelde henüz kimse bitirmedi.",
  recordsBlasterHardcore: "BlasterDaster: \"ben hardcore oynamam. speedrun yaparım.\"",
  recordsYou: "Sen",
  recordsFailed: "Rekorlar yüklenemedi.",
  screenshot: "Ekran görüntüsü",
  screenshotSaved: "Ekran görüntüsü indirilenlere kaydedildi",
  hardcoreOver: "Oyun bitti!",
  hardcoreOverBody: "Hardcore: tek bir can vardı.",
  hardcoreBlaster: "tek can. benim gibi ama daha kötü.",
  bfuunyModeDeath: "ölüm #{bfuuny}. hayatıma hoş geldin.",
  bfuunyModeLaughK: "deftere bir tane daha.",
  bfuunyModeLaughB: "hahaha.",
  raceWin: "tamam. rövanş.",
  raceLose: "çok yavaş.",
  advFaster: "BlasterDaster'dan hızlı",
  runTime: "Süren:",
  runRank: "Sıra #",
  splitNether: "Nether",
  splitStronghold: "Kale",
  splitEnd: "End",
  splitEndcity: "End Şehri",
  ghostPhantoms: "iki gecedir uyumadın. gökyüzündekiler bunu fark ediyor.",
  itemBone: "Kemik",
  golemAngry: "golem'e vurdun. ben buradan izliyorum.",
  wolfTamed: "bir köpeğin var. benim de vardı. BlasterDaster'la gitti.",
  wolfDied: "ben değildim. bu sefer.",
  hintBone: "Bir kemik tut ve evcilleştirmek için bir kurda kullan.",
  pigName: "Pastırma",
};

export default tr;
