services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 25580:8080
    volumes:
      - ../servers:/data
      - ./config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
