name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Check the [roadmap](https://minepanel.ketbome.com/roadmap) first.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the feature you'd like
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: What problem does this feature solve?
      placeholder: Currently I have to... / This would help because...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions you've thought of?

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Server Management
        - UI/UX
        - Mods & Plugins
        - Backups
        - Monitoring
        - Networking
        - Authentication
        - Docker/Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
        - label: I can help test this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the [roadmap](https://minepanel.ketbome.com/roadmap) and this is not already planned
          required: true
        - label: I have searched existing issues and this is not a duplicate
          required: true
