import { Injectable, Logger, OnApplicationBootstrap } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import * as fs from 'fs-extra';
import * as path from 'node:path';
import * as yaml from 'js-yaml';
import { HostContextService } from 'src/common/docker/host-context.service';
import { InstanceSettingsService } from 'src/settings/instance-settings.service';

const execAsync = promisify(exec);

const ROUTER_IMAGE = 'itzg/mc-router:1.46.2';
const CONTAINER_NAME = 'mc-router';
const PANEL_NETWORK = 'minepanel-network';
const GENERATED_HEADER = [
  '# Generated by Minepanel - do not edit by hand.',
  '# Managed from Settings -> Network; changes here are overwritten.',
  '',
  '',
].join('\n');

/**
 * Runs mc-router as its own compose project.
 *
 * It used to be a service in the panel's own compose file behind a `proxy`
 * profile, which meant the panel could never touch it: recreating that stack
 * would recreate the panel mid-command. As a separate project it works exactly
 * like a server does, and its settings move from .env into the UI.
 */
@Injectable()
export class ProxyRouterService implements OnApplicationBootstrap {
  private readonly logger = new Logger(ProxyRouterService.name);
  private readonly DATA_HOST_DIR: string;
  private readonly DATA_HOST_DIR_IS_A_GUESS: boolean;
  private readonly PROJECT_DIR = '/app/data/proxy';

  constructor(
    private readonly configService: ConfigService,
    private readonly instanceSettings: InstanceSettingsService,
    private readonly hostContext: HostContextService,
  ) {
    this.DATA_HOST_DIR = this.configService.get('dataHostDir');
    this.DATA_HOST_DIR_IS_A_GUESS = (this.configService.get<string[]>('unresolvedHostPaths') ?? []).includes('/app/data');
  }

  // On boot the container may be missing (host restarted) or stale (settings
  // changed while the panel was down), so bring it back in line either way.
  async onApplicationBootstrap(): Promise<void> {
    try {
      await this.reconcile();
    } catch (error) {
      this.logger.error('Could not reconcile mc-router on startup', error);
    }
  }

  private getComposePath(): string {
    return path.join(this.PROJECT_DIR, 'docker-compose.yml');
  }

  // Host path, because compose mounts are resolved by the Docker daemon on the
  // host and not inside this container.
  private getHostDataDir(): string {
    return path.join(this.DATA_HOST_DIR, 'proxy');
  }

  async isRunning(): Promise<boolean> {
    try {
      const { stdout } = await execAsync(`docker ps --filter "name=^/${CONTAINER_NAME}$" --format "{{.ID}}"`);
      return stdout.trim().length > 0;
    } catch (error) {
      this.logger.warn('Failed to detect mc-router status', error);
      return false;
    }
  }

  /**
   * True when a router container exists that this service did not create, i.e.
   * one left over from the old `docker compose --profile proxy` setup. Taking it
   * over means stopping someone else's container, so the caller has to confirm.
   */
  async findUnmanagedRouter(): Promise<{ project?: string } | null> {
    try {
      const { stdout } = await execAsync(
        `docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' ${CONTAINER_NAME}`,
      );
      const project = stdout.trim();
      if (!project || project === 'proxy') return null;
      return { project };
    } catch {
      // No such container, which is the normal case.
      return null;
    }
  }

  async generateComposeFile(): Promise<string> {
    const [row, host] = await Promise.all([this.instanceSettings.getRouterSettings(), this.hostContext.get()]);

    // In the split stack the panel is "backend"; in the all-in-one image it is
    // "minepanel". Reading it off our own container avoids guessing.
    const panelHost = host.service || 'backend';
    const basePath = this.configService.get<string>('basePath') || '';

    const environment: Record<string, string> = {
      ROUTES_CONFIG: '/data/routes.json',
      ROUTES_CONFIG_WATCH: 'true',
    };

    if (row.autoScaleEnabled && row.autoScaleToken) {
      Object.assign(environment, {
        AUTO_SCALE_UP: 'true',
        AUTO_SCALE_DOWN: 'true',
        AUTO_SCALE_DOWN_AFTER: row.autoScaleDownAfter,
        AUTO_SCALE_WEBHOOK_URL: `http://${panelHost}:8091${basePath}/servers/autoscale`,
        AUTO_SCALE_WEBHOOK_HEADERS: `Authorization=Bearer ${row.autoScaleToken}`,
        AUTO_SCALE_WEBHOOK_WAKE_TIMEOUT: row.autoScaleWakeTimeout,
        AUTO_SCALE_ASLEEP_MOTD: row.autoScaleAsleepMotd,
        AUTO_SCALE_LOADING_MOTD: row.autoScaleLoadingMotd,
      });
    }

    const extraNetworks = this.parseExtraNetworks(row.extraNetworks);
    const networks: Record<string, unknown> = { [PANEL_NETWORK]: { external: true } };
    for (const name of extraNetworks) {
      networks[name] = { external: true };
    }

    const compose = {
      services: {
        'mc-router': {
          image: ROUTER_IMAGE,
          container_name: CONTAINER_NAME,
          ports: [`${row.proxyPort}:25565`],
          environment,
          volumes: [`${this.getHostDataDir()}:/data`],
          networks: [PANEL_NETWORK, ...extraNetworks],
          restart: 'unless-stopped',
        },
      },
      networks,
    };

    await fs.ensureDir(this.PROJECT_DIR);
    const content = GENERATED_HEADER + yaml.dump(compose, { lineWidth: -1 });
    await fs.writeFile(this.getComposePath(), content);
    return content;
  }

  private parseExtraNetworks(value?: string | null): string[] {
    if (!value) return [];
    return value
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && line !== PANEL_NETWORK);
  }

  async start(): Promise<boolean> {
    // The router reads routes.json off a bind mount, so an unknown host path would put it
    // in a crash loop against an empty directory. Failing here at least says why.
    if (this.DATA_HOST_DIR_IS_A_GUESS) {
      this.logger.error(
        `Refusing to start mc-router: nothing is mounted at /app/data, so "${this.getHostDataDir()}" is a guess and the router would find no routes.json. ` +
          'Mount a host directory or a named volume at /app/data.',
      );
      return false;
    }

    try {
      await this.generateComposeFile();
      await execAsync('docker compose up -d', { cwd: this.PROJECT_DIR });
      this.logger.log('mc-router is up');
      return true;
    } catch (error) {
      this.logger.error('Failed to start mc-router', error);
      return false;
    }
  }

  async stop(): Promise<boolean> {
    try {
      if (!(await fs.pathExists(this.getComposePath()))) {
        return true;
      }
      await execAsync('docker compose down', { cwd: this.PROJECT_DIR });
      this.logger.log('mc-router is down');
      return true;
    } catch (error) {
      this.logger.error('Failed to stop mc-router', error);
      return false;
    }
  }

  /**
   * Bring the container in line with the saved settings. Called on boot and
   * whenever the proxy settings change.
   */
  async reconcile(): Promise<void> {
    const { enabled } = await this.instanceSettings.getProxy();
    const running = await this.isRunning();

    if (enabled && !running) {
      await this.start();
      return;
    }

    if (!enabled && running) {
      // Only stop a router we own; an unmanaged one is the user's to remove.
      if (await this.findUnmanagedRouter()) {
        this.logger.warn('Leaving an unmanaged mc-router container alone');
        return;
      }
      await this.stop();
      return;
    }

    if (enabled && running) {
      // Settings may have changed while it was up.
      await this.start();
    }
  }
}
