const execMock = jest.fn();
jest.mock('node:child_process', () => ({
  exec: (command: string, options: unknown, callback?: (...args: unknown[]) => void) => {
    const done = typeof options === 'function' ? (options as (...args: unknown[]) => void) : callback!;
    const cwd = typeof options === 'function' ? undefined : options;
    Promise.resolve(execMock(command, cwd)).then(
      (result) => done(null, result ?? { stdout: '', stderr: '' }),
      (error) => done(error),
    );
  },
}));

jest.mock('fs-extra', () => ({
  ensureDir: jest.fn().mockResolvedValue(undefined),
  writeFile: jest.fn().mockResolvedValue(undefined),
  pathExists: jest.fn().mockResolvedValue(true),
}));

import * as fs from 'fs-extra';
import * as yaml from 'js-yaml';
import { ProxyService } from './proxy.service';
import { VelocityRuntimeService } from './velocity-runtime.service';

describe('VelocityRuntimeService', () => {
  let instanceSettings: Record<string, jest.Mock>;
  let dockerCompose: { getServerIndex: jest.Mock };
  let service: VelocityRuntimeService;

  const build = (unresolved: string[] = []) =>
    new VelocityRuntimeService(
      { get: jest.fn((key: string) => (key === 'dataHostDir' ? '/srv/minepanel/data' : key === 'unresolvedHostPaths' ? unresolved : undefined)) } as any,
      instanceSettings as any,
      dockerCompose as any,
      new ProxyService({ get: jest.fn() } as any, instanceSettings as any),
    );

  const written = (file: string) => {
    const call = (fs.writeFile as unknown as jest.Mock).mock.calls.find(([target]) => target === file);
    return call?.[1] as string;
  };

  beforeEach(() => {
    jest.clearAllMocks();
    execMock.mockResolvedValue({ stdout: '', stderr: '' });
    instanceSettings = {
      getEdge: jest.fn().mockResolvedValue({ enabled: true, mode: 'velocity', baseDomain: 'mc.example.com' }),
      getRouterSettings: jest.fn().mockResolvedValue({ proxyPort: '25565' }),
      getVelocitySecrets: jest.fn().mockResolvedValue({ forwardingSecret: 'fwd-secret', rconPassword: 'rcon-pass' }),
      getNetwork: jest.fn().mockResolvedValue({ publicIp: '1.2.3.4', lanIp: null }),
    };
    dockerCompose = {
      getServerIndex: jest.fn().mockResolvedValue([
        { id: 'survival', serverType: 'PAPER', velocityEnabled: true, velocityFallbackOrder: 2 },
        { id: 'lobby', serverType: 'PURPUR', minecraftVersion: '1.21.4', velocityEnabled: true, velocityFallbackOrder: 1, proxyHostname: 'hub' },
        { id: 'minigames', serverType: 'PAPER', velocityEnabled: true, velocityFallbackOrder: null },
        { id: 'standalone', serverType: 'PAPER', velocityEnabled: false },
        { id: 'bedrock', edition: 'BEDROCK', velocityEnabled: true },
        // Turned into Fabric while mc-router was the edge: it can no longer forward.
        { id: 'modded', serverType: 'FABRIC', velocityEnabled: true, velocityFallbackOrder: 3 },
      ]),
    };
    service = build();
  });

  describe('compose file', () => {
    it('runs the pinned image on the public port with the server dir bind-mounted from the host', async () => {
      const compose: any = yaml.load(await service.generateComposeFile());
      const velocity = compose.services.velocity;

      expect(velocity.image).toBe('itzg/mc-proxy:2026.9.2-java25');
      expect(velocity.container_name).toBe('mc-velocity');
      expect(velocity.ports).toEqual(['25565:25565']);
      expect(velocity.volumes).toEqual(['/srv/minepanel/data/velocity/server:/server']);
      expect(velocity.environment).toEqual({ TYPE: 'VELOCITY', ENABLE_RCON: 'true', RCON_PASSWORD: 'rcon-pass' });
      expect(velocity.networks).toEqual(['minepanel-network']);
      expect(compose.networks['minepanel-network']).toEqual({ external: true });
      expect(fs.writeFile).toHaveBeenCalledWith('/app/data/velocity/docker-compose.yml', expect.stringMatching(/^# Generated by Minepanel/));
    });
  });

  describe('velocity.toml', () => {
    it('lists members, orders the fallback chain and adds forced hosts', async () => {
      await service.writeConfig();
      const toml = written('/app/data/velocity/server/velocity.toml');

      expect(toml).toContain('player-info-forwarding-mode = "modern"');
      expect(toml).toContain('"lobby" = "lobby:25565"');
      expect(toml).toContain('"minigames" = "minigames:25565"');
      expect(toml).not.toContain('standalone');
      expect(toml).not.toContain('bedrock');
      expect(toml).not.toContain('modded');
      expect(toml).toContain('try = ["lobby", "survival"]');
      expect(toml).toContain('"hub.mc.example.com" = ["lobby"]');
      expect(toml).toContain('"survival.mc.example.com" = ["survival"]');
      expect(fs.writeFile).toHaveBeenCalledWith('/app/data/velocity/server/forwarding.secret', 'fwd-secret', { mode: 0o600 });
    });

    it('leaves forced hosts empty without a base domain', () => {
      const toml = service.buildVelocityToml([{ id: 'lobby', fallbackOrder: 0 }], null);

      expect(toml).toMatch(/\[forced-hosts\]\n\n?$/);
    });

    it('leaves out forced hosts that are invalid or already taken', () => {
      const toml = service.buildVelocityToml(
        [
          { id: 'lobby', hostname: 'play' },
          { id: 'survival', hostname: 'PLAY' },
          { id: 'evil', hostname: 'x"\n[servers]' },
          { id: 'game' },
        ],
        'mc.example.com',
      );

      expect(toml).toContain('"play.mc.example.com" = ["lobby"]');
      expect(toml).not.toContain('["survival"]');
      expect(toml).not.toContain('["evil"]');
      expect(toml).toContain('"game.mc.example.com" = ["game"]');
      expect(toml.match(/^\[servers\]$/gm)).toHaveLength(1);
    });

    it('escapes quotes and backslashes', () => {
      const toml = service.buildVelocityToml([{ id: 'a"b\\c' }], null);

      expect(toml).toContain('"a\\"b\\\\c" = "a\\"b\\\\c:25565"');
    });
  });

  describe('addresses', () => {
    it('lists each member at its forced host', async () => {
      expect(await service.getAddresses()).toEqual({
        survival: 'survival.mc.example.com',
        lobby: 'hub.mc.example.com',
        minigames: 'minigames.mc.example.com',
      });
    });

    it('falls back to the public IP without a base domain, and to nothing without either', async () => {
      instanceSettings.getEdge.mockResolvedValue({ enabled: true, mode: 'velocity', baseDomain: null });
      expect(await service.getAddresses()).toMatchObject({ lobby: '1.2.3.4' });

      instanceSettings.getNetwork.mockResolvedValue({ publicIp: null, lanIp: null });
      expect(await service.getAddresses()).toEqual({});
    });
  });

  describe('lifecycle', () => {
    it('detects whether the container is running', async () => {
      execMock.mockResolvedValueOnce({ stdout: 'abc\n' });
      expect(await service.isRunning()).toBe(true);
      execMock.mockResolvedValueOnce({ stdout: '\n' });
      expect(await service.isRunning()).toBe(false);
      execMock.mockRejectedValueOnce(new Error('no docker'));
      expect(await service.isRunning()).toBe(false);
    });

    it('writes its config before starting', async () => {
      expect(await service.start()).toBe(true);
      expect(written('/app/data/velocity/server/velocity.toml')).toBeDefined();
      expect(execMock).toHaveBeenLastCalledWith('docker compose up -d', { cwd: '/app/data/velocity' });
    });

    it('reports a failed start with the last line compose printed', async () => {
      execMock.mockRejectedValueOnce(
        Object.assign(new Error('Command failed'), {
          stderr:
            ' Container mc-velocity Starting \nError response from daemon: failed programming external connectivity on endpoint mc-velocity (' +
            'a'.repeat(64) +
            '): Bind for 0.0.0.0:25565 failed: port is already allocated\n',
        }),
      );
      expect(await service.start()).toBe(false);
      expect(service.startError).toBe('failed programming external connectivity on endpoint mc-velocity: Bind for 0.0.0.0:25565 failed: port is already allocated');

      expect(await service.start()).toBe(true);
      expect(service.startError).toBeNull();
    });

    it('refuses to start against a guessed host path', async () => {
      const unmounted = build(['/app/data']);
      expect(await unmounted.start()).toBe(false);
      expect(unmounted.startError).toContain('Nothing is mounted at /app/data');
      expect(execMock).not.toHaveBeenCalled();
    });

    it('stops only a project it has written', async () => {
      (fs.pathExists as unknown as jest.Mock).mockResolvedValueOnce(false);
      expect(await service.stop()).toBe(true);
      expect(execMock).not.toHaveBeenCalled();

      expect(await service.stop()).toBe(true);
      expect(execMock).toHaveBeenCalledWith('docker compose down', { cwd: '/app/data/velocity' });

      execMock.mockRejectedValueOnce(new Error('boom'));
      expect(await service.stop()).toBe(false);
    });

    it('reloads a running proxy after rewriting its config, and tolerates a failed reload', async () => {
      jest.spyOn(service, 'isRunning').mockResolvedValue(true);
      await service.syncConfig();
      expect(execMock).toHaveBeenCalledWith('docker exec mc-velocity rcon-cli velocity reload', undefined);

      execMock.mockRejectedValueOnce(new Error('rcon down'));
      await expect(service.syncConfig()).resolves.toBeUndefined();
    });

    it('only rewrites the config while the proxy is down', async () => {
      jest.spyOn(service, 'isRunning').mockResolvedValue(false);
      await service.syncConfig();
      expect(written('/app/data/velocity/server/velocity.toml')).toBeDefined();
      expect(execMock).not.toHaveBeenCalled();
    });
  });

  describe('reconcile', () => {
    it('starts Velocity when it is the enabled edge', async () => {
      jest.spyOn(service, 'isRunning').mockResolvedValue(false);
      await service.reconcile();
      expect(execMock).toHaveBeenCalledWith('docker compose up -d', { cwd: '/app/data/velocity' });
      expect(execMock).not.toHaveBeenCalledWith(expect.stringContaining('reload'), undefined);
    });

    it('reloads an already running proxy so a changed velocity.toml applies', async () => {
      jest.spyOn(service, 'isRunning').mockResolvedValue(true);
      await service.reconcile();
      expect(execMock).toHaveBeenCalledWith('docker exec mc-velocity rcon-cli velocity reload', undefined);
    });

    it('stops it when the edge is mc-router or off', async () => {
      instanceSettings.getEdge.mockResolvedValue({ enabled: true, mode: 'mc-router', baseDomain: 'mc.example.com' });
      jest.spyOn(service, 'isRunning').mockResolvedValue(true);
      await service.reconcile();
      expect(execMock).toHaveBeenCalledWith('docker compose down', { cwd: '/app/data/velocity' });
    });

    it('does nothing when it is neither wanted nor running', async () => {
      instanceSettings.getEdge.mockResolvedValue({ enabled: false, mode: 'velocity', baseDomain: null });
      jest.spyOn(service, 'isRunning').mockResolvedValue(false);
      await service.reconcile();
      expect(execMock).not.toHaveBeenCalled();
    });

    it('does not crash the boot when reconciling fails', async () => {
      instanceSettings.getEdge.mockRejectedValue(new Error('db down'));
      await expect(service.onApplicationBootstrap()).resolves.toBeUndefined();
    });
  });
});
