import { Injectable, Logger, OnApplicationBootstrap } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import * as fs from 'fs-extra';
import * as path from 'node:path';
import * as yaml from 'js-yaml';
import { escapeComposeValues } from 'src/common/compose/compose-escape';
import { DockerComposeService } from 'src/docker-compose/docker-compose.service';
import { InstanceSettingsService } from 'src/settings/instance-settings.service';
import { isValidHostname, ProxyService } from './proxy.service';
import { describeCommandFailure } from './command-failure';
import { isVelocityBackend } from './velocity-backend';

const execAsync = promisify(exec);

const VELOCITY_IMAGE = 'itzg/mc-proxy:2026.9.2-java25';
const CONTAINER_NAME = 'mc-velocity';
const PANEL_NETWORK = 'minepanel-network';
const GENERATED_HEADER = ['# Generated by Minepanel - do not edit by hand.', '# Managed from Settings -> Network; changes here are overwritten.'];

export interface VelocityMember {
  id: string;
  fallbackOrder?: number | null;
  hostname?: string;
}

const tomlString = (value: string) => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;

/**
 * Runs Velocity as its own compose project, the same way mc-router is run.
 *
 * The two are alternatives for the public port, never chained. The panel owns
 * velocity.toml and forwarding.secret; everything else under data/velocity/server
 * (plugins, their configs) belongs to the operator. The compose file sits one
 * level up so the RCON password in it is not readable by proxy plugins.
 */
@Injectable()
export class VelocityRuntimeService implements OnApplicationBootstrap {
  private readonly logger = new Logger(VelocityRuntimeService.name);
  private readonly DATA_HOST_DIR: string;
  private readonly DATA_HOST_DIR_IS_A_GUESS: boolean;
  private readonly PROJECT_DIR = '/app/data/velocity';
  // Why the last start failed, so the UI can say it instead of only showing "stopped".
  startError: string | null = null;

  constructor(
    private readonly configService: ConfigService,
    private readonly instanceSettings: InstanceSettingsService,
    private readonly dockerComposeService: DockerComposeService,
    private readonly proxyService: ProxyService,
  ) {
    this.DATA_HOST_DIR = this.configService.get('dataHostDir');
    this.DATA_HOST_DIR_IS_A_GUESS = (this.configService.get<string[]>('unresolvedHostPaths') ?? []).includes('/app/data');
  }

  async onApplicationBootstrap(): Promise<void> {
    try {
      await this.reconcile();
    } catch (error) {
      this.logger.error('Could not reconcile Velocity on startup', error);
    }
  }

  private getComposePath(): string {
    return path.join(this.PROJECT_DIR, 'docker-compose.yml');
  }

  private getServerDir(): string {
    return path.join(this.PROJECT_DIR, 'server');
  }

  async isRunning(): Promise<boolean> {
    try {
      const { stdout } = await execAsync(`docker ps --filter "name=^/${CONTAINER_NAME}$" --format "{{.ID}}"`);
      return stdout.trim().length > 0;
    } catch (error) {
      this.logger.warn('Failed to detect Velocity status', error);
      return false;
    }
  }

  async generateComposeFile(): Promise<string> {
    const [router, secrets] = await Promise.all([this.instanceSettings.getRouterSettings(), this.instanceSettings.getVelocitySecrets()]);

    const compose = {
      services: {
        velocity: {
          image: VELOCITY_IMAGE,
          container_name: CONTAINER_NAME,
          ports: [`${router.proxyPort}:25565`],
          environment: {
            TYPE: 'VELOCITY',
            ENABLE_RCON: 'true',
            RCON_PASSWORD: secrets.rconPassword,
          },
          volumes: [`${path.join(this.DATA_HOST_DIR, 'velocity', 'server')}:/server`],
          networks: [PANEL_NETWORK],
          restart: 'unless-stopped',
        },
      },
      networks: { [PANEL_NETWORK]: { external: true } },
    };

    await fs.ensureDir(this.PROJECT_DIR);
    const content = [...GENERATED_HEADER, '', ''].join('\n') + yaml.dump(escapeComposeValues(compose), { lineWidth: -1 });
    await fs.writeFile(this.getComposePath(), content);
    return content;
  }

  buildVelocityToml(members: VelocityMember[], baseDomain: string | null): string {
    const servers = members.map((member) => `${tomlString(member.id)} = ${tomlString(`${member.id}:25565`)}`);
    const tryOrder = members
      .filter((member) => typeof member.fallbackOrder === 'number')
      .sort((a, b) => (a.fallbackOrder as number) - (b.fallbackOrder as number))
      .map((member) => tomlString(member.id));
    // A duplicate key makes Velocity refuse the whole file, so a host that is invalid or
    // already taken (possible when hostnames were set before the base domain) is left out.
    const taken = new Set<string>();
    const forcedHosts: string[] = [];
    for (const member of baseDomain ? members : []) {
      const host = this.proxyService.generateHostname(member.id, baseDomain as string, member.hostname?.trim()).toLowerCase();
      if (!isValidHostname(host) || taken.has(host)) {
        this.logger.warn(`Skipping the forced host ${JSON.stringify(host)} of ${member.id}: it is invalid or used by another member`);
        continue;
      }
      taken.add(host);
      forcedHosts.push(`${tomlString(host)} = [${tomlString(member.id)}]`);
    }

    return [
      ...GENERATED_HEADER,
      'config-version = "2.7"',
      'bind = "0.0.0.0:25565"',
      'motd = "<#09add3>Minepanel network"',
      'online-mode = true',
      'force-key-authentication = true',
      'player-info-forwarding-mode = "modern"',
      'forwarding-secret-file = "forwarding.secret"',
      '',
      '[servers]',
      ...servers,
      `try = [${tryOrder.join(', ')}]`,
      '',
      '[forced-hosts]',
      ...forcedHosts,
      '',
    ].join('\n');
  }

  private async getMembers(): Promise<VelocityMember[]> {
    const index = await this.dockerComposeService.getServerIndex();
    return index
      .filter((server) => server.velocityEnabled && isVelocityBackend(server))
      .map((server) => ({ id: server.id, fallbackOrder: server.velocityFallbackOrder, hostname: server.proxyHostname }));
  }

  /**
   * Where players reach each member: its forced host, or the public IP (they land in
   * the lobby and switch with /server) when there is no base domain. Members with
   * neither are left out.
   */
  async getAddresses(): Promise<Record<string, string>> {
    const [members, edge, network] = await Promise.all([this.getMembers(), this.instanceSettings.getEdge(), this.instanceSettings.getNetwork()]);
    const entries = members
      .map((member) => [member.id, edge.baseDomain ? this.proxyService.generateHostname(member.id, edge.baseDomain, member.hostname) : network.publicIp])
      .filter(([, host]) => !!host);
    return Object.fromEntries(entries);
  }

  async writeConfig(): Promise<void> {
    const [members, edge, secrets] = await Promise.all([this.getMembers(), this.instanceSettings.getEdge(), this.instanceSettings.getVelocitySecrets()]);
    await fs.ensureDir(this.getServerDir());
    await fs.writeFile(path.join(this.getServerDir(), 'velocity.toml'), this.buildVelocityToml(members, edge.baseDomain));
    await fs.writeFile(path.join(this.getServerDir(), 'forwarding.secret'), secrets.forwardingSecret, { mode: 0o600 });
  }

  // A reload keeps connected players; a restart would not.
  private async reload(): Promise<void> {
    try {
      await execAsync(`docker exec ${CONTAINER_NAME} rcon-cli velocity reload`);
    } catch (error) {
      this.logger.warn('Velocity did not reload its config; it applies on the next restart', error);
    }
  }

  // Rewrites velocity.toml from the server index and applies it if the proxy is up.
  async syncConfig(): Promise<void> {
    await this.writeConfig();
    if (await this.isRunning()) await this.reload();
  }

  async start(): Promise<boolean> {
    // velocity.toml lives on a bind mount, so an unknown host path would start a
    // proxy with no servers at all.
    if (this.DATA_HOST_DIR_IS_A_GUESS) {
      this.startError = 'Nothing is mounted at /app/data. Mount a host directory or a named volume at /app/data.';
      this.logger.error(`Refusing to start Velocity: ${this.startError}`);
      return false;
    }

    try {
      await this.writeConfig();
      await this.generateComposeFile();
      await execAsync('docker compose up -d', { cwd: this.PROJECT_DIR });
      this.startError = null;
      this.logger.log('Velocity is up');
      return true;
    } catch (error) {
      this.startError = describeCommandFailure(error);
      this.logger.error('Failed to start Velocity', error);
      return false;
    }
  }

  async stop(): Promise<boolean> {
    try {
      if (!(await fs.pathExists(this.getComposePath()))) {
        return true;
      }
      await execAsync('docker compose down', { cwd: this.PROJECT_DIR });
      this.logger.log('Velocity is down');
      return true;
    } catch (error) {
      this.logger.error('Failed to stop Velocity', error);
      return false;
    }
  }

  async reconcile(): Promise<void> {
    const { enabled, mode } = await this.instanceSettings.getEdge();
    const wanted = enabled && mode === 'velocity';
    const running = await this.isRunning();

    if (wanted) {
      // Settings may have changed while it was up: compose up recreates only on a
      // compose diff, so a changed velocity.toml still needs the reload.
      if ((await this.start()) && running) await this.reload();
      return;
    }

    if (running) {
      await this.stop();
    }
  }
}
