import { ServerConfig } from "./types/types.d";

export interface ServerTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  config: Partial<ServerConfig>;
}

export const serverTemplates: ServerTemplate[] = [
  {
    id: "vanilla-survival",
    name: "vanillaSurvival",
    description: "vanillaSurvivalDesc",
    icon: "grass",
    color: "emerald",
    config: {
      serverType: "VANILLA",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
    },
  },
  {
    id: "vanilla-creative",
    name: "vanillaCreative",
    description: "vanillaCreativeDesc",
    icon: "diamond",
    color: "cyan",
    config: {
      serverType: "VANILLA",
      gameMode: "creative",
      difficulty: "peaceful",
      hardcore: false,
      pvp: false,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: false,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: true,
      allowFlight: true,
    },
  },
  {
    id: "vanilla-hardcore",
    name: "vanillaHardcore",
    description: "vanillaHardcoreDesc",
    icon: "spawner",
    color: "red",
    config: {
      serverType: "VANILLA",
      gameMode: "survival",
      difficulty: "hard",
      hardcore: true,
      pvp: true,
      maxPlayers: "10",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
    },
  },
  {
    id: "paper-performance",
    name: "paperPerformance",
    description: "paperPerformanceDesc",
    icon: "paper",
    color: "blue",
    config: {
      serverType: "PAPER",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "50",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
      useAikarFlags: true,
      viewDistance: "10",
      simulationDistance: "8",
    },
  },
  {
    id: "skyblock",
    name: "skyblock",
    description: "skyblockDesc",
    icon: "chest",
    color: "green",
    config: {
      serverType: "PAPER",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: false,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: false,
      generateStructures: false,
      allowNether: true,
      levelType: "minecraft:flat",
      onlineMode: true,
      commandBlock: true,
      allowFlight: false,
    },
  },
  {
    id: "pvp-arena",
    name: "pvpArena",
    description: "pvpArenaDesc",
    icon: "diamond-pickaxe",
    color: "orange",
    config: {
      serverType: "PAPER",
      gameMode: "adventure",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "32",
      spawnAnimals: false,
      spawnMonsters: false,
      spawnNpcs: false,
      generateStructures: false,
      allowNether: false,
      levelType: "minecraft:flat",
      onlineMode: true,
      commandBlock: true,
      allowFlight: false,
    },
  },
  {
    id: "peaceful-paradise",
    name: "peacefulParadise",
    description: "peacefulParadiseDesc",
    icon: "golden-apple",
    color: "yellow",
    config: {
      serverType: "VANILLA",
      gameMode: "survival",
      difficulty: "peaceful",
      hardcore: false,
      pvp: false,
      maxPlayers: "20",
      spawnAnimals: true,
      spawnMonsters: false,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:default",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
    },
  },
  {
    id: "amplified-world",
    name: "amplifiedWorld",
    description: "amplifiedWorldDesc",
    icon: "emerald",
    color: "purple",
    config: {
      serverType: "VANILLA",
      gameMode: "survival",
      difficulty: "normal",
      hardcore: false,
      pvp: true,
      maxPlayers: "15",
      spawnAnimals: true,
      spawnMonsters: true,
      spawnNpcs: true,
      generateStructures: true,
      allowNether: true,
      levelType: "minecraft:amplified",
      onlineMode: true,
      commandBlock: false,
      allowFlight: false,
      maxMemory: "4G",
    },
  },
];

export const getTemplateById = (id: string): ServerTemplate | undefined => {
  return serverTemplates.find((t) => t.id === id);
};
